### ISSUE TITLE
Improve serialization

### ISSUE THREAD

**Issue by davidtsadler** [davidtsadler/ebay-sdk-php#1]
Look at improving the serialization of the SDK.

One possible solution is for the SDK to implement the [Serializable interface](http://php.net/manual/en/class.serializable.php)

Another solution is to improve the passing of property values via the constructor. At the moment it is possible to do the following.

```php
$item->Variations->Variation[] = new Types\VariationType(array(
    'SKU' => 'TS-W-S',
    'Quantity' => 5,
    'StartPrice' => new Types\AmountType(array('value' => 10.99)),
    'VariationSpecifics' => array(new Types\NameValueListArrayType(array(
        'NameValueList' => array(
            new Types\NameValueListType(array('Name' => 'Color', 'Value' => array('White'))),
            new Types\NameValueListType(array('Name' => "Size (Men's)", 'Value' => array('S')))
        )
    )))
));
```

However the above method involves constructing objects before passing them via the array. An improvement would be to *also allow* the following.

```php
$item->Variations->Variation[] = new Types\VariationType(array(
    'SKU' => 'TS-W-S',
    'Quantity' => 5,
    'StartPrice' => array('value' => 10.99),
    'VariationSpecifics' => array((array(
        'NameValueList' => array(
            array('Name' => 'Color', 'Value' => array('White')),
            array('Name' => "Size (Men's)", 'Value' => array('S'))
        )
    )))
));
```

This solution could allow the usage shown below when calling the [toArray](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/Types/BaseType.php#L223) method.

```php
if (Cache::has($key)) {
    // Create a new instance and populates its properties with values from the cache.
    $results = new FindItemsAdvancedResponse(Cache::get($key));
    return $results;
}

$results = $service->findItemsAdvanced($this->request);

// Cache the values of the response object.
// toArray returns an assoicated array of the response object properties.
Cache::put($key,$results->toArray(),24*60);
```

**Comment by davidtsadler** [comment]
Implemented in https://github.com/davidtsadler/ebay-sdk-php/commit/d8457f4f0fbf95c02b7389458fc646e1d6e60fbf

**Comment by shreyanshpanchal** [comment]
How do you convert `\DTS\eBaySDK\Trading\Types\GetAccountResponseType` response to array?
I'm trying to save this whole object in Cache for later use. 

- If i simply type cast it to array & populate it while retrieval: I get this `Unknown property DTS\eBaySDK\Types\BaseTypevalue` error. Which is rightfully so caused by array having: BaseType key.

Can anyone help please?

**Comment by shreyanshpanchal** [comment]
It's what becomes of the array as i typecast it from response object.
``` 
   array (size=2)
  '�DTS\eBaySDK\Types\BaseType�values' => 
    array (size=11)
      'Timestamp' => 
        object(DateTime)[571] ```
