### ISSUE TITLE
Can this package be imported into symfony 3.7

### ISSUE THREAD

**Issue by durovin12** [davidtsadler/ebay-sdk-php#100]
I am trying to import this package into my symfony3.7 project but the composer dependancy doesn't seem to be working for this particular projects, wanted to find out whether it was possible to do this with this sdk?

**Comment by davidtsadler** [comment]
I have not much experience with symfony3.7 so can't give you an answer with the information that you have provided. 

I've provide a forum at https://forum.devbay.net/ and https://groups.google.com/forum/#!forum/ebay-sdk-php where questions regarding the usage of the API may have a better chance of been answered.
