### ISSUE TITLE
issue with loading class from the sdk

### ISSUE THREAD

**Issue by durovin12** [davidtsadler/ebay-sdk-php#103]
there is a an issue i am having when i attempt to load the Trading\Types Namespace into my php symfony class, i know for a fact when I load the Shopping\Types Namespace and call the geteBayTime() class there is no autload issue?

error message :

Attempted to load class "GetMyMessagesRequestType" from namespace "DTS\ebaySDK\Trading\Types".
Did you forget a "use" statement for "DTS\eBaySDK\Trading\Types\GetMyMessagesRequestType"?

code :

$service = new Services\TradingService([
    'authToken'=> "",
    'credentials' => [
      'appId' => '',
      'certId' => '',
      'devId' => ''
    ],
    'siteId'=>0
  ]);
$request = new Types\GetMyMessagesRequestType();

**Comment by davidtsadler** [comment]
Would changing the code to be the below work?

```php
$request = new DTS\eBaySDK\Trading\Types\GetMyMessagesRequestType();
```

**Comment by durovin12** [comment]
Same problem has occurred.

**Comment by durovin12** [comment]
I did install the package via composer and I don't get the same problem when I load the shopping namespace and call a class from the services and types namespaces respectively.

**Comment by davidtsadler** [comment]
Don't have much experience with symphony so not sure at the moment what to advise. You may get a better answer via the forums.

https://groups.google.com/forum/m/#!forum/ebay-sdk-php
https://forum.devbay.net
