### ISSUE TITLE
Post-Order:submitCancellationRequest - Unknown property exception

### ISSUE THREAD

**Issue by kingsaj** [davidtsadler/ebay-sdk-php#105]
Hi,

I'm trying to make a submitCancellationRequest call in sandbox, which is part of the post-order apis

Soon as this line is run:
```php
$response = $service->submitCancellationRequest($request);
```

It crashes out with the below error:
```php
DTS\eBaySDK\Exceptions\UnknownPropertyException with message 'Unknown property errorName'
```

I've tried to debug and this is the raw json that is returned, which is what I'm expecting for the orderId I provided..

```json
{
    "error": [{
        "errorId": 10005,
        "domain": "CancelSvcErrorDomain",
        "subdomain": "Buying",
        "severity": "ERROR",
        "category": "APPLICATION",
        "message": "Eligibility Check failed",
        "parameter": [],
        "errorName": "eligibilityCheckFailed",
        "resolution": "Retry",
        "organization": "Marketplace",
        "errorGroups": ""
    }]
}
```

Regards

**Comment by davidtsadler** [comment]
Looks like another case where the API response is not matching the [documentation](https://developer.ebay.com/Devzone/post-order/ErrorResponse.html#ErrorResponse). 

I'll add the missing fields to the [Error](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/PostOrder/Types/Error.php) class.
