### ISSUE TITLE
How to catch 503: Service Unavailable / BadResponseException ?

### ISSUE THREAD

**Issue by itsonit** [davidtsadler/ebay-sdk-php#11]
A 503 API call produce a fatal error:

`[17-Nov-2015 22:10:32 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\ServerErrorResponseException' with message 'Server error response
[status code] 503
[reason phrase] Service Unavailable
[url] https://api.ebay.com/ws/api.dll' in /etc/cudgelmiddleware/code/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /etc/cudgelmiddleware/code/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /etc/cudgelmiddleware/code/vendor/symfony/event-dispatcher/EventDispatcher.php(158): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /etc/cudgelmiddleware/code/vendor/symfony/event-dispatcher/EventDispatcher.php( in /etc/cudgelmiddleware/code/vendor/guzzle/guzzle/src/Guzzle/Http/Exception/BadResponseException.php on line 43`

Best practise to catch this? ty very much!

**Comment by davidtsadler** [comment]
There are a few options available.

Just catch the exception.

```php
try
{
    $response =  $service->operation($request);
    // Handle successful response.
}
catch(Exception $e)
{
    /**
     * Add strategy for dealing with the exception. 
     * For example log exception message or re-try request.
     */
}
```

You can also get access to the actual Guzzle3 object that sends the request. The [httpClient](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/Services/BaseService.php#L144) method returns the [HttpClient](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/HttpClient/HttpClient.php) object that the SDK uses for sending the request. This object uses a Guzzle3 instance that can be obained via the [guzzle](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/HttpClient/HttpClient.php#L46) method. This will enable you to use some of the Guzzle3 plugins that are available.
 
```php
use GuzzleHttp\Subscriber\Retry\RetrySubscriber;
/**
 * Use a plugin that retrys 500 and 503 responses.
 */
$retry = new RetrySubscriber([
    'filter' => RetrySubscriber::createStatusFilter()
]);

$service = new Services\TradingService(...);
/**
 * Attach pluging to Guzzle3 object.
 */
$service->httpClient()->guzzle()->getEmitter()->attach($retry);

$response =  $service->operation($request);
```

It's also possible to supply the SDK with your own HTTP client and let that handle the actual request. You can then implement what ever retry mechanisam and error handling that you feel is suitable for your project. There is an [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/misc/01-http-client.php) available that shows how to use cURL to send requests to the API.

**Comment by itsonit** [comment]
Thank you for your detailed reply! (:

I had already tried to catch the exception globally, but that did not work.

I will try to solve it with Guzzle RetrySubscriber as you described.

**Comment by itsonit** [comment]
Shame on me. I just only catched a CurlException, not a general.. Sorry for the noise.
