### ISSUE TITLE
Add allowance to silently ignore extra fields

### ISSUE THREAD

**Issue by chuhta** [davidtsadler/ebay-sdk-php#112]
When eBay is updating a minor version, this can cause a shutdown of the endpoint through the SDK. This is a result of eBay adding new fields to the endpoint, such as during [version 1.2.0](https://developer.ebay.com/devzone/rest/sell/content/fulfillment/release-notes.html).

This is in conflict with [eBay's versioning docs](http://developer.ebay.com/Devzone/rest/ebay-rest/content/versioning.html). Major versions can be BC breaks, while minor versions should be safe to update to at leisure. However, due to the non-allowance of extraneous fields in API responses, the SDK breaks anytime eBay adds new data to their APIs.

**Comment by davidtsadler** [comment]
@chuhta the 12.0.1 release should hopefully address this issue. Let me know if there are any problems.
