### ISSUE TITLE
Taxonomy API Support

### ISSUE THREAD

**Issue by Silentscripter** [davidtsadler/ebay-sdk-php#116]
Any plan to support [Taxonomy API](https://developer.ebay.com/devzone/rest/commerce/content/taxonomy/overview.html)?

Anyway thanks a lot for your package, it rocks !

**Comment by davidtsadler** [comment]
Support for the Taxonomy API is currently on the develop [branch](https://github.com/davidtsadler/ebay-sdk-php/tree/develop/src/Taxonomy). I'm hoping to get this merged into the main branch do a full release over the next week.

I'll leave this issue open in case anyone else is interested and close it once the support is live.

**Comment by davidtsadler** [comment]
Support for the Taxonomy API has been added to the 13.0.0 release.

**Comment by davidtsadler** [comment]
There is also an [example available](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/taxonomy/01-get-default-category-tree-id.php).
