### ISSUE TITLE
ResolutionCaseManagement\Types\Integer not found

### ISSUE THREAD

**Issue by 1mr3yn** [davidtsadler/ebay-sdk-php#12]
I'm trying to use the ResolutionCaseManagement but I keep having this error

`Fatal error: Class 'DTS\eBaySDK\ResolutionCaseManagement\Types\Integer' not found in C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Parser\XmlParser.php on line 228`

Here is my code

    $request = new Types\GetActivityOptionsRequest();
    $request->caseId = new Types\CaseIdType();
    $request->caseId->id = '1111111111';
    $request->caseId->type = 'EBP_INR
    $response = $service->getActivityOptions($request);

Is the file really missing?

Thanks.
Reyn

**Comment by davidtsadler** [comment]
Leave this with me. I'll take a look tomorrow. I think I know what the issue may be. I belive the XML parser is thinking a field in the XML response should be an instance of a class called Integer, which does not exist. I think the parser is wrong and the field is just a real integer rather than an instance of some class. I will know more when I look into it further.

**Comment by 1mr3yn** [comment]
I got another fatal error for both getActivityOptions and getEBPCaseDetail. My code is still in the same format:

    $request = new Types\GetEBPCaseDetailRequest();
    $request->caseId = new Types\CaseIdType();
    $request->caseId->id = '5088683312';
    $request->caseId->type = 'EBP_INR';
    $response = $service->getEBPCaseDetail($request);

and I got this error

    Fatal error:  Uncaught exception 'DTS\eBaySDK\Exceptions\UnknownPropertyException' with message 'Unknown property: DTS\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse::cases' in C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php:443
Stack trace:
#0 C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(276): DTS\eBaySDK\Types\BaseType::ensurePropertyExists('DTS\\eBaySDK\\Res...', 'cases')
#1 C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(88): DTS\eBaySDK\Types\BaseType->get('DTS\\eBaySDK\\Res...', 'cases')
#2 C:\xampp\htdocs\ebay-sdk\getUserCases.php(39): DTS\eBaySDK\Types\BaseType->__get('cases')
#3 {main}
  thrown in C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php on line 443

**Comment by 1mr3yn** [comment]
Thank you for the response. But anyway im having another fatal error, for both getEBPCaseDetail and getActivityOptions. Code is still the same format

    $request = new Types\GetEBPCaseDetailRequest();
    $request->caseId = new Types\CaseIdType();
    $request->caseId->id = '5088683312';
    $request->caseId->type = 'EBP_INR';
    $response = $service->getEBPCaseDetail($request);

And the error:

    Fatal error:  Uncaught exception 'DTS\eBaySDK\Exceptions\UnknownPropertyException' with message 'Unknown property: DTS\eBaySDK\ResolutionCaseManagement\Types\GetEBPCaseDetailResponse::cases' in C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php:443
Stack trace:
    #0 C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(276): DTS\eBaySDK\Types\BaseType::ensurePropertyExists('DTS\\eBaySDK\\Res...', 'cases')
    #1 C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php(88): DTS\eBaySDK\Types\BaseType->get('DTS\\eBaySDK\\Res...', 'cases')
    #2 C:\xampp\htdocs\ebay-sdk\getUserCases.php(41): DTS\eBaySDK\Types\BaseType->__get('cases')
    #3 {main} thrown in C:\xampp\htdocs\ebay-sdk\src\DTS\eBaySDK\Types\BaseType.php on line 443

**Comment by 1mr3yn** [comment]
Though the request is success. But the result is empty

     [activityOptions] => DTS\eBaySDK\ResolutionCaseManagement\Types\ActivityOptionListType Object
                (
                    [values:DTS\eBaySDK\Types\BaseType:private] => Array
                        (
                        )

                    [attachment:DTS\eBaySDK\Types\BaseType:private] => Array
                        (
                            [data] => 
                            [mimeType] => 
                        )

                )

**Comment by davidtsadler** [comment]
There is a new [0.5.0](https://github.com/davidtsadler/ebay-sdk-php/releases/tag/0.5.0) release available. It should fix the `Fatal error: Class 'DTS\eBaySDK\ResolutionCaseManagement\Types\Integer' not found` error. Not sure if this will resolve your other issues so I will leave this open for the time been as I may need more information from you.

**Comment by davidtsadler** [comment]
Closing this but please feel free to open a new issue if you are still having problems since the 0.5.0 release.
