### ISSUE TITLE
Installing on Laravel 5.4

### ISSUE THREAD

**Issue by towhitch** [davidtsadler/ebay-sdk-php#120]
I installed this package using composer and tried to get one of the provided examples to work. I was unsuccessful. I am running Windows 10. I guess I don't know where to put the example code at in my code.  

Example Code
https://github.com/davidtsadler/ebay-sdk-examples/blob/master/finding/01-simple-keywords-search.php

I tried putting it all in a view and break it up a little with a controller. But I would get errors App\HTTP\Controllers\Ebay is missing so I would create a standard ebay controller and that would bring up a problem with Config (I did setup my env file and change the variable names to match).

This line - $config = require __DIR__.'/../configuration.php';

I don't have this configuration.php file within my install. Is this something I need to create myself? Sorry If I am not explaining this properly, I am not that great of a developer but I am trying to learn. Let me know if you need any other information.

**Comment by michabbb** [comment]
take the [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/configuration.php.example) and change everything to your needs....

**Comment by towhitch** [comment]
Thanks for the fast reply. I tried that as well but the error never changed (I'll try again as soon as I get home). I work with some developers and they mentioned it might be from how I am running laravel and instead run it using homestead but that hasn't really changed anything and homestead isn't working right for me either. Sometimes it works but most of the time it doesn't.

**Comment by davidtsadler** [comment]
Just [hardcode](http://devbay.net/sdk/guides/guide/configuration.html#credentials) your credentials to begin with.  Look at moving them into a configuration file once you have it working.

**Comment by michabbb** [comment]
keep in mind `$config` is only an array. in your case, when you work with laravel, i would consider to put everything into your `.env` file... and access this with the [known laravel methodes](https://laravel.com/docs/5.4/configuration#retrieving-environment-configuration)

**Comment by towhitch** [comment]
I think I am going to try and hardcode it first and see where I can get from there. I had an api call working with some basic xml but I want to step up my game. Thanks again for the help.
