### ISSUE TITLE
[Help request] SetStoreCategories call ignores ChildCategory

### ISSUE THREAD

**Issue by Silentscripter** [davidtsadler/ebay-sdk-php#121]
Hello, of course this is not a bug related with your package but I'd like to know if you may help me.

I can't upload a category tree to the ebay store with SetStoreCategories call since the ChildCategory is always ignored and only top level categories are added. 

Is there any advice to handle this or am I forced to add categories one level at a time?

**Comment by davidtsadler** [comment]
I'm not 100% sure but you may have to  upload one level at a time. Also in future please ask personal issues with the SDK via the [forum](https://forum.devbay.net/).
