### ISSUE TITLE
Order->CreatedTime not inserted in database

### ISSUE THREAD

**Issue by zLegend-210** [davidtsadler/ebay-sdk-php#123]
While retreiving orders and saving them, I have a created_at column which of type timestamp, When inserting Order->CreatedTime it saves now datetime, I tried to fix this by 
```
Order->CreatedTime->format('Y-m-d H:i:s');
```
and not working.

Any suggestions? Thanks <3

**Comment by davidtsadler** [comment]
Please ask personal issues with the SDK via the [forum](https://forum.devbay.net/).  And please provide more information other than "it's not working".

**Comment by zLegend-210** [comment]
Anyway I found the solution, I'm using Laravel and was migrating the purchase date column as a timestamp, I changed it to datetime and it's working fine.
