### ISSUE TITLE
Small pictuers on ebay add item

### ISSUE THREAD

**Issue by slaveykov** [davidtsadler/ebay-sdk-php#125]
Hello, i have a problem with gallery pictures on ebay.
I use this code with addFixedPriceItem api

	// pictures
		$item->PictureDetails = new \DTS\eBaySDK\Trading\Types\PictureDetailsType();
		$item->PictureDetails->GalleryType = \DTS\eBaySDK\Trading\Enums\GalleryTypeCodeType::C_GALLERY; 
		$item->PictureDetails->PhotoDisplay = \DTS\eBaySDK\Trading\Enums\PhotoDisplayCodeType::C_SUPER_SIZE; 
		$item->PictureDetails->PictureURL = $itemInfo['gallery_images'];//its array with images

Evrything is okay when i add item. The pictures are 1600x1600px on revising item, but on main item url is small (500px) without gallery. Please, help!

**Comment by michabbb** [comment]
because i don´t use `PhotoDisplay` and `GalleryType` (and never used it, i use additem with the trading api), maybe give it a try and make calls without that option and see if that changes anything for you ?

**Comment by michabbb** [comment]
don´t know if it has anything todo with your problem, the [api](http://developer.ebay.com/devzone/xml/docs/reference/ebay/additem.html#Request.Item.PictureDetails.GalleryType) says:

> SuperSize - Only available for site-hosted (EPS) images.

i am used to upload **all images** to ebay, get the new ebay image url and use it for add/revise item,
maybe this sounds complicated to someone, but i never had any problems with this and 1600px images
are working very nice.

**Comment by timramseyjr** [comment]
Are you in production or sandbox?  I remember the main image being small on sandbox(they resize to reduce image file size), but once I switched to production the image was the correct size.

**Comment by slaveykov** [comment]
// pictures
		$item->PictureDetails = new \DTS\eBaySDK\Trading\Types\PictureDetailsType();
		$item->PictureDetails->PictureURL = $itemInfo['gallery_images'];

Now im use only  this but i dont see diffrence.. btw i upload images first on ebay server and when i recive a links of images i submit listing.

**Comment by slaveykov** [comment]
This is the front image: https://i.ebayimg.com/images/g/aQgAAOSwJS5ZgKGv/s-l500.jpg
This is the image when i revise a product: http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/aQgAAOSwJS5ZgKGv/$_57.JPG?set_id=8800005007

**Comment by slaveykov** [comment]
The api is in a production mode.

**Comment by michabbb** [comment]
@slaveykov whats the itemid ? do you have a source url for your 1600x1600 image ?

**Comment by slaveykov** [comment]
this is the item http://www.ebay.com/itm/202005261557

**Comment by slaveykov** [comment]
I send this to ebay
   ["PictureDetails"]=&gt;
        object(DTS\eBaySDK\Trading\Types\PictureDetailsType)#102 (2) {
          ["values":"DTS\eBaySDK\Types\BaseType":private]=&gt;
          array(3) {
            ["GalleryType"]=&gt;
            string(7) "Gallery"
            ["PhotoDisplay"]=&gt;
            string(9) "SuperSize"
            ["PictureURL"]=&gt;
            object(DTS\eBaySDK\Types\RepeatableType)#103 (5) {
              ["data":"DTS\eBaySDK\Types\RepeatableType":private]=&gt;
              array(10) {
                [0]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/O-UAAOSwIwJZgeQA/$_10.JPG?set_id=8800005007"
                [1]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/O-UAAOSwIwJZgeQA/$_10.JPG?set_id=8800005007"
                [2]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/S-MAAOSwzRlZgeQE/$_10.JPG?set_id=8800005007"
                [3]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/Gy0AAOSwH4NZgeQG/$_10.JPG?set_id=8800005007"
                [4]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/GfsAAOSwLIhZgeQK/$_10.JPG?set_id=8800005007"
                [5]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/1C8AAOSwFjNZgeQN/$_10.JPG?set_id=8800005007"
                [6]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/DxgAAOSwp1RZgeQQ/$_10.JPG?set_id=8800005007"
                [7]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/K5AAAOSwSCZZgeQT/$_10.JPG?set_id=8800005007"
                [8]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/TxgAAOSw3IdZgeQY/$_10.JPG?set_id=8800005007"
                [9]=&gt;
                string(84) "http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/BbAAAOSwk6pZgeQc/$_10.JPG?set_id=8800005007"
              }

**Comment by michabbb** [comment]
@slaveykov so when i do a getitem for your item, i see this:

```php
[GalleryURL] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/jm4AAOSw8apZgKGz/$_57.JPG?set_id=8800005007
[PhotoDisplay] => PicturePack
[PictureURL] => DTS\eBaySDK\Types\UnboundType Object
    (
        [data:DTS\eBaySDK\Types\UnboundType:private] => Array
            (
                [0] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/jm4AAOSw8apZgKGz/$_57.JPG?set_id=8800005007
                [1] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/aQgAAOSwJS5ZgKGv/$_57.JPG?set_id=8800005007
                [2] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/qwkAAOSwqklZgKG2/$_57.JPG?set_id=8800005007
                [3] => http://i.ebayimg.com/00/s/Mjk5WDUwMA==/z/szMAAOSwOt9ZgKG4/$_57.JPG?set_id=8800005007
                [4] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/bA0AAOSwq9lZgKG7/$_57.JPG?set_id=8800005007
                [5] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/q~UAAOSwIwJZgKG~/$_57.JPG?set_id=8800005007
                [6] => http://i.ebayimg.com/00/s/NTAwWDUwMA==/z/-X4AAOSwhURZgKHC/$_57.JPG?set_id=8800005007
            )
    )
```

and the `GalleryURL` image is 1600x1600 so i don´t really know what to say.
if the item would be online, you should see the zoom effect for the image.
[maybe you can enable the item and set quantity to zero,](http://developer.ebay.com/devzone/xml/docs/reference/ebay/ReviseItem.html#ChangeHistory) because in this case,
the item is still online, but nobody finds it or is able to buy it.

> 8232013-05-08 | Item.OutOfStockControl (added): Flag that when set to 'true' hides a listing when the quantity of the item goes to 0 (zero) but keeps the listing alive.

i guess the gallery should work if the item is "disabled" but still online.
so we can see you item alive and are able to debug this (better).

**Comment by slaveykov** [comment]
The item is active now www.ebay.com/itm/202007307053

**Comment by michabbb** [comment]
@slaveykov right now: it isn´t: 

> This listing was ended by the seller because the item is no longer available.
