### ISSUE TITLE
FindItemsByKeywordsRequest and FindItemsByProductRequest with variations?

### ISSUE THREAD

**Issue by AlexBa** [davidtsadler/ebay-sdk-php#126]
Hey,
just one quick question: Is it possible to perform `FindItemsByKeywordsRequest` and `FindItemsByProductRequest` with variants? If not, then how is it possible to get the variants of a specific product or within a keyword search?

I have searched a long time with no results..

Thank you!

**Comment by michabbb** [comment]
This question is not related to this framework, please use the forum or the official ebay support pages... 

https://groups.google.com/group/ebay-sdk-php
https://forums.developer.ebay.com/
