### ISSUE TITLE
Call to undefined function httpHandler()

### ISSUE THREAD

**Issue by omrcm** [davidtsadler/ebay-sdk-php#127]
Hi there,
first one thanks  for the ebay sdk. I get errors when I try to call $service->getUserToken. 
The error is Call to undefined function httpHandler(). When I open the file OAuthService.php and go to the error line there is ;
        $httpHandler = $this->getConfig('httpHandler');
        $httpOptions = $this->getConfig('httpOptions');

how can I fix this issue.

Best Regards

**Comment by davidtsadler** [comment]
I have set-up a forum over at https://forum.devbay.net/ where questions about using the SDK can be raised. It will help as well if you can provide an example of the code that is causing the error.
