### ISSUE TITLE
statusCode 405 - processReturnRequest

### ISSUE THREAD

**Issue by artemmelnik** [davidtsadler/ebay-sdk-php#129]
Hi, I'm trying to make a request through SDK. PostOrderService
`/**
     * @param string $returnId
     * @return \DTS\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse
     * @throws EbayPostOrderApiException
     */
    public function decideApprove($returnId)
    {
        if (false === $returnId) {
            throw new EbayPostOrderApiException('Invalid property type provided for returnId.');
        }

        $request = new ProcessReturnRequestRestRequest();
        $request->returnId = $returnId;
        $request->decision = DecisionEnum::C_APPROVE;

        return $this->getService()->processReturnRequest($request);
    }`

Returns

`object(DTS\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse)[408]
  private 'values' (DTS\eBaySDK\Types\BaseType) => 
    array (size=0)
      empty
  private 'attachment' (DTS\eBaySDK\Types\BaseType) => 
    array (size=2)
      'data' => null
      'mimeType' => null
  private 'statusCode' => int 405
  private 'headers' => 
    array (size=2)
      'Content-Type' => 
        array (size=1)
          0 => string 'text/plain' (length=10)
      'Content-Length' => 
        array (size=1)
          0 => string '0' (length=1)
  private 'headerNames' => 
    array (size=2)
      'content-type' => string 'Content-Type' (length=12)
      'content-length' => string 'Content-Length' (length=14)`

Help me please.

**Comment by davidtsadler** [comment]
Looks like it's an issue with the SDK. I believe the issue is [here](https://github.com/davidtsadler/ebay-sdk-php/blob/828c48e68c24ea3b67c3df04e9a92199321201d7/src/PostOrder/Services/PostOrderService.php#L634) where it's using the wrong http method to send the request. It's a typo as it should be POST not MET. I'll get a fix done as soon as possible.

**Comment by davidtsadler** [comment]
The 13.0.1 release should stop the status code 405 been returned from the API.

**Comment by artemmelnik** [comment]
Thank David. 

`'ProcessReturnRequest' => [
            'method' => 'POST',
            'resource' => 'return/{returnId}/decide',
            'responseClass' => '\DTS\eBaySDK\PostOrder\Types\ProcessReturnRequestRestResponse',
            'params' => [
                'returnId' => [
                    'valid' => ['string'],
                    'required' => true
                ]
            ]
        ],`
