### ISSUE TITLE
Unknown property: DTS\eBaySDK\Trading\Types\OrderIDArrayType::0

### ISSUE THREAD

**Issue by bbtimx** [davidtsadler/ebay-sdk-php#13]
Hey

I try to get the Order Transaction but end up in this Exception:

**Fatal error: Uncaught exception 'DTS\eBaySDK\Exceptions\UnknownPropertyException' with message 'Unknown property: DTS\eBaySDK\Trading\Types\OrderIDArrayType::0'**

My Code Sample:

```php
$orderIDs = array( '111111115645-22222222001');
$array = array( 'OrderIDArray' => $orderIDs );

$request = new Types\GetOrderTransactionsRequestType( $array );

$response = $service->getOrderTransactions($request);

var_dump( $response );
```

Same Error:
```php
$orderIDs = array( '111111115645');
```

Any Solution?
THX

**Comment by davidtsadler** [comment]
You need to assign the IDs to the [OrderID](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetOrderTransactions.html#Request.OrderIDArray.OrderID) property that is a member if OrderIDArray.

```php
$array = array( 'OrderIDArray' => array('OrderID' => $orderIDs));
```
