### ISSUE TITLE
GetSimilarItems returns Failed to parse timestring

### ISSUE THREAD

**Issue by yamenarahman** [davidtsadler/ebay-sdk-php#132]
![screenshot from 2017-08-27 18-50-22](https://user-images.githubusercontent.com/24607365/29752166-51b3f73a-8b59-11e7-9181-b8084d559b0c.png)
As shown in this screenshot there are items returned and I think the request is send successfully but this error maybe caused by something in recieving the response.
Here's my code:
```
$request = new Merchandising\Types\GetSimilarItemsRequest();

$request->maxResults = 10;
$request->itemId = $id;
$response = self::$service->getSimilarItems($request);

        if (isset($response->Errors)) {
            foreach ($response->Errors as $error) {
                printf(
                    "%s: %s\n%s\n\n",
                    $error->SeverityCode === Merchandising\Enums\SeverityCodeType::C_ERROR ? 'Error' : 'Warning',
                    $error->ShortMessage,
                    $error->LongMessage
                );
            }
        }

        if ($response->Ack !== 'Failure') {
            return $response; // print_r() not workin also.
        }
```

**Comment by davidtsadler** [comment]
I think eBay returns a invalid date and time in the response that is causing the exception when the SDK tries and parses it. Will need to think how to handle this as eBay should be returning valid values.

**Comment by yamenarahman** [comment]
Waiting for you Boss!
