### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by itank** [davidtsadler/ebay-sdk-php#135]
I'm trying to import all ebay categories using GetCategoriesRequestType. Importing from each country one at a time goes well, looping through each country cause memory overflow. 

 Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in  /vendor/dts/ebay-sdk-php/src/Types/BaseType.php on line 162

**Comment by davidtsadler** [comment]
GetCategories can return a huge amount of data. From memory the US site alone had about 18,000 categories. That's 18,000 PHP objects created once the SDK has parsed the XML response.

You can use OutputSelector to reduce the amount of information that is returned from eBay, but this won't reduce the number of objects created by the SDK.

You are either going to have to increase the memory allocated to the PHP script or just continue to get one country at a time.
