### ISSUE TITLE
Cannot iterate over properties that are an array?

### ISSUE THREAD

**Issue by ChangePlaces** [davidtsadler/ebay-sdk-php#137]
I'm trying to parse the GeteBayDetails response and convert all the CountryDetails to an array:

`$payload['countryDetails'] = array_walk($resp->CountryDetails, function($x){return $x->toArray();});`

Except the first $x is actually the whole countrydetails array - it instead iterates over the 5 elements of CountryDetails object instead of through them, so I get the error that I'm calling `toArray` on an array.

How can I actually do what I want to do?

**Comment by davidtsadler** [comment]
CountryDetails is not a true array, but is "array like" in that it [implements](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Types/RepeatableType.php#L12) ArrayAccess, Countable, and Iterator.

For the most part you can treat it as a normally array. However, for some functions you need to first call [iterator_to_array](http://php.net/manual/en/function.iterator-to-array.php) to convert it into a true array.

Also array_walk returns a boolean. I think you need to call [array_map](http://php.net/manual/en/function.array-map.php) to get what you want.

```php
$array = iterator_to_array($response->CountryDetails);
$results = array_map(function ($countryDetails) {
    return $countryDetails->toArray();
}, $array);
```

The above can also be reduced to a single line as the SDK [supports JMESPath Expressions](http://devbay.net/sdk/guides/guide/jmespath.html);

```php
$results = $response->search('CountryDetails[]');
```

**Comment by ChangePlaces** [comment]
wow - excellent thanks. learn something new everyday!
