### ISSUE TITLE
WithdrawOffer missing from InventoryService

### ISSUE THREAD

**Issue by Silentscripter** [davidtsadler/ebay-sdk-php#139]
The `withdrawOffer` method and corresponding request and response types seems to be missing from `InventoryService`.

[WithdrawOffer docs](https://developer.ebay.com/api-docs/sell/inventory/resources/offer/methods/withdrawOffer)

**Comment by Silentscripter** [comment]
Hello, ETA about this?

**Comment by davidtsadler** [comment]
I'll try and get this done over the weekend. I've been caught up with other things and shouldn't have left this for the time that I have, so I apologize for that.

**Comment by Silentscripter** [comment]
Hi, no problem. I've added a pull request to help with this task if you prefer
