### ISSUE TITLE
FindItemsAdvancedRequest - Cant find items from seller if no category ID or Keyword is used.

### ISSUE THREAD

**Issue by Skateboss** [davidtsadler/ebay-sdk-php#14]
$request = new Types\FindItemsAdvancedRequest();
    $request->itemFilter->name = 'Seller';
    $request->itemFilter->value = $seller_ID;

^ should be enough to return all sellers items but get this result "Error: Keyword or category ID are required."

according to this page: 
http://developer.ebay.com/devzone/finding/callref/types/FindItemsAdvancedRequest.html#itemFilter

under categoryID it should work because the seller item filter is the exception for needing a keyword or category.

**Comment by michabbb** [comment]
according to this url, itemFilter is a array !

https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/DTS/eBaySDK/Finding/Types/FindItemsAdvancedRequest.php#L28

**Comment by davidtsadler** [comment]
There's an existing [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/finding/05-find-items-advanced.php#L74) showing how to use itemFilter that can be adapted to search by seller.
