### ISSUE TITLE
SKU can be null in Trading\ReviseInventoryStatus

### ISSUE THREAD

**Issue by ChangePlaces** [davidtsadler/ebay-sdk-php#141]
At the moment, the `ReviseInventoryStatusRequestType` class doesn't like SKU being null, but if you're using itemid as per the default for listing tracking, and not working with an item with variations, it's perfectly legal to have a null sku.

**Comment by davidtsadler** [comment]
Do you have a code example?. I'm not sure what the issue is.

**Comment by ChangePlaces** [comment]
sorry, my fault. I'm assigning a null value, instead of checking if the value is null beforehand. Though, it feels weird that the property is allowed to be null, but setting null is not allowed.
