### ISSUE TITLE
Setting PrivateListing to true when ReviseFixedPriceItem

### ISSUE THREAD

**Issue by nocodelab** [davidtsadler/ebay-sdk-php#142]
Dear all,
I'm having an issue on changing PrivateListing value when i'm revising a FixedPriceItem.
Basically, instead of changing that value on the existing auction it creates a brand new auction.

Have you experienced something similar?

Thanks!

**Comment by michabbb** [comment]
what has this todo with this framework ? for me that sounds like a question you should ask at the ebay forum....

**Comment by nocodelab** [comment]
I've asked here because I'm not sure if it's a framework bug or an API limitation.

**Comment by michabbb** [comment]
in that case, you have to [debug](http://devbay.net/sdk/guides/guide/configuration.html#debug) the framework, and see, if a revise is really sent, if yes, the framework does what it should and i would say it's **not** a framework problem ;)

**Comment by davidtsadler** [comment]
Please use the [forum](https://forum.devbay.net/) for usage issues with the SDK.
