### ISSUE TITLE
`GetUserAlerts` call from eBay Client Alerts API

### ISSUE THREAD

**Issue by hughgrigg** [davidtsadler/ebay-sdk-php#144]
Does this library include the `GetUserAlerts` call from the eBay Client Alerts API?

http://developer.ebay.com/Devzone/client-alerts/docs/Concepts/ClientAlertsAPIGuide.html

The other calls leading up to that in docs are provided, but I can't find `GetUserAlerts`. I can have a look at making a PR to add it if it's not currently present.

**Comment by michabbb** [comment]
did you search for "GetUserAlerts" inside this github repo ?

**Comment by hughgrigg** [comment]
@michabbb, yes, I don't believe it's present anywhere in this repo.

**Comment by michabbb** [comment]
so, why are you asking ? ;-)))

**Comment by hughgrigg** [comment]
@michabbb I'm confirming that I'm not missing anything before I try to put a PR in for something that is already here, or should not be here :)

**Comment by davidtsadler** [comment]
The SDK doesn't support the Client Alerts service. I would need some time to look into it before I can add it.

**Comment by hughgrigg** [comment]
@davidtsadler thanks, I'll look at an alternative solution for now in that case.
