### ISSUE TITLE
Cannot run Inventory example

### ISSUE THREAD

**Issue by MikeWillis** [davidtsadler/ebay-sdk-php#145]
I'm sure this is entirely due to my own lack of understanding regarding composer and github, so I really appreciate any advice. I followed the installation instructions using composer, and I got the "Get the official eBay time" example working with no problem.

However, running the "02-create-or-replace-inventory-item.php" example (copy/paste of the code into my own test.php script) failed. The first attempt gave the following error:

PHP Fatal error: Class 'DTS\eBaySDK\Inventory\Services\InventoryService' not found in /path/test.php

I checked my server and found the "vendor/dts/ebay-sdk-php/src/DTS/eBaySDK" folder did not contain an "Inventory" subfolder (among several others). So I manually downloaded the master source from github, and uploaded via FTP, skipping any existing files. Now when I run my test.php script I get a different error:

PHP Fatal error: Call to undefined function DTS\eBaySDK\applyDebug() in /path/vendor/dts/ebay-sdk-php/src/DTS/eBaySDK/ConfigurationResolver.php on line 59

I checked out ConfigurationResolver.php and it makes no request for the applyDebug() function anywhere.

I imagine I missed a simple composer step or something..?

**Comment by michabbb** [comment]
Have you tried, next to composer, one of the other methods of installation explained here: http://devbay.net/sdk/guides/getting-started/installation.html?

**Comment by MikeWillis** [comment]
I had tried them yesterday but ran into some conflicts because I was running PHP 5.4 but they needed 5.5. Had my host install 5.5 separately today and did some testing:

The .phar method results in the same applyDebug() undefined function error
The .zip method seems to be working so far

So I'll stick with the .zip file for now
