### ISSUE TITLE
Trading GeteBayDetailsResponseType is missing PaymentOptionDetailsType

### ISSUE THREAD

**Issue by modstore** [davidtsadler/ebay-sdk-php#146]
I've attached the sample xml response.

I could make a pull request, but PaymentOptionDetailsType says not to edit the file, and I'm not sure how you generate them.

[GeteBayDetailsResponse.xml.zip](https://github.com/davidtsadler/ebay-sdk-php/files/1336961/GeteBayDetailsResponse.xml.zip)

**Comment by davidtsadler** [comment]
The field was deprecated and removed from the API. To get the information use GetCategoryFeatures instead, and pass in PaymentMethods as a FeatureID value in the request.
