### ISSUE TITLE
Guzzle error

### ISSUE THREAD

**Issue by angular013** [davidtsadler/ebay-sdk-php#147]
So i am getting a fatal error; my php is 32 bit in Xampp , windown 7 ( 64 bit ) ...i tested on my live server having 64 bit PHP but still the same error:

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://svcs.ebay.com/services/search/FindingService/v1` resulted in a `500 Internal Server Error` response: <?xml version='1.0' encoding='UTF-8'?><errorMessage xmlns="http://www.ebay.com/marketplace/search/v1/services"><error><e (truncated...) ' in E:\xampp\htdocs\new_job\ebay_search_items\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 E:\xampp\htdocs\new_job\ebay_search_items\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 E:\xampp\htdocs\new_job\ebay_search_items\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 E:\xampp\htdocs\new_job\ebay_search_items\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 E:\ in E:\xampp\htdocs\new_job\ebay_search_items\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113
`

here is my code:

`require 'vendor/autoload.php';

$config = require __DIR__ . '/configuration.php';

use \DTS\eBaySDK\Constants;
use \DTS\eBaySDK\Finding\Services;
use \DTS\eBaySDK\Finding\Types;
use \DTS\eBaySDK\Finding\Enums;

$service = new Services\FindingService([
	'apiVersion' => '1.13.0',
    'credentials' => $config['sandbox']['credentials'],
    'globalId'    => Constants\GlobalIds::US
]);

$request = new Types\FindItemsByKeywordsRequest();
/**
 * Assign the keywords.
 */
$request->keywords = 'Harry Potter';
/**
 * Send the request.
 */
$response = $service->findItemsByKeywords($request);
/**
 * Output the result of the search.
 */
if (isset($response->errorMessage)) {
    foreach ($response->errorMessage->error as $error) {
        printf(
            "%s: %s\n\n",
            $error->severity=== Enums\ErrorSeverity::C_ERROR ? 'Error' : 'Warning',
            $error->message
        );
    }
}
if ($response->ack !== 'Failure') {
    foreach ($response->searchResult->item as $item) {
        printf(
            "(%s) %s: %s %.2f\n",
            $item->itemId,
            $item->title,
            $item->sellingStatus->currentPrice->currencyId,
            $item->sellingStatus->currentPrice->value
        );
    }
}`

**Comment by angular013** [comment]
so i solved this issue , by changing from sandbox credentials to production credentials. i still dont know why the previous error came for my sandbox credentials

$service = new Services\FindingService([
	'apiVersion' => '1.13.0',
    'credentials' => $config['production']['credentials'],
    'globalId'    => Constants\GlobalIds::US
	
]);

**Comment by davidtsadler** [comment]
In the past I've seen the Finding API return a `500 Internal error` if you use the wrong credentials for the environment. By default the SDK will assume that you are connecting to the production server. If you are using your sandbox credentials you have to pass `true` to the [sandbox](http://devbay.net/sdk/guides/guide/configuration.html#sandbox) configuation option.

```php
$service = new Services\FindingService([
    'apiVersion'  => '1.13.0',
    'credentials' => $config['sandbox']['credentials'],
    'globalId'    => Constants\GlobalIds::US,
    'sandbox'     => true
]);
```
