### ISSUE TITLE
how to use Fulfillment getOrders?

### ISSUE THREAD

**Issue by hlb-schmidt** [davidtsadler/ebay-sdk-php#152]
heres what i tried:
```
$api = new \DTS\eBaySDK\Sdk([
	"sandbox" => true,
	"credentials" => [
		"appId" => $acnt["app_id"],
		"devId" => $acnt["dev_id"],
		"certId" => $acnt["cert_id"]
	]
]);

$wat = $api->createFulfillment();
$wat->getOrders();
```

but get an InvalidArgumentException `Missing required configuration options: authorization`

**Comment by michabbb** [comment]
take a look to the examples, i.e.

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php#L43

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/configuration.php.example

**Comment by davidtsadler** [comment]
The Fulfillment API uses the new RESTful token for authorization. You need to pass you oAuth token via the [authorization](http://devbay.net/sdk/guides/guide/configuration.html#authorization) configuration option.

More info on using the SDK with the RESTful services can be found in the [documentation](http://devbay.net/sdk/guides/guide/restful-services.html).

There are also several examples available.

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/inventory/01-get-inventory-item.php
https://github.com/davidtsadler/ebay-sdk-examples/blob/master/browse/01-search-for-items.php
https://github.com/davidtsadler/ebay-sdk-examples/blob/master/feed/01-get-item-feed.php

**Comment by hlb-schmidt** [comment]
thank you for the tip about (soap) trading api. that works without user intervention (as i need to use this in a cronjob) and a single seller token that only has to be created once a year. versus rest/fulfillment api where it seems we need manual user grants and short lasting tokens...
