### ISSUE TITLE
cURL error 35

### ISSUE THREAD

**Issue by djeraseit** [davidtsadler/ebay-sdk-php#156]
A long running process dies with the following error:

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 35:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in ********/includes/ebay-sdk-examples/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:18

**Comment by michabbb** [comment]
@djeraseit what does this error has todo with this SDK ?????? i suggest [this](http://bfy.tw/GZ1P).

**Comment by djeraseit** [comment]
@michabbb since you're so smart, do you know how to override the curl handler in the sdk to increase number of simultaneous thread requests?

**Comment by michabbb** [comment]
I guess Google is smarter than all of us , beside that, I don't understand your request because I don't see any simultaneously threads here. 
Again, I guess your questions about curl should be placed at stackoverflow.com.
