### ISSUE TITLE
Missing publishOfferByInventoryItemGroup

### ISSUE THREAD

**Issue by Tam** [davidtsadler/ebay-sdk-php#157]
Would it be possible to add [`publishOfferByInventoryItemGroup`](https://developer.ebay.com/api-docs/sell/inventory/resources/offer/methods/publishOfferByInventoryItemGroup) to the Inventory service?

**Comment by davidtsadler** [comment]
The latest 14.0.0 release should now support [publishOfferByInventoryItemGroup](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Inventory/Services/InventoryService.php#L825).
