### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by frafra85** [davidtsadler/ebay-sdk-php#16]
When i try to install with composer , i obtain this message:

```
php composer.phar require dts/ebay-sdk-php
Using version ^0.5.0 for dts/ebay-sdk-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dts/ebay-sdk-php No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by davidtsadler** [comment]
I can't recreate this when starting a new project with an empty composer.json file. Can you post the contents of your composer.json file as it is before installing the SDK.

**Comment by davidtsadler** [comment]
Closing this for now. Please add more information if this issue is still occurring for you.

**Comment by 1Mpuls3** [comment]
Hi, same problem here using Composer (version 1.3.1) 

`
{
    "name": "dts/ebay-sdk-php",
    "description": "An eBay SDK for PHP. Use the eBay API in your PHP projects.",
    "keywords": ["ebay", "api", "sdk"],
    "homepage": "http://devbay.net/",
    "type": "library",
    "license": "(Apache-2.0 and MIT)",
    "authors": [
        {
            "name": "David T. Sadler",
            "email": "davidtsadler@googlemail.com",
            "homepage": "http://davidtsadler.com"
        }
    ],
    "support": {
        "issues": "https://github.com/davidtsadler/ebay-sdk-php/issues"
    },
    "require": {
        "php": ">=5.5",
        "guzzlehttp/guzzle": "~6.0",
        "guzzlehttp/psr7": "~1.0",
        "guzzlehttp/promises": "^1.1"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "squizlabs/php_codesniffer": "2.*"
    },
    "autoload": {
        "psr-4": {
            "DTS\\eBaySDK\\": "src/"
        },
        "files": ["src/functions.php"]
    },
    "autoload-dev": {
        "psr-4": {
            "DTS\\eBaySDK\\Test\\": "test/"
        },
        "classmap": ["build/"]
    }
}
`

**Comment by davidtsadler** [comment]
What's the contents of your project's composer.json file?

**Comment by 1Mpuls3** [comment]
Sorry my bad, using npm all day made me forget how you use composer. I was starting composer in the zip folder instead of creating my own composer.json file, uh. It's monday! 

It's now all solved. Thanks for the reactivity though!

**Comment by davidtsadler** [comment]
No problems :)
