### ISSUE TITLE
Revise item variation price works as manually entered number but not as variable

### ISSUE THREAD

**Issue by G0dsp33d888** [davidtsadler/ebay-sdk-php#162]
First off, thank you for making this awesome php version of the eBay SDK! I really appreciate it.

I have gotten everything to work except for this; I get a price variable ($price) from my database and try to insert this variable. I get the error "Please enter a valid price for your item (e.g. US $0.99).". When I manually replace the $price variable with a random double number, it works. I need to dynamically update the price without having to put the price manually for every variation, as there are a few.

Here is a sample of my code:

```
settype($price, "double");
$item->Variations->Variation[] = new Types\VariationType([
    'SKU' => $id,
    'Quantity' => $qty,
    'StartPrice' => new Types\AmountType(['value' => $price]),
    'VariationSpecifics' => [new Types\NameValueListArrayType([
        'NameValueList' => [
            new Types\NameValueListType(['Name' => 'Packaging', 'Value' => [$packaging]]),
            new Types\NameValueListType(['Name' => 'Size', 'Value' => [$size]])
        ]
    ])]
]);
```

**Comment by michabbb** [comment]
- maybe a `.` `,` (decimal divider) problem ?
- what is your output of your `var_dump($price)` ?
- what is the full original ebay error you get ?

**Comment by G0dsp33d888** [comment]
Hey, thanks for your reply.

- I am unsure of what a decimal divider problem is, but the page receives it from the database in a format like 5.22
- Output is "float(20.88)"
- "Error: Price is not valid. Please enter a valid price for your item (e.g. US $0.99)."

**Comment by michabbb** [comment]
an "original" ebay error has a error-number...  there are some countries where the minimum price of an item is (here in germany for example) 1 EUR. so a price with 0.99 EUR is not allowed, take care that this does not apply to your problem ;)

**Comment by G0dsp33d888** [comment]
Whoops! The error code is 73.
The minimum price in the US is $0.99, so that shouldn't be the problem.

The $price variable would be set to 20.88 and it would throw the error, but when the variable is replaced by the number 20.88 it would revise correctly. It's really stumping me on how to solve this..

**Comment by michabbb** [comment]
you should dump the xml the SDK is sending to ebay, than you should verify the request/result in the [ebay developer tools](https://developer.ebay.com/DevZone/build-test/test-tool/?index=0)...

**Comment by G0dsp33d888** [comment]
I finally figured it out!! The problem is I'm a bit dumb :)
My page was iterating through an array and one of my prices weren't entered, making the price 0. Thank you for your help @michabbb!

**Comment by michabbb** [comment]
@G0dsp33d888 glad to help, most people forget the good old `print_r` 😋
