### ISSUE TITLE
DeletedField errors in RelistFixedPriceItem call

### ISSUE THREAD

**Issue by ChangePlaces** [davidtsadler/ebay-sdk-php#165]
I'm trying to delete the value of the location field of an item. In this call I'm sending a `DeletedField` of `Item.Location` to do this, but receive the error;
`
[{"ShortMessage":"DeletedField tag is invalid.","LongMessage":"DeletedField tag name \"item.location\" is invalid. You must use a valid path in the form \"item.tag1[.tag2]\".","ErrorCode":"10201","SeverityCode":"Error","ErrorParameters":[{"Value":"item.location","ParamID":"0"}],"ErrorClassification":"RequestError"}]`

Is it correct that the value is converted to lowercase? I've tried other values to delete the field including `Location`, `location`, `item.location` all which give the same error.

**Comment by michabbb** [comment]
you should first try the [ebay api test tool](https://developer.ebay.com/DevZone/build-test/test-tool/?index=0) at the developer section to be 100% sure, that you are able to delete this special field. if that is working, you can compare the xml of the SDK to the XML you created in the tool to finde the difference.

**Comment by ChangePlaces** [comment]
@michabbb Thank you, trying it now, but still getting the same error, which appears to go against the docs! I think I'm sending the deletedfield name correctly, so will try it a bit more to be sure before I close this issue.

**Comment by michabbb** [comment]
@ChangePlaces ebay docs are not always correct, i know ;-( but either you are not allowed to delete that field or your xml (you are building in the tool by hand) is wrong. in cases like this, my suggestion is: first create a working xml in that tool, so you can be 100% sure, it has nothing todo with the SDK. btw you get to know the ebay api better, because many things are hidden in a SDK ;) and if nothing is working, there is still the [ebay premium support](https://developer.ebay.com/my/support/tickets), they usually do a great job.

**Comment by ChangePlaces** [comment]
@michabbb I tried without deletefield (assuming I cannot just delete the field at this point) and just passed an empty string, and it still keeps the old value. I've tried an empty string with a space, but still the old value remains! It really is infuriating how sloppy the docs are now!

And unfortunately, $75 for one hour of premium support is a little step when you're just working on a project just for yourself!

**Comment by michabbb** [comment]
@ChangePlaces don´t forget: investing 5 hours of debugging our time is (i´m sure) more expansive than 75$ for premium support. and if it turns out, it´s a bug, you won´t get charged. anyway, it´s up to you.
sorry if i cannot help any further.

**Comment by davidtsadler** [comment]
The error may be an indication that you are not allowed to delete that field. I know from experience that eBay's API messages don't always explain what is wrong.
