### ISSUE TITLE
split project parts into smaller pieces (incl. composer)

### ISSUE THREAD

**Issue by ole1986** [davidtsadler/ebay-sdk-php#166]
Are there any plans to split the project into sub projects?
Eg. only trader libraries?

**Comment by michabbb** [comment]
that would be surprising, because in the old days every api was a individual project and @davidtsadler combined everything together, so i guess he won´t undo this

**Comment by davidtsadler** [comment]
When I first developed the SDK it was split into 9 different repositories, one for each API that was supported. It was too much hassle maintaining them to be honest, and that was a few years before the RESTfull APIs came out. For the foreseeable future it will be kept as one repository.

**Comment by Aerendir** [comment]
And kept it into one single repository is also the best way to manage the packages.

Something that could be done, but I don't think it is required, is to create sub-tree splits of the various parts.

But, to be honest, as said, I don't think it is a requirement, as this is server side code and so we don't need to take to much in consideration the size of the package...
