### ISSUE TITLE
Guzzle 3 is deprecated

### ISSUE THREAD

**Issue by debojitkakoti** [davidtsadler/ebay-sdk-php#17]
Hi I got this error when installed the ebay-sdk-php. Can I ignore it?
Error:
`guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
`
How to reproduce:
`composer require dts/ebay-sdk-php`

composer version: 1.0-dev
php versionn: PHP 5.5.9

**Comment by davidtsadler** [comment]
Hi, 

For the moment it is OK to ignore this message as Guzzle 3 will still be installed. It's just a warning to say that the developers of Guzzle 3 are no longer supporting it and that people should use Guzzle 6 instead. I'm updating the SDK so that it will use Guzzle 6 in future.
