### ISSUE TITLE
[Request] Please add an example in the Trading on how to list using "Collect in person" only

### ISSUE THREAD

**Issue by ChangePlaces** [davidtsadler/ebay-sdk-php#170]
I can't figure out how to list or revise an item using the API to set it as 'collect in person' only. I have got 'courier' working, but not this. When I check a listing that is already listed as collect in person only, it doesn't appear to have any shipping service options set, but when I try to revise / add an item doing this, the API gives an error that at least one service is required.

**Comment by pjw345** [comment]
If it helps, we setup business policies (My Account -> Business policies) for Payment, Returns and Postage and then only assign the business policies to the listings accordingly instead of setting shipping methods on each listing

**Comment by ChangePlaces** [comment]
Thanks. I'm trying to write an interface as complete as I can for my needs, and unfortunately this is a blocker for me. That's an interesting plan B though. There is a `SellerShippingProfile` (or similar) set to "Collection in person when I look at the data returned via the API but I'm not sure if that's dynamically created on ebay's part.

**Comment by michabbb** [comment]
@ChangePlaces setup everything with the ebay frontend, then do a GetItem and debug the values

**Comment by ChangePlaces** [comment]
@michabbb I did! There appeared to be nothing set as I mentioned in the first post!

**Comment by michabbb** [comment]
@ChangePlaces so you used `UK_CollectInPersonInternational` according to [this list](https://developer.ebay.com/devzone/xml/docs/reference/ebay/types/ShippingServiceCodeType.html) ?
