### ISSUE TITLE
Missing required configuration options:

### ISSUE THREAD

**Issue by dustinmoore** [davidtsadler/ebay-sdk-php#172]
Running into the error (that's all I get) when trying to use the following:

		$this->tradingService = new Services\TradingService(array(
			'apiVersion' => '1039',
			'authToken' => $this->settings['authToken'],
			'credentials' => $this->credentials,
			'siteId'      => $data['siteId'],
			'sandbox'     => true
		));

Initially I didn't have authToken or apiVersion in there. Not sure what I might be missing here.

**Comment by michabbb** [comment]
because nobody knows what `$this->credentials` in your code is, i would suggest to
read the [docu](http://devbay.net/sdk/guides/guide/configuration.html) or see the [examples](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/01-get-ebay-official-time.php#L42)

**Comment by dustinmoore** [comment]
$this->credentials refers to this:

$this->credentials = new Credentials($this->config['appName'], $this->config['certName'], $this->config['devName']);

For some reason it just seems to be an issue with the TradingService. I've been able to for instance get a user token with Servers\OAuthService and use InventoryService. I've been combing thru the docs and examples for the last 2 days trying to solve the issue.

**Comment by michabbb** [comment]
i am not using the oauth, i always work with a user-token so i cannot tell much about that. but i am wondering why u are using an Credentials object, because the examples (don´t know if they are 100% up2date) use a simple array:

```php

$config = require __DIR__.'/../configuration.php';

$service = new Services\TradingService([
    'credentials' => $config['production']['credentials'],
    'siteId'      => Constants\SiteIds::US
]);
```
the [config](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/configuration.php.example) is just an array

**Comment by dustinmoore** [comment]
That method was in one of the examples in the documentation and so that's what I ended up using. As a test just now to see if for some reason that was an issue. I tried using the method you pasted and it's the same problem. The error is kind of frustrating because it doesn't say anything outside of "Missing required configuration options:" 

But I have no idea what could be missing.

**Comment by michabbb** [comment]
have you checked the value of your `$data['siteId']` ??

**Comment by michabbb** [comment]
i would suggest [to debug the function](https://github.com/davidtsadler/ebay-sdk-php/blob/3584f5fa985386b392b178d1b4212b6770dbc547/src/ConfigurationResolver.php#L41) that throws this error to find out, what exactly is missing

**Comment by dustinmoore** [comment]
Wow, that was it $data['siteId']. 

For some reason the value wasn't coming across. Thanks for responding this whole time. Much appreciated.

**Comment by michabbb** [comment]
@dustinmoore what about closing this issue ? ;)

**Comment by dustinmoore** [comment]
@michabbb Sorry about that. Thanks for all your help again!
