### ISSUE TITLE
$item->Description returns null

### ISSUE THREAD

**Issue by jrm2107** [davidtsadler/ebay-sdk-php#173]
In your example [11-get-my-ebay-selling.php](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php):

adding **$item->Description** does not work

    if ($response->Ack !== 'Failure' && isset($response->ActiveList)) {
        foreach ($response->ActiveList->ItemArray->Item as $item) {
            printf(
                "(%s) %s: %s %s %.2f\n",
                $item->ItemID,
                $item->Title,
                $item->Description,
                $item->SellingStatus->CurrentPrice->currencyID,
                $item->SellingStatus->CurrentPrice->value
            );
        }
    }

**Comment by michabbb** [comment]
If you want to use this SDK, you should really know how [the ebay api](http://developer.ebay.com/devzone/xml/docs/reference/ebay/getmyebayselling.html#Request.DetailLevel) is working

**Comment by jrm2107** [comment]
indulge me, professor.
