### ISSUE TITLE
wissing fields in RateTableDetailsType

### ISSUE THREAD

**Issue by geromueller** [davidtsadler/ebay-sdk-php#179]
Hi!

RateTableDetailsType is missing DomesticRateTableId, InternationalRateTable and InternationalRateTableId

http://developer.ebay.com/devzone/xml/docs/Reference/eBay/types/RateTableDetailsType.html

**Comment by davidtsadler** [comment]
I think those fields are already in the SDK https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Trading/Types/RateTableDetailsType.php#L15
