### ISSUE TITLE
For ShoppingService globalId does not change anything

### ISSUE THREAD

**Issue by Dmitri10** [davidtsadler/ebay-sdk-php#182]
I'm using this code with full path to avoid any misunderstanding from your side:
```
$service = new \DTS\eBaySDK\Shopping\Services\ShoppingService([
    'credentials' => $config['production']['credentials'],
    'globalId'    => \DTS\eBaySDK\Constants\GlobalIds::DE,
]);

$request = new \DTS\eBaySDK\Shopping\Types\GetSingleItemRequestType();
$request->ItemID = '291781175293';
$request->IncludeSelector = 'ItemSpecifics,Variations,Compatibility,Details';
$response = $service->getSingleItem($request);
dd($response);
```
https://www.ebay.de/itm/smt/291781175293
https://www.ebay.com/itm/smt/291781175293
so even if I use GlobalIds::US results are the same and look like this:
![2018-04-03_12-16-58](https://user-images.githubusercontent.com/2151287/38241407-c94d51aa-373a-11e8-930a-3278696116ec.png)

Did I miss something?

**Comment by michabbb** [comment]
Hi there, i guess you really miss something here 😁
The SiteId is not binded to your call "GetSingleItem", it's binded to the item itself. Whenever you create an item at ebay, you usually provide the Country/SiteId, so it's fixed a part of the item itself, and has nothing to do with your calls, getting Infos about the item. Try to see the SiteId the same like title, price, description, and so on...

**Comment by michabbb** [comment]
Hopefully I got your question, because you speak about globalid and I of SiteId 😏

**Comment by Dmitri10** [comment]
@michabbb Thank you for a quick response.
But product is shown on both sites: 
https://www.ebay.de/itm/smt/291781175293
https://www.ebay.com/itm/smt/291781175293
And ShoppingService has a param globalId so I thought I can use it to extract info by ID from site I need.

You want to say there isn't way to extract from another site, right?

**Comment by michabbb** [comment]
@Dmitri10 i guess i don´t really understand your "extract from another site" phrase. the ebay api is global, you can create listing on different siteids, but that is unimportant when fetching item infos. please be more specific what you expact from the result.

**Comment by Dmitri10** [comment]
@michabbb Excuse me for bad explanation please.
I want to get info by item id with price for single eBay site.
And I showed you that I can't set specific country to extract price in EUR/GBP whatever.
itemID is unique for all sites - that's clear.
But ViewItemURLForNaturalSearch and one of (ConvertedCurrentPrice or CurrentPrice) should contain data from Site I requested.

During my investigation I found that GetSingleItemRequestType  doesn't contain any mentions about site I interest.
As I said before I used https://www.ebay.com/itm/smt/291781175293 to test and there is response from API in my first message.

If I add here
https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Services/BaseService.php#L164
$headers['X-EBAY-API-SITE-ID'] = 3;
to get from Great Britain then I receive info I need:
![2018-04-03_16-50-43](https://user-images.githubusercontent.com/2151287/38253448-554fdb54-375f-11e8-9d27-c12ac81df022.png)

That thing I need. You see?

**Comment by michabbb** [comment]
@Dmitri10 okay, so you fetch

this item: https://www.ebay.com/itm/smt/291781175293

and you use 

`'globalId'    => \DTS\eBaySDK\Constants\GlobalIds::DE,`

and you expact, that `ViewItemURLForNaturalSearch` and `ConvertedCurrentPrice` should be "german".

but it isn´t, correct ?

**Comment by Dmitri10** [comment]
Agree, this library is awesome!
But I can confirm the bug:
![2018-04-03_17-22-20](https://user-images.githubusercontent.com/2151287/38255136-b10495a8-3763-11e8-8545-63e15a17c32d.png)
![2018-04-03_17-23-41](https://user-images.githubusercontent.com/2151287/38255195-d860c0ea-3763-11e8-8c29-368979914376.png)
---------------------------
As I said I need parameter X-EBAY-API-SITE-ID

That's a dump from request 
`dd($url, $headers, $body);`
placed here https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Services/BaseService.php#L164

![2018-04-03_17-26-35](https://user-images.githubusercontent.com/2151287/38255335-42791d2e-3764-11e8-88ef-72b8d4aba7f4.png)

It's missing :(

**Comment by michabbb** [comment]
@Dmitri10 thanks a lot for debuggung this! now it´s 100% clear and i am pretty sure @davidtsadler will fix this soon, as it looks to me that this is not a big deal (hopefully) ;)

**Comment by michabbb** [comment]
@Dmitri10 thanks for debugging this. do you have noticed, that in your first posting you speak about "globalid" and in your last debuggings you speak about "SITE-ID" ?

when i look to the code:

https://github.com/davidtsadler/ebay-sdk-php/blob/3584f5fa985386b392b178d1b4212b6770dbc547/src/Shopping/Services/ShoppingBaseService.php#L106

i see that you should be able to set the `siteId` - did you try your first call with `siteId` instead of `globalid` ??

**Comment by michabbb** [comment]
@Dmitri10 because, when you search the code for `globalId` you won´t find anything that has todo with the shopping-api, maybe you have seen this at the finding-api:

https://github.com/davidtsadler/ebay-sdk-php/search?p=1&q=globalId&type=&utf8=%E2%9C%93

**Comment by Dmitri10** [comment]
@michabbb I am so sorry, I really couldn't find that in docs. And didn't find that in ShoppingService. 
Yes, there is another constants file for sites and I used parameter you included and it works!
```
$service = new \DTS\eBaySDK\Shopping\Services\ShoppingService([
    'credentials' => $config['production']['credentials'],
    'siteId'    => \DTS\eBaySDK\Constants\SiteIds::GB,
]);
```
Thank you!

**Comment by michabbb** [comment]
@Dmitri10 as usual, in most cases: it´s the little things that make our life more complicated 😄
