### ISSUE TITLE
Is it possible to cancel an order with this api ? 

### ISSUE THREAD

**Issue by doralb** [davidtsadler/ebay-sdk-php#185]
```
    public function cancelRequest($token, $order_id , $siteId = 0) {


        $request_url = 'https://api.ebay.com/post-order/v2/cancellation';
        $payload = json_encode(array('legacyOrderId' => $order_id));


        $headers = array(
            'Authorization:' => $token,
            'Content-Type' => 'application/json',
            'X-EBAY-C-MARKETPLACE-ID' => 'EBAY_US',
            'Accept' => 'application/json',
            'X-EBAY-API-DEV-NAME' => $this->appData['EBAY_DEVNAME'],
            'X-EBAY-API-APP-NAME' => $this->appData['EBAY_APPNAME'],
            'X-EBAY-API-CERT-NAME' => $this->appData['EBAY_CERTNAME'],
            'X-EBAY-API-SITEID' => '0',
        );

        $ch = curl_init($request_url);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_HEADER, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        return $response;
    }
```

Since I didn't found a solution in this API (maybe is there but I cant see it :D ) ,  I built this function to for the cancel request by following the ebay developer API instrutcions. Doesnt works :( keeps redirecting to page not responding. Any solution or Idea ?

**Comment by michabbb** [comment]
hi, these kind of question belong to the [mailing-list](https://groups.google.com/group/ebay-sdk-php).
maybe the call [AddDispute](https://developer.ebay.com/devzone/xml/docs/reference/ebay/AddDispute.html) is something you are looking for.

**Comment by doralb** [comment]
@michabbb  you are right. but I am kinda desperate. :D To confusing this kind of ebay API

**Comment by michabbb** [comment]
@doralb then you should start with a SDK, you should start working with the API itself, because otherwise you always will get stuck somewhere ;) i really recommend the [ebay api test tool](synology_nas_ds218_plus_8TB_2018-04-08), work with that, test your stuff and if you understand the API itself and its calls, start writing your code, its much easier, believe me ;)
