### ISSUE TITLE
TradingAPI Issue with OAuth - Getting 931 Invalid Token

### ISSUE THREAD

**Issue by erikbens** [davidtsadler/ebay-sdk-php#186]
Hey everyone,
I'm trying to get the sdk up and running for the trading API of eBay. First of all I have to say: Great work!  It's easy to use and up to date - thanks already for that! 

I already used the API (Account API) successfully to get the policies into my application using OAuth with the steps
1) Get the AUTH Code from eBay with the redirect / accept pages
2) Get a user access token based on the AUTH Code via the SDK and use the token to get the policies
That works perfectly fine for me.

However I'm having issues now to get the category tree from eBay. I'm trying it the same way - getting the Auth Code, retrieving the user access token and then call the service using this token in the request. I also added my credentials (from production in https://developer.ebay.com/my/keys) to the service itself. 

I'm ending up getting the token, but receiving a errorcode 931 for Auth Token invalid. As you can see i print the token to the page -> if I use this token in the api test tool (https://developer.ebay.com/DevZone/build-test/test-tool/default.aspx?index=0&env=production&api=trading&call=GetCategories&variation=xml) with OAuth I actually get the results without any errors. What am I doing wrong?

Here's my code:
```php
$service = new OAuthService([
    'credentials' => EbayConfig::getEbayCredentials(), // appId, certId, devId from https://developer.ebay.com/my/keys
    'ruName' => EbayConfig::getEbayRuName() // from https://developer.ebay.com/my/auth/?env=production
]);

$request = new GetUserTokenRestRequest();
$request->code = $_SESSION['ebayAuthCode'];

/**
 * Send the request.
 */
$response = $service->getUserToken($request);

if ($response->getStatusCode() === 200) {
    $_SESSION['ebayOAuthToken'] = $response->access_token;
    $service = new TradingService([
        'credentials' => EbayConfig::getEbayCredentials(), // same credentials as above (is that correct?)
        'siteId' => SiteIds::DE,

    ]);

    $request = new GetCategoriesRequestType();
    $request->RequesterCredentials = new CustomSecurityHeaderType();
    $request->RequesterCredentials->eBayAuthToken = $_SESSION['ebayOAuthToken'];
    $request->DetailLevel = [DetailLevelCodeType::C_RETURN_ALL];
    $request->ViewAllNodes = true;
    $request->OutputSelector = [
        'CategoryArray.Category.CategoryID',
        'CategoryArray.Category.CategoryParentID',
        'CategoryArray.Category.CategoryLevel',
        'CategoryArray.Category.CategoryName',
        'CategoryArray.Category.LeafCategory',
        'CategoryArray.Category.Expired'
    ];

    $response = $service->getCategories($request);

    printf("\nStatus: %s%s", $response->Ack, '<br>');
    if (isset($response->Errors)) {
        foreach ($response->Errors as $error) {
            printf(
                "%s: %s\n%s\n\n",
                $error->ErrorCode,
                $error->ShortMessage,
                $error->LongMessage
            );
        }
        print("<br> Used Token=" . $_SESSION['ebayOAuthToken']);
    }
    if ($response->Ack === AckCodeType::C_SUCCESS) {
        $categories = $response->CategoryArray;

        foreach ($categories as $category) {
           // do stuff with the category
        }
    }
} else {
    printf(
        "%s: %s",
        $response->error,
        $response->error_description
    );
}
```

**Comment by michabbb** [comment]
as you pointed out, the api test tool works without any errors, print the raw xml of the SDKs request and compare it with your own (u used with the test tool) - i guess there has to be a difference somewhere....

**Comment by erikbens** [comment]
Well, that was kinda helpful. I'm a bit rusty. The issue is that the example given in https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/02-get-category-hierarchy.php does not work for me.

If I change it so that the TradingService itself gets the Token for the header information like
```php
$service = new TradingService([
        'credentials' => EbayConfig::getEbayCredentials(),
        'siteId' => SiteIds::DE,
        'authorization' => $_SESSION['ebayOAuthToken']
    ]);
```
and remove the `$request->RequesterCredentials = new CustomSecurityHeaderType()` entirely, it works for me.

**Comment by michabbb** [comment]
i don´t wotk with oauth, so i cannot follow you in detail, hopefully i was able to help (a bit)... ;)

**Comment by NerdGuruDevelopers** [comment]
So I just ran into this exact issue and erikben's solution works. Perhaps it should be added to the documentation (if this is the right way to do it) or if not then we should probably get a "why not" from the creator.
