### ISSUE TITLE
SearchReturns

### ISSUE THREAD

**Issue by detit** [davidtsadler/ebay-sdk-php#187]
Hi,

trying to get all open returns using SearchReturns. Getting the error 'Unknown property flags'. Spend the whole day trying to fix it and tried literally everything.

```
$service = new Services\PostOrderService([
   'credentials' => $config['production']['credentials'],
   'authToken'   => $config['production']['authToken'],
   'sandbox'     => false,
   'siteId'      => $siteId
]);
$request = new Types\SearchReturnsRestRequest();
$service->SearchReturns($request);
```

Also, not sure whether parameter 'states' is required, this is not clear from documentation. However, setting 'states' to 'INITIAL' allows the call to go through, though resulting in 0 total results (which is not true).
Setting 'states' to CLOSED produces the same Unknown property flags error.
`$request->states = 'CLOSED';`

**Comment by michabbb** [comment]
Looks like this call is a simple GET request, so you can call the simple get url based on the ebay docu with postman (for example) and than compare the url, you created on your own, with the one, this SDK is creating and compare both to find the differences

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔
