### ISSUE TITLE
DetailLevel String or Repeatable?

### ISSUE THREAD

**Issue by JoelSParker** [davidtsadler/ebay-sdk-php#189]
When I set $getItem->DetailLevel to a string I get:

Fatal error: Uncaught DTS\eBaySDK\Exceptions\InvalidPropertyTypeException: Invalid property type provided for DetailLevel. Expected DTS\eBaySDK\Types\RepeatableType but got string in vendor\dts\ebay-sdk-php\src\Types\BaseType.php:383.

When I set it to a RepeatableType I get:

Fatal error: Uncaught DTS\eBaySDK\Exceptions\InvalidPropertyTypeException: Invalid property type provided for DetailLevel. Expected string but got DTS\eBaySDK\Types\RepeatableType in vendor\dts\ebay-sdk-php\src\Types\BaseType.php:497

Please help!

**Comment by michabbb** [comment]
What about showing some code or shall we guess what you are really doing here? 😏

**Comment by JoelSParker** [comment]
Well that would make life too easy. You are just supposed to assume I am doing everything correctly 😜

`$requestGetItem->RequesterCredentials = new Types\CustomSecurityHeaderType();
$requestGetItem->RequesterCredentials->eBayAuthToken = $credentials['production']['authToken'];

$requestGetItem->IncludeItemCompatibilityList = true;
$requestGetItem->IncludeItemSpecifics = true;
$requestGetItem->DetailLevel = Enums\DetailLevelCodeType::C_RETURN_ALL;
$requestGetItem->ItemID = $item->ItemID;

$responseGetItem = $service->getItem($requestGetItem);`

**Comment by michabbb** [comment]
what happens if you try with `$requestGetItem->DetailLevel = ['ReturnAll'];` ?

**Comment by JoelSParker** [comment]
You are a genius! Should all repeatables be passed as an array?

Thank you for your help!
