### ISSUE TITLE
MPN, Brand and EAN Issue

### ISSUE THREAD

**Issue by korcstar** [davidtsadler/ebay-sdk-php#19]
I was trying to post fixed item on Ebay

My code is bellow

$request = new Types\AddFixedPriceItemRequestType();
$item = new Types\ItemType();
$item->ProductListingDetails = new Types\ProductListingDetailsType();
$item->ProductListingDetails->BrandMPN = new Types\BrandMPNType();
$item->ProductListingDetails->BrandMPN->Brand = "Dell";
$item->ProductListingDetails->BrandMPN->MPN = "MyProductMPN";
$item->ProductListingDetails->EAN = "ProductEAN";
 .....
$request->Item = $item;
$this->service->addFixedPriceItem($request);

When item was posted on ebay, I can't see MPN, Brand and EAN
What is my wrong
Please help me

**Comment by korcstar** [comment]
I found solution for this

$item->ItemSpecifics = new Types\NameValueListArrayType();
        
        $specific_brand = new Types\NameValueListType();
        $specific_brand->Name = 'Brand';
        $specific_brand->Value[] = $brand;
        
        $item->ItemSpecifics->NameValueList[] = $specific_brand;

**Comment by mrcmnk** [comment]
Thank you so much for sharing your solution. I was loosing my mind over this. 👍

**Comment by michabbb** [comment]
i have seen tons of these mistakes: if all that people would use a good php IDE like phpstorm, things like that wouldn't happen, because a good IDE offers you type autocompletion and let you know when an array is used a string 🙈

**Comment by mrcmnk** [comment]
Hey Michael,
will take a look into PhpStorm. Thanks. ;)
Can you correct our mistake above? Not that good of a programmer, I am afraid (doing more Frontent dev).

**Comment by michabbb** [comment]
@mrcmnk i thought your problems are solved....?
