### ISSUE TITLE
Problems with ebay upload site hosted pictures (uploadSiteHostedPictures)

### ISSUE THREAD

**Issue by Rykono** [davidtsadler/ebay-sdk-php#190]
XML error 5 on uploadSiteHostedPictures help pleassssssssseeee. What do i do???!~?!?!?

is this better?

**Comment by michabbb** [comment]
before going into this: do you think it helps posting any binary data here ? ;)

**Comment by michabbb** [comment]
next: be sure u use latest version of this SDK to avoid [last changes](https://github.com/davidtsadler/ebay-sdk-php/pull/171) here

**Comment by Rykono** [comment]
I apologize i only posted the binary data because of the random XML tag in the middle of the data. I have only started using the sdk yesterday. before using the SDK I was using this class.

namespace App\Classes\ListClasses;

use \DomDocument;
use \SimpleXMLElement;

class UploadSiteHostedPictures
{
    public $sandbox = false;

    public $devID;
    public $appID;
    public $certID;
    public $serverUrl;
    public $compatabilityLevel;

    public $accountName;
    public $pictures;

    public $files;

    public $apisite = "Trading";




    public function __construct($files)
    {
        $this->accountName = $files['accountName'];
        $this->files = $files;


        include("keys.php");
        $sessionkeys = getKeys($files['accountName'], $this->sandbox, $this->apisite);
        $this->devID = $sessionkeys['0'];
        $this->appID = $sessionkeys['1'];
        $this->certID = $sessionkeys['2'];
        $this->serverUrl =  $sessionkeys['3'];
        $this->compatabilityLevel = $sessionkeys['4'];
    }





    public function upload()
    {
        $return_array = array();



        foreach ($this->files['pictures'] as $key => $value) {
            if ($this->sandbox) {
                $token = trim(file_get_contents('../.ebay_sdk/blah.sandbox.token'));
            } else {
                $token = trim(file_get_contents('../.ebay_sdk/blah.token'));
            }


            $siteID = 0;
            $verb =	"UploadSiteHostedPictures";

            ///Build the request XML request which is first part of multi-part POST
            $xmlReq = '<?xml version="1.0" encoding="utf-8"?>' . "\n";
            $xmlReq .= '<' . $verb . 'Request xmlns="urn:ebay:apis:eBLBaseComponents">' . "\n";
            $xmlReq .= "<Version>991</Version>\n";
            $xmlReq .= "<PictureName>my_pic</PictureName>\n";
            $xmlReq .= "<PictureSet>Supersize</PictureSet>\n";
            $xmlReq .= "<RequesterCredentials><eBayAuthToken>$token</eBayAuthToken></RequesterCredentials>\n";
            $xmlReq .= '</' . $verb . 'Request>';

            $boundary = "MIME_boundary";
            $CRLF = "\r\n";

            // The complete POST consists of an XML request plus the binary image separated by boundaries
            $firstPart   = '';
            $firstPart  .= "--" . $boundary . $CRLF;
            $firstPart  .= 'Content-Disposition: form-data; name="XML Payload"' . $CRLF;
            $firstPart  .= 'Content-Type: text/xml;charset=utf-8' . $CRLF . $CRLF;
            $firstPart  .= $xmlReq;
            $firstPart  .= $CRLF;

            $secondPart='';
            $secondPart .= "--" . $boundary . $CRLF;
            $secondPart .= 'Content-Disposition: form-data; name="dummy"; filename="dummy"' . $CRLF;
            $secondPart .= "Content-Transfer-Encoding: binary" . $CRLF;
            $secondPart .= "Content-Type: application/octet-stream" . $CRLF . $CRLF;
            $secondPart .= $value['data'];
            $secondPart .= $CRLF;
            $secondPart .= "--" . $boundary . "--" . $CRLF;

            $fullPost = $firstPart . $secondPart;


            // Create a new eBay session (defined below)
            $session = new eBaySession($token, $this->devID, $this->appID, $this->certID, $this->sandbox, $this->compatabilityLevel, $siteID, $verb, $boundary);

            $responseXml = $session->sendHttpRequest($fullPost);

            $responseDoc = new DomDocument();
            $responseDoc->loadXML($responseXml);




            if (stristr($responseXml, 'HTTP 404') || $responseXml == '') {
                array_push($return_array, array( 'Errors' => 'eBay API could not be reached.'));
            }


            $errors = $responseDoc->getElementsByTagName('Ack');

            $xml = simplexml_load_string($responseXml, null, LIBXML_NOCDATA);
            $json = json_encode($xml);
            $array = json_decode($json, true);

            //if there are error nodes
            if ($errors === "Failure" || in_array('Failure', $array)) {
                $json = simplexml_load_string($responseXml);

                array_push($return_array, $json);
            } else {
                $xml = new SimpleXMLElement($responseXml);

                array_push($return_array, strval($xml->SiteHostedPictureDetails->FullURL));
            }
        }


        return $return_array;
    }
}
// This is a modified version of the 'eBaySession' class which is used in many
// of the other PHP samples.  This has been modified to accomodate multi-part HttpRequests
class eBaySession
{
    private $requestToken;
    private $devID;
    private $appID;
    private $certID;
    private $serverUrl;
    private $compatLevel;
    private $siteID;
    private $verb;
    private $boundary;

    public function __construct(
    $userRequestToken,
    $developerID,
    $applicationID,
    $certificateID,
    $useTestServer,
                            $compatabilityLevel,
    $siteToUseID,
    $callName,
    $boundary
) {
        $this->requestToken = $userRequestToken;
        $this->devID = $developerID;
        $this->appID = $applicationID;
        $this->certID = $certificateID;
        $this->compatLevel = $compatabilityLevel;
        $this->siteID = $siteToUseID;
        $this->verb = $callName;
        $this->boundary = $boundary;
        if (!$useTestServer) {
            $this->serverUrl = 'https://api.ebay.com/ws/api.dll';
        } else {
            $this->serverUrl = 'https://api.sandbox.ebay.com/ws/api.dll';
        }
    }

    /**	sendHttpRequest
        Sends a HTTP request to the server for this session
        Input:	$requestBody
        Output:	The HTTP Response as a String
    */
    public function sendHttpRequest($requestBody)
    {
        $headers = array(
                    'Content-Type: multipart/form-data; boundary=' . $this->boundary,
                    'Content-Length: ' . strlen($requestBody),
        'X-EBAY-API-COMPATIBILITY-LEVEL: ' . $this->compatLevel,  // API version

        'X-EBAY-API-DEV-NAME: ' . $this->devID,     //set the keys
        'X-EBAY-API-APP-NAME: ' . $this->appID,
        'X-EBAY-API-CERT-NAME: ' . $this->certID,

                    'X-EBAY-API-CALL-NAME: ' . $this->verb,		// call to make
        'X-EBAY-API-SITEID: ' . $this->siteID,      // US = 0, DE = 77...
            );
        //initialize a CURL session - need CURL library enabled
        $connection = curl_init();
        curl_setopt($connection, CURLOPT_URL, $this->serverUrl);
        curl_setopt($connection, CURLOPT_TIMEOUT, 30);
        curl_setopt($connection, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($connection, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($connection, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($connection, CURLOPT_POST, 1);
        curl_setopt($connection, CURLOPT_POSTFIELDS, $requestBody);
        curl_setopt($connection, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($connection, CURLOPT_FAILONERROR, 0);
        curl_setopt($connection, CURLOPT_FOLLOWLOCATION, 1);
        //curl_setopt($connection, CURLOPT_HEADER, 1 );           // Uncomment these for debugging
        //curl_setopt($connection, CURLOPT_VERBOSE, true);        // Display communication with serve
        curl_setopt($connection, CURLOPT_USERAGENT, 'ebatns;xmlstyle;1.0');
        curl_setopt($connection, CURLOPT_HTTP_VERSION, 1);       // HTTP version must be 1.0

        $response = curl_exec($connection);

        if (!$response) {
            print "curl error " . curl_errno($connection) . "\n";
        }
        curl_close($connection);





        return $response;
    } // function sendHttpRequest
}  // class eBaySession

**Comment by michabbb** [comment]
1) you post binary data (10 pages of scrolling, nobody needs)
2) you post some own code but your problem is related to this SDK

there is no need to apologize, but before you post tons of data, you should reflect
if this really helps others to help you. 

[there exists an example](apologize), you should use this as close as possible for your testing.

**Comment by Rykono** [comment]
Your link is broken what example do you mean?

**Comment by michabbb** [comment]
updated my comment, please try again

**Comment by Rykono** [comment]
I used that exact example in my code. The only difference is i use a foreach to make a new uploadSiteHostedPicture for each picture. Could there be a problem with running multiple uploads at once?

**Comment by michabbb** [comment]
don´t know... are you able to make this example running without any modifictions ?
