### ISSUE TITLE
Trading API Updates

### ISSUE THREAD

**Issue by ShaneOH** [davidtsadler/ebay-sdk-php#193]
There are some minor updates (e.g. new field inclusions) to several calls in the Trading API, [as described here](https://developer.ebay.com/pbse).

- Is there any ETA on adding support for these updates?
- Are Pull Requests being accepted to begin adding some of this functionality?

**Comment by davidtsadler** [comment]
I will look at getting the SDK up to date with the latest API versions over the new few days.
