### ISSUE TITLE
Issues Occured when add product into Ebay motors

### ISSUE THREAD

**Issue by ssrgspdkt** [davidtsadler/ebay-sdk-php#196]
Hi Please provide an example PHP code to upload product in Ebay Motors. Currently Product add working correctly in Ebay main site. I have Specified SiteID as 100 but Still not working. I could see the following errors.

**Warning: Invalid Payment Terms Payment Method is not supported on this site or the category you have selected. It has been removed from the listing.

Warning: PayPal settings removed. Your PayPal settings have been removed from the listing since you do not have a PayPal account or specified Deposit as none.

Warning: FullPaymentTime Defaulted Item was submitted with 7 days for DaysToFullPayment

Error: Duration Invalid. The duration "GTC" day(s) is not available for this listing type, or invalid for category "10156".

Error: Payment method is missing. You must choose at least one payment method.

Warning: Category 10156 requires custom item specifics. Category 10156 only accepts custom item specifics.

Error: Seller Provided Title Value is missing. Seller Provided Title Value is missing.

Warning: Return policy is not supported. Return policy is not supported for this category.**

**Comment by michabbb** [comment]
hi, this doesn´t sound like a bug with the SDK, so you should consult the mailinglist, the official ebay forum or the ebay professional support. do your call with the [api test tool](https://developer.ebay.com/DevZone/build-test/test-tool/) before you do with the SDK, so you know what needs to be set.
