### ISSUE TITLE
GeteBayDetails->PaymentOptionDetails returns NULL

### ISSUE THREAD

**Issue by twigs67** [davidtsadler/ebay-sdk-php#198]
PaymentOptionDetailsType [appears to be empty](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Trading/Types/PaymentOptionDetailsType.php).

**Comment by michabbb** [comment]
the moon [appears to be far away](https://www.google.de/moon)

**Comment by twigs67** [comment]
Sorry, I think I'm missing something here. Is that intentional?

**Comment by yiiprogrammer** [comment]
please restate your question. and what is your code? check for any misspelling of variables, etc. (don't show your credentials)

**Comment by twigs67** [comment]
DTS\eBaySDK\Types\RepeatableType::__set_state(array(
   'data' => 
  array (
  ),
   'position' => 0,
   'class' => 'DTS\\eBaySDK\\Trading\\Types\\GeteBayDetailsResponseType',
   'property' => 'PaymentOptionDetails',
   'expectedType' => 'DTS\\eBaySDK\\Trading\\Types\\PaymentOptionDetailsType',
