### ISSUE TITLE
Unable to find a way to get sold items list

### ISSUE THREAD

**Issue by king4aol** [davidtsadler/ebay-sdk-php#20]
Hi, I am looking for a way to get all sold items list from my seller account. Please help me out in this or give me any reference to the appropriate example. Thanks

**Comment by davidtsadler** [comment]
[GetMyeBaySelling](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetMyeBaySelling.html) will get a list of sold items. There is an [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php) available. At the moment the example obtains the [list of active listings](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetMyeBaySelling.html#Request.ActiveList) but you can [modify](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/11-get-my-ebay-selling.php#L74) it to obtain the [sold list](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetMyeBaySelling.html#Request.SoldList).
