### ISSUE TITLE
FindProduct by type in Shopping API is not correct

### ISSUE THREAD

**Issue by KryDos** [davidtsadler/ebay-sdk-php#200]
Hi @davidtsadler, thank you for the great package. 

I'm currently trying to use [Find Product](http://developer.ebay.com/devzone/Shopping/docs/CallRef/FindProducts.html#FindProducts) Shopping API and I want to find a product by ProductID. But unfortunately can't make it working. 

The issue is ebay documentation asks me to pass `type` attribute (for ProductID). The `src/Shopping/Types/FindProductsRequestType.php` has `ProductIDType` class as a type of  `ProductID`. Unfortunately there is no `type` property defined in `ProductIDType` (of shopping api) and of course I  can't pass it. 

I was trying to redefine `ProductIDType` with my own class but it doesn't work since type check is there. Assigning `false` value to `Sdk::$STRICT_PROPERTY_TYPES` doesn't work as well because `checkPropertyType` function is going to return false only for basic types (int, string, etc...).

**Is there any way I can extend a class from SDK and pass it to the request without type checking?** 

P.S.
Let me know if I described it in a bit complex way, I'll try to do it better.

**Comment by KryDos** [comment]
ok, I was able to fix it with composer.json and psr-4

basically I've added this:

```json
        "psr-4": {
          "DTS\\eBaySDK\\Shopping\\": "myapp/sdkfixes"
        }
```

and in `myapp/sdkfixes` I've added `Types` directory with `ProductIDType` class. 
So composer helped a lot and it uses my own implementation before the original implementation which is good. 

Fill free to close the issue if there is no better solution for now.

**Comment by davidtsadler** [comment]
The SDK is generated from the eBay WSDLs. I agree that the type attribute should be a member of the class. I'll need to look into why the code generator is not picking that property up from the WSDLs.

**Comment by KryDos** [comment]
cool, thank you @davidtsadler 
is there any way I can help? I was trying to find the code that generates the repo code from WSDL (as you've mentioned) but wasn't able to find it.

**Comment by ChangePlaces** [comment]
Yep I'm hitting the same problem and was pulling my hair out until I found this issue!
