### ISSUE TITLE
Compliance API

### ISSUE THREAD

**Issue by michabbb** [davidtsadler/ebay-sdk-php#201]
dear @davidtsadler ,

as you have been so kind to implement the Catalog API, i would be very thankful if you could do the same with the Compliance API - because of ebays stupid try to imitate amazon, i´m afraid, we need that API, too 😢 

thanks

**Comment by davidtsadler** [comment]
Leave this with me. I'll see what I can get done over the next few days.

**Comment by davidtsadler** [comment]
There is an example available if required. https://github.com/davidtsadler/ebay-sdk-examples/blob/master/compliance/01-get-listing-violations-summary.php
