### ISSUE TITLE
How to use this API GetCompatibilitySearchValuesRequest  filter 

### ISSUE THREAD

**Issue by yashangqingsong** [davidtsadler/ebay-sdk-php#202]
dear @davidtsadler 

ebay-sdk-examples-master/product_metadata/02-get-compatibility-search-values.php

How to add the parameters of the filter, can you give an example：
/**
 * Create the request object.
 */
$request = new Types\GetCompatibilitySearchValuesRequest();
$request->categoryId = '174090';
$request->propertyName = 'Model';
$request->propertyFilter = [????];//eg. filter  Car Make => BMW
$request->listFormatOnly = true;

I wrote the code like this :
$request->propertyFilter = [
                                            'propertyFilter' => new Types\PropertyValue(
                                                [
                                                'propertyName' => new Types\Value(
                                                        new Types\StringValue(['propertyFilter' => 'BMW'])
                                                    )
                                                ]
                                            )
                                    ];

But it's always wrong。

**Comment by michabbb** [comment]
@yashangqingsong close without any solution? Let others learn from your mistakes.

**Comment by yashangqingsong** [comment]
change this issue to ebay-sdk-examples

**Comment by michabbb** [comment]
@yashangqingsong ????

**Comment by yashangqingsong** [comment]
https://github.com/davidtsadler/ebay-sdk-examples/issues/61
