### ISSUE TITLE
Get relist item ID after product expired in the Shopping Service

### ISSUE THREAD

**Issue by almonax** [davidtsadler/ebay-sdk-php#203]
Hi everyone
I build service to review anything products. The writer creates an article and fills products to it.
We use DTS\eBaySDK\Shopping\Services\ShoppingService with method getMultipleItems() by getting information about the product, but we have a problem with products which expired and has been relisted

For example: 
If writer added a link to the product on the eBay: https://www.ebay.de/itm/Lego-Darth-Vader-TIE-Fighter-8017-Anleitung-OVP-/123190324900
And after its expired time of the product and if you go to this link you will have a redirect to https://www.ebay.de/itm/Display-stand-angled-no-3-for-75105-7965-Millennium-Falcon-Star-Wars-Lego-/172850356481?oid=123190324900 , this a product with new ItemID, which can contain different cost, name, and other information.

Could you explain how we can get a new ItemID on which redirect on basic request from the browser?

I try to use method getItem in the DTS\eBaySDK\Trading\Services\TradingService for get Item.ListingDetails.RelistedItemID, but I have got error:
```php
$service = service = new TradingService([
    'credentials' => $this->availableAccs[$this->currentAccKey],
    'siteId'      => $this->siteId // DTS\eBaySDK\Constants\SiteIds::DE
]); 
$request = new GetItemRequestType();
$request->DetailLevel[] = DetailLevelCodeType::C_RETURN_ALL;
$request->ItemID = $itemsIdString;
$response = $service->getItem($request);
```
Response:
```php
`GetItemResponseType {#507 ▼
  -values: array:5 [▼
    "Timestamp" => DateTime @1529747514 {#506 ▶}
    "Ack" => "Failure"
    "Errors" => RepeatableType {#526 ▼
      -data: array:1 [▼
        0 => ErrorType {#518 ▼
          -values: array:5 [▼
            "ShortMessage" => "No Password and no token."
            "LongMessage" => "No XML <RequestPassword> or <RequestToken> was found in XML Request."
            "ErrorCode" => "930"
            "SeverityCode" => "Error"
            "ErrorClassification" => "RequestError"
          ]
          -attachment: array:2 [▼
            "data" => null
            "mimeType" => null
          ]
        }
      ]
      -position: 0
      -class: "DTS\eBaySDK\Trading\Types\GetItemResponseType"
      -property: "Errors"
      -expectedType: "DTS\eBaySDK\Trading\Types\ErrorType"
    }
    "Version" => "1063"
    "Build" => "E1063_CORE_API_18716213_R1"
  ]
  -attachment: array:2 [▼
    "data" => null
    "mimeType" => null
  ]
}
```

**Comment by michabbb** [comment]
please read the [wiki](http://devbay.net/sdk/guides/guide/credentials.html) or inspect the [samples](https://github.com/davidtsadler/ebay-sdk-examples).

**Comment by Dmitri10** [comment]
Hi guys. I'd like to have the same feature(to extract a new Item ID if I have an ended one ) 
But I'm not an owner of relisted item.
So it seems I can't use TradingService to get this kind of info. 
I've searched in official docs, articles, questions on stakoverflow and others to find another way.

The only thing I see is usage curl with redirect to extract a new ID, but captcha can brake it.

@michabbb Could you suggest something please?

**Comment by michabbb** [comment]
@Dmitri10 as far as i know: the getitem call gives you the "old itemid" of your own listings. i never had the need before to get this info from foreign listings so i don´t know the perfect solution here. but why don´t u ask the professional ebay support ? if there is another way, the will know - and tell you.

**Comment by Dmitri10** [comment]
@michabbb I'll get their response in 24-48 h so I wondered here if you or Topic author had the same problem.

**Comment by michabbb** [comment]
@Dmitri10 many thanks for letting us know

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔
