### ISSUE TITLE
ReviseItemStatus ErrorParamters 

### ISSUE THREAD

**Issue by twigs67** [davidtsadler/ebay-sdk-php#204]
Hello everyone,

Using the Trading API (ReviseItemStatus) ParamID in ErrorParameters is only providing numeric increments where I believe it should be showing ParamID values, such as "ItemID".  Here is an example response:

    'DTS\eBaySDK\Types\RepeatableType::__set_state(array(
       'data' => 
      array (
        0 => 
        DTS\eBaySDK\Trading\Types\ErrorType::__set_state(array(
       'values' => 
      array (
        'ShortMessage' => 'This listing would cause you to exceed the number of items (600) and amount ($9,500.00) you can list. ',
        'LongMessage' => 'This listing would cause you to exceed the number of items and amount you can list. You can list up to 379 more items and $6,114.03 more in total sales this month.',
        'ErrorCode' => '21919188',
        'SeverityCode' => 'Error',
        'ErrorParameters' => 
        DTS\eBaySDK\Types\RepeatableType::__set_state(array(
           'data' => 
          array (
            0 => 
            DTS\eBaySDK\Trading\Types\ErrorParameterType::__set_state(array(
               'values' => 
              array (
                'ParamID' => '0',
                'Value' => 'This listing would cause you to exceed the number of items (600) and amount ($9,500.00) you can list. ',
              ),
               'attachment' => 
              array (
                'data' => NULL,
                'mimeType' => NULL,
              ),
            )),
            1 => 
            DTS\eBaySDK\Trading\Types\ErrorParameterType::__set_state(array(
               'values' => 
              array (
                'ParamID' => '1',
                'Value' => 'This listing would cause you to exceed the number of items and amount you can list. You can list up to 379 more items and $6,114.03 more in total sales this month.',
              ),
               'attachment' => 
              array (
                'data' => NULL,
                'mimeType' => NULL,
              ),
            )),
            2 => 
            DTS\eBaySDK\Trading\Types\ErrorParameterType::__set_state(array(
               'values' => 
              array (
                'ParamID' => '2',
                'Value' => '262403205647',
              ),
               'attachment' => 
              array (
                'data' => NULL,
                'mimeType' => NULL,
              ),
            )),
          ),
           'position' => 0,
           'class' => 'DTS\\eBaySDK\\Trading\\Types\\ErrorType',
           'property' => 'ErrorParameters',
           'expectedType' => 'DTS\\eBaySDK\\Trading\\Types\\ErrorParameterType',
        )),
        'ErrorClassification' => 'RequestError',
      ),
       'attachment' => 
      array (
        'data' => NULL,
        'mimeType' => NULL,
      ),
        )),
      ),
       'position' => 0,
       'class' => 'DTS\\eBaySDK\\Trading\\Types\\ReviseInventoryStatusResponseType',
       'property' => 'Errors',
       'expectedType' => 'DTS\\eBaySDK\\Trading\\Types\\ErrorType',
    ))'

The third error element ("2") is the ItemID of the failed request and in the XML itself, it shows ParamID as: 
`<ErrorParameters ParamID="ItemID"><Value>262403205647</Value>`

Maybe I'm missing something, but is there a way to grab the string attribute ("ItemID")?

**Comment by davidtsadler** [comment]
I agree. If the XML is showing "ItemID" then ParamID via the SDK should be the same. Not sure at the moment why ParamID is returning an integer that appears to be incrementing. Will need to look into this.
