### ISSUE TITLE
How to implement this script?

### ISSUE THREAD

**Issue by juragandotid** [davidtsadler/ebay-sdk-php#207]
can u give me an example step to make order using this source?

search product -> getproductID -> checkout product -> guestcheckout -> payment -> suceess or failed.

**Comment by michabbb** [comment]
[reading is a powerful tool](https://github.com/davidtsadler/ebay-sdk-php/blob/master/README.md) -> **Resources** - the rest has nothing todo with the SDK, it´s about using the [ebay api](https://go.developer.ebay.com/api-documentation), therefor you have to read the docs.

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔
