### ISSUE TITLE
Auth'n'Auth token empty

### ISSUE THREAD

**Issue by klachhab** [davidtsadler/ebay-sdk-php#208]
Hi David,

First off all thank you so much for this fabulous library
Actuelly I cannot get the Auth'n'Auth token, I do get the SessionID but while I execute the FetchTokenRequestType I get this error message : No XML <RequestUserId> entity was found in the XML request. and it's a serious problem
I have tried the other method with which is the bay Sign-in page but I got empty Data : tknexp=1970-01-01+00:00:00 & ebaytkn=

Can you please tell me how I can solve the problem and generate the Token ? 

Cordially

**Comment by michabbb** [comment]
get your `Auth'n'Auth` token [here](https://developer.ebay.com/my/auth/?env=production&index=0).

![06-07-2018-06-45-30](https://user-images.githubusercontent.com/3524595/42390611-c46a82dc-814c-11e8-8214-84fc28a4ebfe.png)

**Comment by klachhab** [comment]
Hi Michael
Thanx for your response
Actually i mean programmatically unsing Php not manually 😊

**Comment by michabbb** [comment]
how should that be possible without any manual interaction ? btw.. google gives you [this](https://ebaydts.com/eBayKBDetails?KBid=1198).

**Comment by klachhab** [comment]
Yes it is possible using the FetchToken call cause i can generate OAuth tokens programmatically i can even refresh them without any manual interaction but i still searching the solution for this Auth'n'auth tokens fetching issue
I'll informe you once i found out how to do it

**Comment by michabbb** [comment]
**oAuth has nothing todo with Auth'n'Auth**, don´t mix things up here. and FetchToken is the correct call to get this "none-oAuth-token". and what i ment: manual action is of course necessary, to get your token in the first place:

```
Use this call to retrieve an authentication token for a user.   
The call can be used to get a token only after   the specified user 
has given consent for the token to be generated. Consent is given through the eBay    
sign-in page. After token retrieval, the token can be used to authenticate other calls 
made on behalf of the associated user.  
```

so i assume you already have a token (you know, the token that cannot be refreshed, because it has nothing todo with oAuth) and you only want to get it with [FetchToken](http://developer.ebay.com/devzone/xml/docs/reference/ebay/FetchToken.html) ?

**Comment by klachhab** [comment]
You're right OAuth is the best waybut Trading calls only accept Auth'n'Auth token

**Comment by michabbb** [comment]
> Trading calls only accept Auth'n'Auth token

[NO](https://github.com/davidtsadler/ebay-sdk-php/issues/164).

**Comment by klachhab** [comment]
I tried both Auth'n'auth and OAuth tokens, but sadly it works only with the A'n'A one 😟

Using Auth'n'Auth Token (generated manually from eBay Dev website) :
<img width="806" alt="using authnauth" src="https://user-images.githubusercontent.com/30941070/42395815-1e65baa4-8157-11e8-977c-cf6b8e5eeda5.png">

Using OAuth Token :
<img width="862" alt="using oauth token" src="https://user-images.githubusercontent.com/30941070/42395816-1e862956-8157-11e8-95dc-9c6c2d2cc152.png">

**Comment by klachhab** [comment]
Hi again Michael i'm so happy to say i found the solution and i did generated the Auth'n'Auth token PROGRAMMTICALLY finally

The solution that i found is : generate a SessionID

**Comment by klachhab** [comment]
Solved i finally found the solution

**Comment by michabbb** [comment]
do you think your message "solved" (without any information) does help anyone who is looking for the same problem ? 🤔

**Comment by klachhab** [comment]
Yep you're right 👍 

The solution is : 
use DTS\eBaySDK\Trading\Services as TradServ;
use \DTS\eBaySDK\Trading\Types as TradTypes;

$service = new TradServ\TradingService([
            'credentials' => $this->config['sandbox']['credentials'],
            'sandbox'     => true,
            'siteId'      => Constants\SiteIds::FR
        ]);

// Generate the SessionID using getSessionID like so => 
$getsessionid = $ervice->getSessionID(
            new TradTypes\GetSessionIDRequestType([
                'RuName' => $runame
            ])
        );
// then store it in a SESSION : 
$_SESSION["sessionid"] = $sessionid->SessionID;

// After that when you get redirected by after clicking 'Agree' in eBay's authorization page you can fetch the Token with this simple way : 

$tkn = $service->fetchToken(
                new TradTypes\FetchTokenRequestType([
                    'SessionID' => $_SESSION["sessionid"],
                ])
            );

That's it

I hope t'can help you

**Comment by michabbb** [comment]
*i* don´t need help here, but maybe others 😏

**Comment by klachhab** [comment]
By saying "You" i meant 'you' + Other people
P.S : You had to say "Thank you" at least Genious 😊

**Comment by joe-pritchard** [comment]
@klachhab - Just so that someone has said it: **Thank you** ;) 

We are all learning all the time and at different levels. Good on you for getting involved and for staying classy in the face of some fairly heavy passive-aggressive behaviour, keep it up

**Comment by klachhab** [comment]
Yes you're right Mr Pritchard 😊

**Comment by klachhab** [comment]
Yes you're right Mr Pritchard 😊
Learning and sharing what we've learned is the most important
Thank you

**Comment by michabbb** [comment]
are you guys crazy ? i invest my private time here to help others, to help david, so that he can focus on development and not on support, i even have to remind people to post their solutions - and for all that - someone tells **me** to say **thank you** ?? 😂 😂 😂 have an nice day anyway you two sensitive 😂

**Comment by salvesvence** [comment]
@klachhab Hi! I'm trying to make the connection with your example and I'm not capeable to get the token when I redirect the url, it always show this message: 

> The secret Id you provided does not match with the one you provided earlier.

It's frustrating because I spent 3 days with that and I still figthing.

**Comment by bbunlock** [comment]
I know its an old thread but got my sign in working perfectly with the solution posted by klachhab, followed his demo code (cleaned up errors) and now my app generates auth n auth tokens perfectly.

Thank you
