### ISSUE TITLE
Workflow on local

### ISSUE THREAD

**Issue by kossmokvin** [davidtsadler/ebay-sdk-php#209]
Hello 
Do I undestand correctrly that **it is impossible to get oAuth token on local machine** because I need to provide Accept page on web server (not local) to get Autorizatione Code from Ebay?

Or there is a way?
Without handy getting the token from devel account and hard-coding it, of course.

**Comment by michabbb** [comment]
first of all: this question has nothing todo with this SDK, it has even nothing todo with ebay at all 😏 
of course you can get a token at your local machine, for example:

- use a public dyn-dns-domain
- at your router: forward requests from outside to your local machine

but as i said, it has nothing todo with this sdk or ebay at all.

**Comment by kossmokvin** [comment]
Thank you for your comment.
I'm a bit new to all this, so it was a first try to get help =)
Anyway thanks!

**Comment by michabbb** [comment]
maybe [this](https://www.google.de/search?q=oauth+local+development&oq=oauth+local+&aqs=chrome.1.69i57j0l5.4417j0j1&sourceid=chrome&ie=UTF-8) helps 😏
