### ISSUE TITLE
MinimumBestOfferMessage is not working

### ISSUE THREAD

**Issue by ganganimaulik** [davidtsadler/ebay-sdk-php#21]
```
    if($bestOfferEnabled) {
        /**
         * Allow buyers to submit a best offer.
         */
        $item->BestOfferDetails = new Types\BestOfferDetailsType();
        $item->BestOfferDetails->BestOfferEnabled = true;

        /**
         * Automatically accept best offers of $acceptPrice and decline offers lower than $declinePrice.
         */
        $item->ListingDetails = new Types\ListingDetailsType();
        $item->ListingDetails->BestOfferAutoAcceptPrice = new Types\AmountType(array('value' => $acceptPrice));
        $item->ListingDetails->MinimumBestOfferPrice = new Types\AmountType(array('value' => $declinePrice));
        $item->ListingDetails->MinimumBestOfferMessage = $minimumBestOfferMessage;
    }
```

I'm trying to add MinimumBestObberMessage for my item but I can not add it. I even don't find it on [ebay addItem documentation](http://developer.ebay.com/devzone/xml/docs/reference/ebay/additem.html).

do you know how to add MinimumBestOfferMessage? It's there on [reviseItem ebay documentation.](http://developer.ebay.com/devzone/xml/docs/reference/ebay/ReviseItem.html).

thank you

**Comment by davidtsadler** [comment]
MinimumBestOfferMessage was deprecated and removed in version 629 of the Trading API. Searching for MinimumBestOfferMessage in the official eBay [WSDL](http://developer.ebay.com/webservices/latest/ebaySvc.wsdl) will confirm this.

**Comment by ganganimaulik** [comment]
Thanks :)
