### ISSUE TITLE
Question: about this SDK and eBay 2017 Restful API

### ISSUE THREAD

**Issue by timramseyjr** [davidtsadler/ebay-sdk-php#210]
Not sure where to ask this, and I am a little confused about this SDK and the new REST API eBay launched last year.   Does this package use any of the new API, or is it strictly for the older SOAP based API.  

Thanks!

**Comment by michabbb** [comment]
git offers a [search](https://github.com/davidtsadler/ebay-sdk-php/search?q=%22REST+API%22&type=Code), nice thing if u ask me 😏

**Comment by timramseyjr** [comment]
Thanks.  So the answer is both API's are mixed in this package.

Does anyone have any opinions if creating a new APP we should use the new API(does anyone know if eBay will deprecate the non REST version)?

The reason I ask is because I have working code working from an old app with non-REST version of the API, but I should update it won't work in a couple years.

**Comment by michabbb** [comment]
That question does not really has something to do with this SDK, but anyway, it's up to you if you use rest or not. I'm not aware of any statement that says, old APIs will be shut down in the near future.
You can ask ebay developer support for a reliable answer.

**Comment by Uebix** [comment]
@timramseyjr , this SDK is for REST API and for SOAP API, you can use both.

**Comment by Uebix** [comment]
Yes @timramseyjr, if ebay does not declare bankruptcy crushed by amazon, the SOAP api will be deprecated in about 3/4 years (eBay not say when).
