### ISSUE TITLE
Changing version in header

### ISSUE THREAD

**Issue by twigs67** [davidtsadler/ebay-sdk-php#211]
Hello all, 

Is there a way to change the API version in the header? For instance, in the Trading API I make the following call
`$request = new Types\ReviseInventoryStatusRequestType(); $request->Version = 1067;`

and the response I get is: 
`     'ShortMessage' => 'Header version 1039 does not match request version 1067.',
              'LongMessage' => 'The version 1039 in the HTTP header \'X-EBAY-API-COMPATIBILITY-LEVEL\' does not match the version 1067 in the request.  The HTTP header version will be used.',
              'ErrorCode' => '21926',
              'SeverityCode' => 'Warning',
              'ErrorParameters' => 
`

**Comment by michabbb** [comment]
reading the [README](https://github.com/davidtsadler/ebay-sdk-php/blob/master/README.md), leads you to the [User Guides](http://devbay.net/sdk/guides/), which has a [search](http://devbay.net/sdk/guides/search.html?q=apiversion&check_keywords=yes&area=default), that brings you finally [here](http://devbay.net/sdk/guides/guide/configuration.html?highlight=apiversion#apiversion).

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔
