### ISSUE TITLE
Issue using Filter in GetOrdersRestRequest()

### ISSUE THREAD

**Issue by choleaoum** [davidtsadler/ebay-sdk-php#218]
Correct me if I'm wrong, but I'm trying to use the last modified date filter in GetOrdersRestRequest, but the filter field says its property type is a string? 

https://github.com/davidtsadler/ebay-sdk-php/blob/42714ad203f0d37be53aa11fbe78b3eb6b18d34b/src/Fulfillment/Types/GetOrdersRestRequest.php#L26-L31

**Comment by michabbb** [comment]
technically everything that is part of the URL is a string 😏 
as the [docu](https://developer.ebay.com/api-docs/sell/fulfillment/resources/order/methods/getOrders) shows the example: 

```
GET https://api.ebay.com/sell/v1/order?
filter=creationdate:%5B2016-03-21T08:25:43.511Z..2016-04-21T08:25:43.511Z%5D,
lastmodifieddate:%5B2016-05-15T08:25:43.511Z..%5D,
orderfulfillmentstatus:%7BNOT_STARTED%7CIN_PROGRESS%7D 
```
maybe you have to concat the filter on your own.

btw... `orderIds` is a `string` too. as the docu says it´s a array of strings, but at the end it´s
only a `comma-separated list of the unique identifiers` - a developer should be able to handle this 😏

**Comment by choleaoum** [comment]
@michabbb Haha, thanks so much. That does make sense! I'm surprised I was the only one with this question, I've been searching everywhere. I was following existing examples with filters and just assumed it was an array of FilterFields.

**Comment by michabbb** [comment]
**it is** a array of FilterFields, but as this SDK only handles _a string_ i guess we have to build this _filter-string_ on our own 😏

**Comment by michabbb** [comment]
btw.. why don´t people never close their issues... i will never understand this... 🤔
