### ISSUE TITLE
Error- Invalid PostagePackage

### ISSUE THREAD

**Issue by slaveykov** [davidtsadler/ebay-sdk-php#221]
<Errors>

    <ShortMessage>Invalid postage package.</ShortMessage>

    <LongMessage>Invalid <PostagePackage>.</LongMessage>

    <SeverityCode>Error</SeverityCode>

    <ErrorClassification>RequestError</ErrorClassification>

</Errors>

**Comment by slaveykov** [comment]
I try to list product in ebay.com.au with my own script writen on php, but i recive this error. 
The same script work on ebay.com, ebay.de, ebay motors...

**Comment by michabbb** [comment]
this is nothing that has todo with this SDK, it´s a regular ebay api problem, please use the ebay developer forum or the developer support inside your developer account. beside that, maybe t[he first result in a google search](http://bfy.tw/JSQG) has something todo with your case.

**Comment by slaveykov** [comment]
Its a two results in google about this issue "Invalid+postage+package". And first result is my open issue in github. :)

**Comment by brideo** [comment]
For anyone seeing this I just didn't set a package type and it worked for me:

`//$packageDetails->ShippingPackage = ShippingPackageCodeType::C_PACKAGE_THICK_ENVELOPE;`
