### ISSUE TITLE
Feature request - Add new methods - Inventory API

### ISSUE THREAD

**Issue by boddie2** [davidtsadler/ebay-sdk-php#224]
Would it be possible to add new methods added in version 1.6.0 ?
https://developer.ebay.com/api-docs/sell/inventory/static/release-notes.html

Thank you

**Comment by davibennun** [comment]
+1
Looks like the type classes are generated automatically, is there any doc on how to generate those files? So we can submit a PR or something

**Comment by davibennun** [comment]
Great bulk calls on v1.6  https://developer.ebay.com/api-docs/sell/inventory/static/release-notes.html#Version7

**Comment by michabbb** [comment]
@davibennun take a look to the open-api-generator-project:

`docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://developer.ebay.com/api-docs/master/sell/inventory/openapi/3/sell_inventory_v1_oas3.yaml -g php -o /local/out/php`

gives you all the files in seconds 😏 

(i didn´t test the generated code, but looks nice)

**Comment by pdbreen** [comment]
Would be nice to update to gain access to withdrawOfferByInventoryItemGroup.  Also it seems eBay has a documentation issue with operatingHours field name for dayOfWeek (part of inventory location).  Documentation (and by extension, this library) declare the field name as "dayOfWeekEnum" with type of "dayOfWeekEnum".  In reality, it appears the field name should be "dayOfWeek".  Not sure how to address this without patching the generated code.
