### ISSUE TITLE
What's the long-term support roadmap for this project?

### ISSUE THREAD

**Issue by ChangePlaces** [davidtsadler/ebay-sdk-php#225]
With the new API's supporting OpenAPI what's the long-term roadmap of this project to be? As the new API's don't cover the old API's completely yet, there's still plenty of support for this project!

**Comment by davidtsadler** [comment]
I'm current in the process of having the SDK files been generated automatically from eBay's OpenAPI files. I will also keep support for the old APIs. I don't have a timeframe yet but I would like to have something in place over the next few months.

**Comment by henryturk** [comment]
Would it be possible to come up with contribution guidelines for this project? Or make the build instructions available so that the project can continue?

**Comment by michabbb** [comment]
@henryturk there are many good generators out there, feel free to give them a try, i did myself and they work pretty well: https://github.com/michabbb/php-ebay-sdk
