### ISSUE TITLE
How to get list of all products?

### ISSUE THREAD

**Issue by Gurpreet68** [davidtsadler/ebay-sdk-php#229]
I want to get list of all products, can you please let me know which service can be used from this library?
Thanks if you send me an code example.

**Comment by michabbb** [comment]
in the [README](https://github.com/davidtsadler/ebay-sdk-php/blob/master/README.md) you have guides and examples. this question has nothing todo with the SDK in case of a bug. you should go to the ebay developer forum and study the ebay [API docs](https://developer.ebay.com/docs), there are often more than one call for the same requirement, so working with the SDK requires **knowing the ebay api**.

**Comment by yamenarahman** [comment]
Use `GetMyEbaySelling` call.
