### ISSUE TITLE
refreshUserToken stopped working on 10/31

### ISSUE THREAD

**Issue by caesarcxiv** [davidtsadler/ebay-sdk-php#234]
$request = new Types\RefreshUserTokenRestRequest();
$request->refresh_token = XXXX;
$response = $service->refreshUserToken($request);

Refresh token is valid. Please advise

Response:

Fatal error: Uncaught DTS\eBaySDK\Exceptions\UnknownPropertyException: Unknown property errors in C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\Types\BaseType.php:464
Stack trace:
#0 C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\Types\BaseType.php(309): DTS\eBaySDK\Types\BaseType::ensurePropertyExists('DTS\\eBaySDK\\Typ...', 'errors')
#1 C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\Types\BaseType.php(276): DTS\eBaySDK\Types\BaseType->set('DTS\\eBaySDK\\Typ...', 'errors', Array)
#2 C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\Types\BaseType.php(62): DTS\eBaySDK\Types\BaseType->setValues('DTS\\eBaySDK\\Typ...', Array)
#3 C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\OAuth\Types\RefreshUserTokenRestResponse.php(79): DTS\eBaySDK\Types\BaseType->__construct(Array)
#4 C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\OAuth\Services\OAuthService.php(332): DTS\eBaySDK\OAuth\Types\RefreshUserTokenRestResponse->__construct(Array, 429, Array)
#5 C:\xampp\htdocs\imperio\vendor\guzzlehttp\promises\src in C:\xampp\htdocs\imperio\vendor\dts\ebay-sdk-php\src\Types\BaseType.php on line 464

**Comment by caesarcxiv** [comment]
"{"errors":[{"errorId":2001,"domain":"ACCESS","category":"REQUEST","message":"Too many requests","longMessage":"The request limit has been reached for the resource."}]}"

**Comment by sleipi** [comment]
I guess you hit the API Rate Limit

See https://developer.ebay.com/api-docs/static/oauth-rate-limits.html#

The rate limit is count per day in PST Time.
