### ISSUE TITLE
Does this SDK Support Marketplace Insights API

### ISSUE THREAD

**Issue by ashleighsims** [davidtsadler/ebay-sdk-php#235]
Not sure this is the right place to post this. Looking to get item sales history from a search which will bring back past sales over the last 90 days. I was using findCompletedItems but eBay told me to use the new Marketplace Insights API.

Any information would be great.

**Comment by michabbb** [comment]
have you looked to the code ? >>> https://github.com/davidtsadler/ebay-sdk-php/tree/master/src

**Comment by ashleighsims** [comment]
@michabbb Yes, I have looked in the code for the answer. First place I went to look for it.

I can find in the finding service the FindCompletedItems type however that is not what I’m after as this was what I was originally using.

I’m asking the question in case I have overlooked it in the code. If not maybe their are plans to in the future.

**Comment by michabbb** [comment]
my search is empty too, so it´s clear 😏 @davidtsadler said a while ago he is working an a complete new way of generating code for the new apis, but as always, i guess he is full of regular work, so don´t know when he comes up with this new stuff 😕
