### ISSUE TITLE
add EAN, Free Shipping and local pick up

### ISSUE THREAD

**Issue by futurewebsites** [davidtsadler/ebay-sdk-php#236]
Sorry to ask this here but I cannot seem to find how to add an EAN number to a fixed price item, Free Shipping and Local pick up, could you kindly point me in the right direction?

**Comment by michabbb** [comment]
hi, this question has nothing todo with the SDK, it´s about "howto use the ebay api" - therefore i suggest you take a look to the [official ebay forum](https://forums.developer.ebay.com/index.html).
the call you should take a look to is [ReviseItem](https://developer.ebay.com/devzone/xml/docs/reference/ebay/ReviseItem.html).

**Comment by futurewebsites** [comment]
Thanks for the head up
