### ISSUE TITLE
PHP 7.3 Error - "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by olimortimer** [davidtsadler/ebay-sdk-php#241]
On PHP 7.3.0 and eBay SDK PHP 18.0.0, I'm receiving the following error:

```
ErrorException  : "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

  at /site/vendor/dts/ebay-sdk-php/src/Parser/XmlParser.php:215
    211|                 case 'string':
    212|                 case 'double':
    213|                 case 'boolean':
    214|                 case 'DateTime':
  > 215|                     continue;
    216|                 default:
    217|                     return $meta->phpType !== '' ? new $phpType() : null;
    218|             }
    219|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError(""continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?", "/site/vendor/dts/ebay-sdk-php/src/Parser/XmlParser.php", ["/site/vendor/composer/../dts/ebay-sdk-php/src/Parser/XmlParser.php"])
      /site/vendor/composer/ClassLoader.php:444

  2   include()
      /site/vendor/composer/ClassLoader.php:444

  Please use the argument -v to see more details.
```

**Comment by olimortimer** [comment]
More of an FYI at the moment 😏

**Comment by Andicot** [comment]
+1

**Comment by michabbb** [comment]
sure, several +1 will help of course at a project, that is dead 🤦‍♂️

**Comment by olimortimer** [comment]
> sure, several +1 will help of course at a project, that is dead 🤦‍♂️

And yet you continue to comment 🤦‍♂️

**Comment by michabbb** [comment]
yes @olimortimer, someone who has eyes + brain and knows how to use them should tell the blind - you're welcome 🙄

**Comment by olimortimer** [comment]
FYI sarcasm is the lowest form of wit

**Comment by Michalbbb** [comment]
@olimortimer Yoooo, look at who u replying to :)

**Comment by yiiprogrammer** [comment]
@michabbb Does anyone know what happened to David Sadler? is he okay? he has an awesome eBay PHP SDK he's created over the years.

**Comment by michabbb** [comment]
@yiiprogrammer stop crying, no, I don't know, holy f... there are code generators out there that create classes perfectly, nobody is addicted to this sdk any longer. start freeing yourself and use modern code!

**Comment by yiiprogrammer** [comment]
Tool. But thanks for the tip
