### ISSUE TITLE
DetailLevel not work on getOrderTransactions

### ISSUE THREAD

**Issue by uresh** [davidtsadler/ebay-sdk-php#245]
Hi i was trying get all records using getOrderTransactions.
so set DetailLevel as "$request->DetailLevel = [Enums\DetailLevelCodeType::C_RETURN_ALL];". but it not return with all records only return 20 records.

**Comment by michabbb** [comment]
@uresh please close this issue, it has nothing todo with the SDK. the [DetailLevel](https://developer.ebay.com/devzone/xml/docs/reference/ebay/getorders.html#Request.DetailLevel) has nothing todo with the number of records you get, it´s about how many `Details` you get `for each` record.
if you don´t see all records you are interested in, please read the `Usage Details` of the ebay docu and play arround with the keys that are used to identify the timeframe of your orders.
for further questions, there is a [ebay developer forum](https://forums.developer.ebay.com/index.html). cheers.

**Comment by uresh** [comment]
> @uresh please close this issue, it has nothing todo with the SDK. the [DetailLevel](https://developer.ebay.com/devzone/xml/docs/reference/ebay/getorders.html#Request.DetailLevel) has nothing todo with the number of records you get, it´s about how many `Details` you get `for each` record.
> if you don´t see all records you are interested in, please read the `Usage Details` of the ebay docu and play arround with the keys that are used to identify the timeframe of your orders.
> for further questions, there is a [ebay developer forum](https://forums.developer.ebay.com/index.html). cheers.

@michabbb Hi, when i send request i set OrderIDArray abut 57 ids and set details levels return all, that meain it should respons to all sent order ids, but response array comes only  20 records.

**Comment by uresh** [comment]
@michabbb yes I understand now. thanks for your reply, could you suggest wich call i need to make to get more than 20 records, getMyeBaySelling request not return all details of the order. so could you recommend any

**Comment by michabbb** [comment]
@uresh the link in my first comment leads you to the docu of the ebay call "GetOrders", there u will find all infos. there is no limit of 20. you only see 20 because in that timeframe you are using aren´t any more orders. please read the infos about [paging](https://developer.ebay.com/devzone/xml/docs/reference/ebay/getorders.html#Request.Pagination.EntriesPerPage).

**Comment by codingleo** [comment]
I think this issue can be closed. @michabbb

**Comment by michabbb** [comment]
@codingleo 95% of all issues here can be closed, but i am not a maintainer, so it´s up to the people here, but most don´t care 😕 
@uresh please close the issue.
