### ISSUE TITLE
Which SDK supports: Featured Shop Monthly Auction/Fixed Price Allowance

### ISSUE THREAD

**Issue by yashangqingsong** [davidtsadler/ebay-sdk-php#247]
ebay  Background display:
<<<
Featured Shop Monthly Auction Allowance
Start 1 Jan 2019
End 1 Feb 2019      Used/Left: 35:265     => 300

Featured Shop Fixed Price Monthly Allowance
Start 1 Jan 2019
End 1 Feb 2019      Used/Left: 1500:0        => 1500
>>>
How can I get this information through the ebay restful API .
I have called almost all the functions in the SDK to test, but I haven't got the above value. Which SDK function do you get this value? I also looked at ebay's API documentation and couldn't find the corresponding api.
@davidtsadler

**Comment by michabbb** [comment]
First, you should know the ebay api call, to get want you want. If you don't know that call, you should consult the official eBay forum and ask there. If you finally know, that there is a call for your needs, you can search the code here to find out, if your call is supported by this SDK.
