### ISSUE TITLE
Error: Auth token is invalid error when try add item

### ISSUE THREAD

**Issue by superdevelop** [davidtsadler/ebay-sdk-php#248]
i try to add item to ebay by your sdk but always show this error although i try alot of auth token but still this error show itry it on localhost

Error: Auth token is invalid. Validation of the authentication token in API request failed.

**Comment by michabbb** [comment]
that´s not an error that has anything todo with the SDK, more with you doing something wrong. you should use the [ebay api test tool](https://developer.ebay.com/DevZone/build-test/test-tool/) first and see if you are able to make successfull calls to the api. if you are not able there, consult the official ebay forum and [check the docs](https://developer.ebay.com/devzone/xml/docs/Concepts/MakingACall.html#auth).

**Comment by calonzolg** [comment]
you can check this example: https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/04-add-fixed-price-item.php

**Comment by superdevelop** [comment]
hi, calonzolg,
Thank you for your reference.
I have checked it, but I got following errors.

Status Code: 200 v^1.1#i^1#f^0#r^0#p^3#I^3#t^H4sIAAAAAAAAAOVYe2wURRjv9ZlSWxJCKBGi52JIEPdu9vaeW+7I9ZVWoC13BbGCzezubLt0b/fcmaU9NHhUJDFqiISYiCKFSERjUEMkUVNR4qNAQAkoiShRfEAgxgQkxqjR2euDa1XotSQ28f65zMz3+n3fb76ZHZAuLr1rc8PmX8odJfl9aZDOdzi4MlBaXLSwoiD/1qI8kCXg6EvfmS7sLbiwCMOElhRiCCcNHSNnT0LTsZCZDDOWqQsGxCoWdJhAWCCSEI8uWyp4XEBImgYxJENjnI21YQaKQIIiDAS8Hk7mFZ7O6sM2W40w45OQB/mDHj7o8yElKNJ1jC3UqGMCdRJmPIALsYBjea4V8ILXLwC/C/hCbYxzJTKxauhUxAWYSCZcIaNrZsV6/VAhxsgk1AgTaYzWx5ujjbV1Ta2L3Fm2IkN5iBNILDx6VGPIyLkSaha6vhuckRbiliQhjBl3ZNDDaKNCdDiYCYSfSXUo6AUe6A0FQpzfLwb8NyWV9YaZgOT6cdgzqswqGVEB6UQlqRtllGZDXIskMjRqoiYaa53233ILaqqiIjPM1FVH71sRr4sxznhLi2msU2Uk20g53usJBX18kIkQhGkKkdneBbUE1Ic8DZobyvMYVzWGLqt21rCzySDViIaNxiaHz0oOFWrWm82oQuyQsuV8I0nk2uyqDpbRIp26XViUoJlwZoY3LsEwJ66x4GaxIqAExBAEfk4EAYggN5YV9l6fCDMidnGiLS1uOxYkwhSbgGYXIkkNSoiVaHqtBDJVWeB9Ct3dCmJlf0hhvSFFYUWf7Gc5BSGAkChKoeD/iiCEmKpoETRCkrELGZRhxk6qoEJFIEYX0ltTScSMlcw0nyFm9OAw00lIUnC7u7u7Xd28yzA73B4AOPeqZUvjUidKQGZEVr2xMKtmOCIhqoVVgdAAwkwPpSB1rncwkVhdfawu3tDe2rykrmmYvqMii4yd/RekcclIohZDU6XU1ILIm3ILNEmq2krRcRxpGv2bFFRsQ/2vQNp7/Z+B2jYwNQKTqsvmnUsyEm4D0uZlT7VnonaOR8gtWikag4xMl4mgbOhaavx6HRbdrIPa41PCtCKuwb5DYeTocbRyDjqqvo7uWsNMTcThiHIOOlCSDEsnE3E3pJqDhmJpiqppdmOaiMMs9VzC1KGWIqqEJ17DzMFD04vVjk6Sqx06R08rqi9BAjUjVyrZ5MWdRjJps1CiHSOHvaIodK9AS7JPnEm1lmgy2ZhIWASKGmqU7b0+xZqpB/AcmDREeWqhokczgabB1ppGMt6pJtl49SqW50M8/ezxQhYqPOeDsjwp2LVo3VSDHfKLPhCEARYovIfe6sQAG4KiyPo5xecTPV4p4FcmhblGU2lmp96tp8HABE2unDX0fn5TQRVuHJg0rgxth1gr057EcrTCrDfAeVgRKSK9rvO+8aIeM5F10f3bR4579DNDJC/z43od/aDX8Va+wwECgOUWggXFBSsKC25hsEqQC0NdFo0eF70cu2i71+lXtIlcXSiVhKqZX+y4f87Fxb9nPXD0rQGzR544Sgu4sqz3DjD32koRN72ynAsBjvYp3usH/jYw79pqITercGYwdr40b/6XXySanrrwY1XZZ01Xzl4F5SNCDkdRXmGvI2/7rNdnrr5ydOulU61nNh04v/rgtg/r8XeXlnyz/+vTT1x+tk7b+arwfMm8jVv21hY//nakf/r8E/1HPpfVJejltUtj7oF96y++s+Lj77dF5q85UyKe2Xfu3nvSm15Mvz/jpdP3PH3o2J6HQ6ZVUVq2vrJyT6qksyQ6Z3fZ5QU/Tys/paemqbebvb/tuuOH/qMLOnDliYs1Py2PvTdNWvzkkbDm2HX3m0VXN/h6An8OHK9+o6rp0oESZ8Vr/IMDxfPmnpzbEPj1aNXOmX3LNjy2JfzCzh2fzH4umk7N2N9xrD3v7Bz80EeRqu34gcS3DbuZZz5ti51M3vbVI4fPHQps/eODXRWHH91R/O5G5sDBvcdfGSzjX3JtITN6EgAA User Access Token 7200 v^1.1#i^1#f^0#r^1#p^3#I^3#t^Ul4xMF81OjE3RDM1MTBGNUJFRDMzRDlGM0NFNjZEMjc3Q0I0QjJCXzNfMSNFXjEyODQ= 

Error: Auth token is invalid. Validation of the authentication token in API request failed.

**Comment by superdevelop** [comment]
One more.
I am getting "code=<authorization-code-value>" manually to get user token on developer.ebay.com.
How can I get "code=<authorization-code-value>" with php programmically?
I would appreciate that if you can share the source code for that.

**Comment by calonzolg** [comment]
> One more.
> I am getting "code=" manually to get user token on developer.ebay.com.
> How can I get "code=" with php programmically?
> I would appreciate that if you can share the source code for that.

@superdevelop hi, here is how you can get OAuth token using this packages: https://github.com/davidtsadler/ebay-sdk-examples/blob/master/oauth-tokens/02-get-user-token.php

**Comment by calonzolg** [comment]
> hi, calonzolg,
> Thank you for your reference.
> I have checked it, but I got following errors.
> 
> Status Code: 200 v^1.1#i^1#f^0#r^0#p^3#I^3#t^H4sIAAAAAAAAAOVYe2wURRjv9ZlSWxJCKBGi52JIEPdu9vaeW+7I9ZVWoC13BbGCzezubLt0b/fcmaU9NHhUJDFqiISYiCKFSERjUEMkUVNR4qNAQAkoiShRfEAgxgQkxqjR2euDa1XotSQ28f65zMz3+n3fb76ZHZAuLr1rc8PmX8odJfl9aZDOdzi4MlBaXLSwoiD/1qI8kCXg6EvfmS7sLbiwCMOElhRiCCcNHSNnT0LTsZCZDDOWqQsGxCoWdJhAWCCSEI8uWyp4XEBImgYxJENjnI21YQaKQIIiDAS8Hk7mFZ7O6sM2W40w45OQB/mDHj7o8yElKNJ1jC3UqGMCdRJmPIALsYBjea4V8ILXLwC/C/hCbYxzJTKxauhUxAWYSCZcIaNrZsV6/VAhxsgk1AgTaYzWx5ujjbV1Ta2L3Fm2IkN5iBNILDx6VGPIyLkSaha6vhuckRbiliQhjBl3ZNDDaKNCdDiYCYSfSXUo6AUe6A0FQpzfLwb8NyWV9YaZgOT6cdgzqswqGVEB6UQlqRtllGZDXIskMjRqoiYaa53233ILaqqiIjPM1FVH71sRr4sxznhLi2msU2Uk20g53usJBX18kIkQhGkKkdneBbUE1Ic8DZobyvMYVzWGLqt21rCzySDViIaNxiaHz0oOFWrWm82oQuyQsuV8I0nk2uyqDpbRIp26XViUoJlwZoY3LsEwJ66x4GaxIqAExBAEfk4EAYggN5YV9l6fCDMidnGiLS1uOxYkwhSbgGYXIkkNSoiVaHqtBDJVWeB9Ct3dCmJlf0hhvSFFYUWf7Gc5BSGAkChKoeD/iiCEmKpoETRCkrELGZRhxk6qoEJFIEYX0ltTScSMlcw0nyFm9OAw00lIUnC7u7u7Xd28yzA73B4AOPeqZUvjUidKQGZEVr2xMKtmOCIhqoVVgdAAwkwPpSB1rncwkVhdfawu3tDe2rykrmmYvqMii4yd/RekcclIohZDU6XU1ILIm3ILNEmq2krRcRxpGv2bFFRsQ/2vQNp7/Z+B2jYwNQKTqsvmnUsyEm4D0uZlT7VnonaOR8gtWikag4xMl4mgbOhaavx6HRbdrIPa41PCtCKuwb5DYeTocbRyDjqqvo7uWsNMTcThiHIOOlCSDEsnE3E3pJqDhmJpiqppdmOaiMMs9VzC1KGWIqqEJ17DzMFD04vVjk6Sqx06R08rqi9BAjUjVyrZ5MWdRjJps1CiHSOHvaIodK9AS7JPnEm1lmgy2ZhIWASKGmqU7b0+xZqpB/AcmDREeWqhokczgabB1ppGMt6pJtl49SqW50M8/ezxQhYqPOeDsjwp2LVo3VSDHfKLPhCEARYovIfe6sQAG4KiyPo5xecTPV4p4FcmhblGU2lmp96tp8HABE2unDX0fn5TQRVuHJg0rgxth1gr057EcrTCrDfAeVgRKSK9rvO+8aIeM5F10f3bR4579DNDJC/z43od/aDX8Va+wwECgOUWggXFBSsKC25hsEqQC0NdFo0eF70cu2i71+lXtIlcXSiVhKqZX+y4f87Fxb9nPXD0rQGzR544Sgu4sqz3DjD32koRN72ynAsBjvYp3usH/jYw79pqITercGYwdr40b/6XXySanrrwY1XZZ01Xzl4F5SNCDkdRXmGvI2/7rNdnrr5ydOulU61nNh04v/rgtg/r8XeXlnyz/+vTT1x+tk7b+arwfMm8jVv21hY//nakf/r8E/1HPpfVJejltUtj7oF96y++s+Lj77dF5q85UyKe2Xfu3nvSm15Mvz/jpdP3PH3o2J6HQ6ZVUVq2vrJyT6qksyQ6Z3fZ5QU/Tys/paemqbebvb/tuuOH/qMLOnDliYs1Py2PvTdNWvzkkbDm2HX3m0VXN/h6An8OHK9+o6rp0oESZ8Vr/IMDxfPmnpzbEPj1aNXOmX3LNjy2JfzCzh2fzH4umk7N2N9xrD3v7Bz80EeRqu34gcS3DbuZZz5ti51M3vbVI4fPHQps/eODXRWHH91R/O5G5sDBvcdfGSzjX3JtITN6EgAA User Access Token 7200 v^1.1#i^1#f^0#r^1#p^3#I^3#t^Ul4xMF81OjE3RDM1MTBGNUJFRDMzRDlGM0NFNjZEMjc3Q0I0QjJCXzNfMSNFXjEyODQ=
> 
> Error: Auth token is invalid. Validation of the authentication token in API request failed.

You can try with the Auth'n'Auth, because i think the OAuth is only use for RestFull Api of ebay. For Ebay Trading API (Old Api), maybe need use the Auth'n'Auth

**Comment by superdevelop** [comment]
https://github.com/davidtsadler/ebay-sdk-examples/blob/master/oauth-tokens/02-get-user-token.php
of course, I am using above sample to get user token.
but user token has expired time.
So we have to get user token with real-time.
we need to get "code=authorization-code-value" to get user token.
"code=authorization-code-value" also will be change as time goes.
but I am getting "code=authorization-code-value" manually.
following shows how to get "code=authorization-code-value" manually.
https://api2cart.com/faqs/connect-ebay-api2cart/

so I would want to get it programmatically.

**Comment by calonzolg** [comment]
and this: https://github.com/davidtsadler/ebay-sdk-examples/blob/master/oauth-tokens/03-refresh-user-token.php maybe help to refresh token ??

**Comment by mikkame** [comment]
Hi. I have same problem.

https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/04-add-fixed-price-item.php

This code not working in my case.

I fixed it.

try change:

```
$service = new Services\TradingService([
    'credentials' => $config['sandbox']['credentials'],
    'sandbox'     => true,
    'siteId'      => $siteId,
    'authorization' => 'user_access_token'
]);

```

and delete this

```
$request->RequesterCredentials = new Types\CustomSecurityHeaderType();
$request->RequesterCredentials->eBayAuthToken = $config['sandbox']['authToken'];
```
