### ISSUE TITLE
Unable to get Tracking Information about a specific order

### ISSUE THREAD

**Issue by elkpodemiami** [davidtsadler/ebay-sdk-php#249]
When I use the "GetOrderRequestType" function to get the specific order I bought, I do not get the Tracking information for the order (carrier / Tracking Number, etc), but when I check online the seller already listed the tracking number on the package.

I dont know what to do at this point. 

The code I use (simplified) is this to make the call:
`
$request = new Types\GetOrdersRequestType();
        $request->DetailLevel[] = "ReturnAll";
        $request->NumberOfDays = 10;
        $ordersArray = new Types\OrderIDArrayType();
        $order = (example) 111-111;
        $ordersArray->OrderID[] = $order;
        $request->OrderIDArray = $ordersArray;
        $request->OrderRole = "Seller";
    
        $response = $service->getOrders($request);
`

**Comment by michabbb** [comment]
before posting here, you should be sure that this is related to the SDK. to check this, use the [ebay api test tool](https://developer.ebay.com/DevZone/build-test/test-tool/) to find out, if the response contains the info you are looking for, if it´s not there, the SDK cannot provide it - of course 😏
