### ISSUE TITLE
Return Policy Attribute Not Valid

### ISSUE THREAD

**Issue by Gurpreet68** [davidtsadler/ebay-sdk-php#251]
I am trying to update item detail but getting error "Return Policy Attribute Not Valid"
The request params are:
`$xml_request = "'<?xml version="1.0" encoding="utf-8"?>
            <ReviseItemRequest xmlns="urn:ebay:apis:eBLBaseComponents">
              <RequesterCredentials>
                <eBayAuthToken>'.$token.'</eBayAuthToken>
              </RequesterCredentials>
              <WarningLevel>High</WarningLevel>
              <Item>
                <ItemID>XXXXXXXXXX</ItemID>
                <Title>Product Description</Title>
                <StartPrice currencyID="USD">24.98</StartPrice>
                <ReturnPolicy>
                    <ReturnsWithinOption>Days_14</ReturnsWithinOption>
                    <ReturnsAcceptedOption>ReturnsAccepted</ReturnsAcceptedOption>
                    <Description>30 day. Buyer pays for return shipping</Description>
                    <WarrantyDurationOption>Years_2</WarrantyDurationOption>
                    <ShippingCostPaidByOption>Seller</ShippingCostPaidByOption>
                </ReturnPolicy>
              </Item>
            </ReviseItemRequest>";`

Thanks in advance

**Comment by michabbb** [comment]
what let you think, this could be a problem with the SDK and not with YOU sending wrong requests ?

**Comment by Gurpreet68** [comment]
I'm sending right information and successfully updated detail like name price etc, but the issue is  Im getting error in response, the error is "Return Policy Attribute Not Valid"
so what should I send in request to get successful response?

**Comment by michabbb** [comment]
So that is clearly not a problem with the SDK, so you should use the official channels like the ebay developer forum to handle your issues with the api.
More important, use the ebay api test tool until your requests works as expected:

https://developer.ebay.com/DevZone/build-test/test-tool/?index=0
