### ISSUE TITLE
Element names are incorrect in file

### ISSUE THREAD

**Issue by shivam311992** [davidtsadler/ebay-sdk-php#255]
I think the element name should be same as key at line number 26 and 32 in the following file. 

ebay-sdk-php/src/OAuth/Types/RefreshUserTokenRestRequest.php

**Comment by michabbb** [comment]
@shivam311992 in case u want to play with ebay oauth, this might be useful: https://github.com/michabbb/ebay-oauth-playground/

**Comment by shivam311992** [comment]
I already worked on this section and found that the request is working fine as 'key' directed but because of element name it creates confusion.
I was aware about it because I have read out the eBay developer doc for O-Auth process.
