### ISSUE TITLE
The Feed API not Working

### ISSUE THREAD

**Issue by yasir-topdot** [davidtsadler/ebay-sdk-php#259]
The feed API does not work.

It return error

> Status Code: 404 2002: Resource not found A resource (URI) associated with the request could not be resolved.

My code is
```
$service = new FeedServices\FeedService([
'authorization' => 'v^1.1#i^1#f^0#I^3#r^0#p^3#..........',
 'marketplaceId' => 'EBAY-US', 
'sandbox'=>true
 ]);
    /**
     * Create the request object.
     */
    $request = new FeedTypes\GetItemFeedRestRequest();
    /**
     * Note how URI parameters are just properties on the request object.
     */
   $request->category_id = '1';
   $request->feed_type   = 'ALL_ACTIVE';
   $request->date        = '0190515';
    /**
     * Send the request.
     */
    $response = $service->getItemFeed($request);
    /**
     * Output the result of calling the service operation.
     */
    printf("\nStatus Code: %s\n\n", $response->getStatusCode());
    if (isset($response->errors)) {
      foreach ($response->errors as $error) {
        printf(
          "%s: %s\n%s\n\n",
          $error->errorId,
          $error->message,
          $error->longMessage
        );
      }
    }
    if ($response->getStatusCode() === 200) {
      foreach ($response->itemFeeds as $itemFeed) {
        printf(
          "%s\n%s\n",
          $itemFeed->itemId,
          $itemFeed->title
        );
      }
    }
```

**Comment by michabbb** [comment]
because you don´t use the official ebay forum, you have a problem with the code itself (issues here are code related): so which code exactly is the problem in your case ?

**Comment by yasir-topdot** [comment]
> because you don´t use the official ebay forum, you have a problem with the code itself (issues here are code related): so which code (of the SDK) exactly is the problem in your case or where do you have found a bug?

Issue is not code related.  You can chec my code now

**Comment by michabbb** [comment]
@yasir-topdot when your problem **is not** code related, why do you post here and not at the official ebay forums or contact the ebay dev supportt ?
