### ISSUE TITLE
How to authorize ebay merchant account with the App and generate token for that account?

### ISSUE THREAD

**Issue by rohitkhatri** [davidtsadler/ebay-sdk-php#26]
How to authorize ebay merchant account with the App and generate token for that account to access the order history of the authorized user?

**Comment by michabbb** [comment]
if i understand you correctly:

1. https://developer.ebay.com/base/membership/signin/
2. upper right menu: [Auth Tokens for Ebay](https://developer.ebay.com/my/auth?env=sandbox&index=0) 
3. choose sandbox or production and follow instructions to get an auth token for an existing ebay user/seller
4. read the [examples](https://github.com/davidtsadler/ebay-sdk-examples/tree/master/trading) and [use the auth](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/01-get-ebay-official-time.php#L56) token within this framework as the examples show for the call [GetOrders](http://developer.ebay.com/devzone/XML/Docs/Reference/ebay/GetOrders.html)
