### ISSUE TITLE
Marketing resource url incorrect for BulkCreateAdsByListingId

### ISSUE THREAD

**Issue by dhm80** [davidtsadler/ebay-sdk-php#261]
https://github.com/davidtsadler/ebay-sdk-php/blob/42714ad203f0d37be53aa11fbe78b3eb6b18d34b/src/Marketing/Services/MarketingService.php#L34

The resource url must be  ```ad_campaign/{campaign_id}/bulk_create_ads_by_listing_id```

**Comment by michabbb** [comment]
the project is nearly two years old, the project owner didn´t say or do anything since a year, do yourself a favor and take a look into this: https://github.com/OpenAPITools/openapi-generator
