### ISSUE TITLE
Error 11 "Please specify a File with Valid Format"

### ISSUE THREAD

**Issue by viandanteoscuro** [davidtsadler/ebay-sdk-php#262]
Hi,

This library is amazing! Great work :D

But sometimes i have the error "Please specify a File with Valid Format" in AddFixedPriceItem request...
Moreover, if I try to re-send the same file, it works!

I don't make the xml like the examples, i already have the complete xml.
Simply, i load it with file_get_contents, then gzipped as in the examples...

```php
$payloadXml = file_get_contents(DATA_FILE);

...

$payloadData =  gzencode($payloadXml, 9);
$uploadFileRequest = new FileTransfer\Types\UploadFileRequest();
$uploadFileRequest->fileReferenceId = $createUploadJobResponse->fileReferenceId;
$uploadFileRequest->taskReferenceId = $createUploadJobResponse->jobId;
$uploadFileRequest->fileFormat = 'gzip';

$uploadFileRequest->attachment($payloadData);
```

Do you have any idea how to solve this issue?

Thanks.

Massimo

**Comment by stevukas** [comment]
Recently its happening for me too, it been good for years, but now i am getting everyday this error.
Please specify a File with Valid Format

**Comment by michabbb** [comment]
in that case, it´s obviously nothing code related and you should contact the ebay support or the official forum and close that issue here to avoid more of these dead issues that have nothing todo with the SDK.
