### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by aa4596037** [davidtsadler/ebay-sdk-php#265]
Hello, David. Your SDK very well, thanks. I need to dock EBAY's Notification. I set'Auction Checkout Complete'and'ItemListed' with 'SetNotificationPreferencesRequestType' to return the success prompt. But after I 'additem'and'buy item', . The URL I reserved did not receive any requests for connections. Can you help me?
![微信图片_20190720002811](https://user-images.githubusercontent.com/34262619/61550598-6f86fa80-aa85-11e9-972a-4d518d242221.png)

**Comment by michabbb** [comment]
1) David didn't answer (or do) anything over a year
2) your question is not related to a bug inside the SDK itself, so you should ask your question at a place that is alive, like the ebay developer forum 
3) the code is outdated anyway because of 1

**Comment by aa4596037** [comment]
> 1. 一年多来，大卫没有回答（或做过）任何事情
> 2. 你的问题与SDK本身内部的错误无关，所以你应该在一个活着的地方问你的问题，比如ebay开发者论坛
> 3. 因为1，代码已经过时了

ok.Thank you for your idea.
