### ISSUE TITLE
Finance API integration

### ISSUE THREAD

**Issue by hkonnet** [davidtsadler/ebay-sdk-php#266]
Hi,

First of all great package its helps alot. There is a new api ebay have now Finance API. I need to integrate that.. i think this package hasn't include this API yet ? can you please tell me can i use Finance API using Auth'nAuth mehtod or i have to use o'auth method? Can you please direct me how should i start ..

Thanks.

**Comment by michabbb** [comment]
consider this project as dead. it´s easy to generate your own classes, there are great code generators out there:

https://github.com/WsdlToPhp/PackageGenerator
https://github.com/OpenAPITools/openapi-generator

here´s an example:

https://github.com/michabbb/php-ebay-sdk/tree/php5
