### ISSUE TITLE
Unable to search category by keywords

### ISSUE THREAD

**Issue by niraj-lal-rahi** [davidtsadler/ebay-sdk-php#268]
Hello everyone,

I am able to fetch all the category with parent and child.
But, I am trying to search category from keywords. I have done R&D of many blogs but it does not really help me.

Any help?

**Comment by michabbb** [comment]
this sounds not like an issue that is sdk related, more than using the eBay api, in that case this is the wrong place. use the official eBay forum or the still existing mailing list of this project.
