### ISSUE TITLE
HTTPS everywhere?

### ISSUE THREAD

**Issue by BenMorel** [davidtsadler/ebay-sdk-php#269]
Hi, I'm using your SDK, and just received this final warning from eBay:

> **You have 27 days to address Finding API integration**
>
> Hi Benjamin,
>
> eBay is making a critical update to our Finding API.
>
> Before October 1, all partners must update their API requests to only use HTTPS service endpoints. After that point, all Finding API calls with HTTP endpoints will fail.

I just want to ensure that there aren't any http endpoint in use in the SDK?

From what I can see [here](https://github.com/davidtsadler/ebay-sdk-php/blob/18.0.0/src/Finding/Services/FindingBaseService.php#L34) it looks alright, but I want to be on the safe side 😉

Thanks in advance!

**Comment by michabbb** [comment]
anyway, the project is dead. you point to https, so should be all fine.

**Comment by BenMorel** [comment]
@michabbb Is it? I can see that there haven't been any commits for a year and that quite a few issues are stacking up, but that doesn't necessarily mean that the project is dead.

For me it's proved stable so far, and I don't know if there are better alternatives at the moment.

Maybe @davidtsadler could clarify this, he may just be busy on other things at the moment.

**Comment by michabbb** [comment]
no, of course, a project without commits over year a and without any feedback from the owner is more than alive, you're right 😂

people are too lazy to use code generaters to have full control over their code, instead they cling to everything that is there, no matter how outdated it is - coders are lazy 😊
