### ISSUE TITLE
How to change quantity to zero for fixedpriceitem

### ISSUE THREAD

**Issue by korcstar** [davidtsadler/ebay-sdk-php#27]
I have try below code to change quantity as 0

`$service = new Services\TradingService(array(
    'authToken' => $authToken,
    'apiVersion' => '899',
    'siteId' => $siteID
));

$request = new Types\ReviseInventoryStatusRequestType();
$inventoryStatus = new Types\InventoryStatusType();
$inventoryStatus->ItemID = $itemID;
$inventoryStatus->Quantity = $quantity;
$request->InventoryStatus[] = $inventoryStatus;
$request->ErrorLanguage = 'en_US';
$request->WarningLevel = 'High';

$response = $service->reviseInventoryStatus($request);`

but I get fail from ebay

eBay Fail: Quantity is not valid.The quantity must be a valid number greater than 0

I want to change as 0 so end item on ebay

Any help?

**Comment by henryturk** [comment]
Please read the documentation regarding [ending a listing](http://developer.ebay.com/Devzone/XML/docs/Reference/ebay/EndItem.html) on Ebay.

**Comment by korcstar** [comment]
This means there is not way to change as 0 and auto ended?

**Comment by henryturk** [comment]
No, if you want to end a listing you must explicitly end it. If you want to set a listing quantity to 0 but still have it online you need to enable the [Out Of Stock Feature](http://developer.ebay.com/DevZone/guides/ebayfeatures/Development/Listings-UseOutOfStock.html).

**Comment by michabbb** [comment]
@korcstar quantity has nothing todo with "ending an item" :smile: as @henryturk already mentioned, it´s only for "hiding" an item.

**Comment by korcstar** [comment]
Thanks All
