### ISSUE TITLE
Internal error to the application:10007 on GetOrders api

### ISSUE THREAD

**Issue by kaydee92** [davidtsadler/ebay-sdk-php#270]
Hi,
i have used your SDK, and it works fine, but from last 2 days, sometimes it gives "Internal error to the application:10007" error.

![image](https://user-images.githubusercontent.com/40662274/64863697-200f1600-d653-11e9-88db-b6370376ec8b.png)

please give solution for that

Thanks

**Comment by michabbb** [comment]
1) as the message says: it´s a message from ebay, a "internal error"
2) it´s not a bug in this SDK
3) maybe you build your request wrong, still, it´s a user problem, not a bug
4) contact the ebay developer support or use the official ebay forum

5) this project is dead, in case you didn´t notice that
