### ISSUE TITLE
AddFixedPriceItemRequest and SuperSize photos

### ISSUE THREAD

**Issue by jacksnodgrass** [davidtsadler/ebay-sdk-php#272]
I am trying to add an auction item with AddFixedPriceItemRequest. 
I used the Supersize with the UploadSiteHostedPicturesRequest call to upload the image to ebay.
 
https://i.ebayimg.sandbox.ebay.com/00/s/MTIwMFgxNjAw/z/4KAAAOSwruddug6W/$_32.JPG?set_id=880000500F

That does give me a 1600x1200 image.  Supposedly using 1600 image will give you the ZOOM option on auction items.   I get get a larger image uploaded with my auction but I don't the hover over the image to zoom option.  

Supposedly... you  are supposed to use something like: 
$item->PictureDetails = new Types\PictureDetailsType();
$item->PictureDetails->PhotoDisplay = Enums\PhotoDisplayCodeType::C_SUPER_SIZE;
when you add your images via  AddFixedPriceItemRequest but I am not getting an error.. my images do get referenced... but they are are 498x498 in width.  

If I use an EXTERNAL picture site and reference the image off of that, the ZOOM works as expected and I get my 1600x image loaded. 

So.. has anyone be able to upload their images to ebay AND take advantage of the ZOOM feature on an auction?

**Comment by michabbb** [comment]
issues here are for reporting bugs of the code, where is your bug? beside the fact that this project is dead - you should try your request without any sdk. use postman or the eBay api test tool to find out what the request should look like. if you fully understand the raw request, it shouldn't be a big deal to understand how this requests should look like with this sdk
