### ISSUE TITLE
Is there a flag / option / etc to log the xml response from ebay? 

### ISSUE THREAD

**Issue by jacksnodgrass** [davidtsadler/ebay-sdk-php#274]
As of Nov 1st, ebay started charging users taxes and automatically deducting it from the sale. I see tax stuff in the sdk call: 
getOrders($request)
but I don't see anything that says IF ebay added the taxes in the 
[Taxes]
structure. I see that $5.03 was calculated for the tax amount on the order BUT there is no flag to indicate if Ebay deducted that from the 
    [Total] => Array
        (
            [value] => 89.99
            [currencyID] => USD
        )
amount reported. Some sales have the tax amount added to the [Total] and paypal shows that the tax was taken out... Some sales do NOT have the tax ammount added to the [Total] and paypal says nothing about the Tax. 

So I am wondering if the XML returned for 
getOrders($request)
might show some newly added fields to say what sales have had taxes added/removed and which sales did not have the taxes taken out of. 

I can add the item amount, shipping cost and compare with the Total to see if there is a difference... which is the tax that ebay added... but if there wa a simple flag that I could use.. that would be better.

**Comment by michabbb** [comment]
what's your bug you try to report here? beside the fact, that this project is dead.

**Comment by jacksnodgrass** [comment]
Is there a flag / option / etc to log the xml response from ebay? 

Project might be dead.. but the code I am using ( mostly ) works. I can add items, track them, etc.  

Just seeing if there is a flag to capture the XML response. 

Thanks - jack

**Comment by michabbb** [comment]
http://devbay.net/sdk/guides/guide/configuration.html#http-options-debug.... maybe
