### ISSUE TITLE
DTS\eBaySDK\Trading\Types\AmountType value problem

### ISSUE THREAD

**Issue by antonellomangone** [davidtsadler/ebay-sdk-php#278]
Hi, I'm, trying to use the class in the subject and to assign the object created to item StartPrice or in ShippingServiceCost and ShippingServiceAdditionalCost. 

If I use a command like this:

$shippingService->ShippingServiceCost = new Types\AmountType(['value' => 2.00]);

taken from your example, the code works, but if I use a command like this:

$shippingService->ShippingServiceCost = new Types\AmountType(['value' => 2.53]);

I receive errorcode 37 and the problem is the decimal numbers

Is something I'm doing wrong or is a problem of the class ???

**Comment by michabbb** [comment]
1) this project is dead, since a long long time, so you're working with **DEAD CODE**
2) as always, when errors occur: check the XML that is generated and take a look to how it "should look like"
3) check google: https://ebaydts.com/eBayKBDetails?KBid=5042
4) use the official eBay forums

**Comment by antonellomangone** [comment]
I solved the problem. I'm Italian and my linux console has the double numbers with Italian style, so with commas in place of dots. To solve the problem I changed the locale representation of numbers and it all worked well, because my script is execute in the console and scheduled in crontab. 

I don't really know if the project is dead, but the last time David T. Sadler has contributed to the project is in August 2019 and also if the project would be dead someone could maintain it alive. 
I think is well done

**Comment by michabbb** [comment]
@antonellomangone please show me the link to this "august 2019". "well done" does not help if the classes are completely outdated. ebay has deleted keys, added new keys... all that is no longer covered by this SDK, sadly. but hey, people are lazy and stick to outdated stuff instead of inventing something new, I´m afraid.

**Comment by antonellomangone** [comment]
@michabbb here's the link you asked for:
https://github.com/davidtsadler?tab=overview&from=2019-12-01&to=2019-12-31

**Comment by michabbb** [comment]
@antonellomangone and what has "https://github.com/davidtsadler/arch" todo with this project ???????

**Comment by antonellomangone** [comment]
I know, but what I'm saying is that he is still alive and the last time he has done something on his repositories. I also wrote him a mail in order to understand if it's all ok.

**Comment by antonellomangone** [comment]
I think this fork could help:
https://packagist.org/packages/glassfrogbooks/ebay-sdk-php

Someone is still working on it

**Comment by michabbb** [comment]
good luck

**Comment by antonellomangone** [comment]
thank you ^_^
