### ISSUE TITLE
"Warning: "continue" targeting switch is equivalent to "break". 

### ISSUE THREAD

**Issue by CnczubehoerEu** [davidtsadler/ebay-sdk-php#279]
Hello, 

I am using the current version of Ebay SDK together with PHP 7.4 and get the following warning:
"Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/public/Packages/Libraries/dts/ebay-sdk-php/src/Parser/XmlParser.php on line 215" It is not a big problem - I just want to tell you for the next SDK version.

Thank you!

Tobias

**Comment by michabbb** [comment]
bro, this project is dead since a very very long time!  go and generate your own classes: https://github.com/WsdlToPhp/PackageGenerator - it has never been easier than that with the help of this great package.
