### ISSUE TITLE
XSD Based Class Generation

### ISSUE THREAD

**Issue by henryturk** [davidtsadler/ebay-sdk-php#29]
@davidtsadler What are you using to generate the classes from the Ebay XSDs?

Or rather, what do you recommend we use if we want to test different version of the Ebay API?

**Comment by davidtsadler** [comment]
Which service and version of the API are you wanting to test? You may get away with just specifying the version number in the [apiVersion](http://devbay.net/sdk/guides/guide/configuration.html#apiversion) configuration option.

**Comment by henryturk** [comment]
I guess I was more curious on what you were using to programmatically generate the classes than to actually test different versions of the API.
