### ISSUE TITLE
Version 1.0.0 Discussion

### ISSUE THREAD

**Issue by davidtsadler** [davidtsadler/ebay-sdk-php#3]
Work is now in progress on the version 1.0.0 release of the SDK. This is been be done on the [1.0.0-beta branch](https://github.com/davidtsadler/ebay-sdk-php/tree/1.0.0-beta). Version 1.0.0 is due for release in January 2016. Until then you should consider the 1.0.0-beta branch unsuitable for production. You can try out the latest changes by using composer.

```
php composer.phar require dts/ebay-sdk-php:dev-1.0.0-beta
```

Below are some of the things that I hope to include in the release. If you have any feedback or would like to suggest a new feature then please use the comments.

### Minimum PHP Version Increase

The SDK will require a minimum PHP version of 5.5.

### SDK Will Use Guzzle 6

Since Guzzle 3 will reach its end of life sometime in 2015 the SDK will use the latest Guzzle 6 version instead.

### HTML Will Be Converted To Entities Automatically.

Currently you have to convert HTML characters to entities.

```php
$item->Description = '&lt;h1&gt;Bits &amp; Bobs&lt;/h1&gt;&lt;p&gt;Just some &lt;stuff&gt; I found.&lt;/p&gt;';
```
In future the SDK will handle this for you.

```php
$item->Description = '<h1>Bits & Bobs</h1><p>Just some &lt;stuff&gt; I found.</p>';
```

### Logger Method To Be Removed.

Currently you can debug a service via the logger method.

```php
$logger = new LogClass();

$service = new DTS\eBaySDK\Shopping\Services\ShoppingService([
	'debug' => true
]);
$service->logger($logger);
```

The logger method will be replaced by a configuration option.

```php
$service = new DTS\eBaySDK\Shopping\Services\ShoppingService([
	'debug' => true,
	'logger' => new LogClass()
]);
```

### New Credentials Configuration Option.

The appId, authToken, certId and devId configuration options will passed via a new credentials option.

```php
$service = new DTS\eBaySDK\Trading\Services\TradingService([
    'credentials' => [
		'appId' => 'APP_ID',
		'authToken' 'AUTH_TOKEN',
		'certId' => 'CERT_ID',
		'devId' => 'DEV_ID'
	]
]);
```

### SDK Class

A new Sdk class will be introduced that will allow the sharing of configuration options across multiple service objects. The class will be a factory that produces service objects via its methods. The service objects returned from these methods will be configured with the options that were passed when the Sdk object was instantiated.

```php
$sdk = new DTS\eBaySDK\Sdk([
	'apiVersion' => '999',
	'credentials' => [
		'appId' => 'ABCDE-12345'
	]
]);

// Both services will be configured with the same apiVersion and credentials.
$finding = $sdk->createFinding();

$trading = $sdk->createTrading();
```

You will still be able to instantiate a service object without the Sdk class.

```php
$shopping = new DTS\eBaySDK\Shopping\Services\ShoppingService([
	'apiVersion' => '111',
        'credentials' => [
		'appId' => 'FGHIJ-67890'
	]
]);
```

### Credentials From Environment Variables

If you do not supply any credentials to a service object the SDK will attempt to find the credentials in your environment. It will look for values stored in the EBAY_SDK_APP_ID, EBAY_SDK_AUTH_TOKEN, EBAY_SDK_CERT_ID and EBAY_SDK_DEV_ID environment variables.

```php
// No credentials passed so the SDK will look them up via the environment variables.
$shopping = new DTS\eBaySDK\Shopping\Services\ShoppingService();
```

### Relax Type Checking Of Properties

A new global SDK option will be added that will relax the type checking used when assigning values to properties. By default the sdk will continue to use strict type checking.

```php
// Relax type checking.
DTS\eBaySDK\Sdk::STRICT_TYPE_CHECKING = false;

// Property expects an integer but is passed a string. 
// No exception is thrown when type checking has been relaxed.
$item->Quantity = '99';
```

Even when type checking is relaxed the SDK will still type check properties that expect an object to be assigned to it.

```php
// This will throw an exception
$item->StartPrice = '8.99';

// Will still have to assign an object to the property.
$item->StartPrice = new Types\AmountType(['value' => '8.99']);
```

**Comment by sebastianherrera** [comment]
great contribution, thank you!.

**Comment by michabbb** [comment]
:+1: well well well done... if i would have more time, i would switch asap to your new sdk.... still stuck in the old one ;)

**Comment by LexBel-co** [comment]
I am new to eBay's api and i found your eBay SDK for PHP. What i need is to read stock and prices of the products on eBay to update it my Magento Store, and i don't know which one of your SDK's services guide use to make the request (through retrieve csv or txt, or it can be done at real time). Thank you in advance for all your help and for your great contribution.

**Comment by sebastianherrera** [comment]
for magento to ebay and viceversa you can use directly www.m2epro.com . Its
free and will fulfill your needs.

2015-09-18 10:55 GMT-03:00 LexBel-co <notifications@github.com>:

**Comment by LexBel-co** [comment]
Thank u Sebastian for your answer, but we have already published the products into eBay, and now we will launch our website and we need to retrieve data (stock and prices) from eBay to Magento, and m2epro only works if we have our products into magento and we need to publish them to eBay

**Comment by LexBel-co** [comment]
Thank u Sebastian for your answer, but we have already published the products into eBay, and now we will launch our website and we need to retrieve data (stock and prices) from eBay to Magento, and m2epro only works if we have our products into magento and we need to publish them to eBay

**Comment by Baachi** [comment]
Instead of guzzle i would use httplug which is psr-7 compatible, if you want i can integrate it.

**Comment by davidtsadler** [comment]
I've been interested in HTTPlug since reading a [SitePoint](http://www.sitepoint.com/breaking-free-from-guzzle5-with-php-http-and-httplug/) article about it. Since the project is currently in the phase of alpha releases I don't want to integrate it into the SDK at this time. I may look at doing that some time in the future once it's stable though. 

For users that want to use their own HTTP client, the SDK will make this possible via a new service configuration option called `handler`.  You can supply a `callable` as the value and the SDK will pass in a `Psr\Http\Message\RequestInterface` object that you pass to your client.

```php

/**
 * Function to handle dispatching a request object via a HTTP client of our own choosing.
 *
 * @param Psr\Http\Message\RequestInterface $request . The request to be sent.
 *
 * @return string The XML response from the API.
 */
$myHandler= function (Psr\Http\Message\RequestInterface $request) {
    $client = new SomeClient();
    $response = $client->sendRequest($request);
   return $response->getBody()->getContent();
};

$service = new FindingService([
    'handler' => $myHandler,
    'siteId' => 0
]);
```

**Comment by Baachi** [comment]
@davidtsadler HTTPlug is currently in the release candidate step. And i talked with the guys and they said it will only exists one release candidate so a stable release will come in few weeks/days.
If i remember correctly they only want to improve the docs before go stable.

Didn't know that, of course this help a lot :+1:

**Comment by aggrosoft** [comment]
@davidtsadler when beginning a new project using the sdk currently - should we go for the 1.0-beta or stay with the old version and migrate then?

**Comment by davidtsadler** [comment]
Hi @aggrosoft. Good question. At the moment I'm a few days off from releasing version 1.0.0. I'm currently finishing off the documentation so there shouldn't be any changes to the 1.0.0-beta code unless I find a major bug between now and the official release. If your new project is not critical I would say go ahead with using the 1.0.0-beta code as you shouldn't have to make any changes to your project once version 1.0.0 is out. 

I would stay with the current SDK if you project is critical, (especially if it's for a paying client), and you don't want to take the risk that the beta code could change once the official version is out. I will be including a migration guide as part of the new documentation. To be honest there will not be much to migrate as there are not many breaking changes in the SDK. I've already migrated the examples over to the [beta version](https://github.com/davidtsadler/ebay-sdk-examples/commit/578d0a298f41be837d082de215202357b85408b1). Most of the migration was due to how the credentials are passed into the service object constructor. 

The one thing that  I should make you aware of is that I'm not sure if I will be supporting any pre version 1.0 code once it has been release.

**Comment by aggrosoft** [comment]
As this will be part of our software I think we will be going for the 1.0.0 then, we will wait until you release the final 1.0 version. Thanks for the great work, we will be providing commits for the bugs arrising ;)

**Comment by atvvarna** [comment]
Hi there,
Any news about the 1.0 release date?

Regards,
Alex

**Comment by davidtsadler** [comment]
@atvvarna  I'm aiming for the end of March for the version 1.0.0 release, but it could be early April if things get delayed. At the moment I'm working on finishing the documentation. There is a now a [migration guide](https://github.com/davidtsadler/ebay-sdk-php/blob/1.0.0-beta/docs/guide/migration.rst) available that should give people an idea of what changes they may need to make once version 1 is out. To be honest most of the changes are to do with how you configure a service object and so I'm not expecting people to have to change much. I've already [ported over the examples](https://github.com/davidtsadler/ebay-sdk-examples/commit/578d0a298f41be837d082de215202357b85408b1) if people want to see what changes I had to do.

**Comment by atvvarna** [comment]
Thanks for the reply, then I will start my project with the beta :-)

**Comment by davidtsadler** [comment]
No that version 1.0.0 is out I'll close this.
