### ISSUE TITLE
ebay sandbox vs. production differences to note

### ISSUE THREAD

**Issue by jlahijani** [davidtsadler/ebay-sdk-php#34]
Although this is not a bug or an issue with either eBay or this SDK, I think the following 'gotchas' may be worth noting in the documentation somewhere.

### listing size limit
With eBay's sandbox, there doesn't seem to be a listing size limit, or at least it's a lot higher than 90K.  Googling for eBay's listing size limit doesn't yield any results, but I think it's ~90K, which I read somewhere that escapes me.  So, if you plan on using something like Bootstrap and inlining it in your listing, you'll surpass this limit.  Instead, bring it in via ```<link>```.

If you surpass the limit, eBay's error doesn't indicate that it's a filesize limit (!), so it may leave you perplexed in determining where the issue is.

### phone numbers and emails in listings
With eBay's sandbox, you can list your email address and phone number, but you cannot with production.

**Comment by jlahijani** [comment]
I also believe sandbox doesn't recognize the set restocking fee.

**Comment by davidtsadler** [comment]
There's a few things that the sandbox does not support. eBay have created a [Knowledge Base article](https://ebaydts.com/eBayKBDetails?KBid=684) about this but I don't know how up to date it is. 

I'm very reluctant to start documenting the sandbox limits or the difference between it and production.   This is more eBay's responsibility as they should know more than me.
