### ISSUE TITLE
Getting 500 internal server error from the Ebay API.

### ISSUE THREAD

**Issue by jaesung2061** [davidtsadler/ebay-sdk-php#36]
Here is the code

```
$sdk = new DTS\eBaySDK\Sdk([
    'apiVersion' => '1.13.0',
    'Finding'    => [
        'apiVersion' => '1.13.0'
    ],
    'credentials' => [
        'appId'  => '<my-key>',
        'devId'  => '<my-key>',
        'certId' => '<my-key>'
    ]
]);

$finding = $sdk->createFinding();

$request = new FindItemsByKeywordsRequest();

$request->keywords = 'Harry Potter';

$request->paginationInput = new PaginationInput();
$request->paginationInput->entriesPerPage = 25;
$request->paginationInput->pageNumber = 1;

$request->sortOrder = 'CurrentPriceHighest';

try {
    $response = $finding->findItemsByKeywords($request);
} catch (Exception $e) {
    var_dump($e->getMessage());
}
```

I get this error message... truncated.

> Server error: POST http://svcs.ebay.com/services/search/FindingService/v1 resulted in a 500 Internal Server Error response:\n
<?xml version='1.0' encoding='UTF-8'?><e (truncated...)\n

I followed the example on getting started which gets the time from the API, which worked. However, this is giving me some issues. What am I doing wrong here?

**Note:** I dumped the $body variable in `callOperationAsync()` and got this:

```
1
25
CurrentPriceHighest
Harry Potter
```

Shouldn't this be in XML format?

**Comment by davidtsadler** [comment]
Ensure that you credentials are not blank or contain spaces at the start and end. Also ensure that you are not passing your sandbox credentials by mistake.

**Comment by jaesung2061** [comment]
Sandbox credentials don't work for this?

**Comment by davidtsadler** [comment]
The SDK has no way to determine which environment the credentials belong to. By default it will assume you want to connect to the production site unless you use  the  [sandbox]http://devbay.net/sdk/guides/guide/configuration.html#sandbox) configuration option to tell it otherwise.

**Comment by jaesung2061** [comment]
Ok it's all working great now. Thank you.

But I'm noticing it fails about 50% of the time due to timeout, is this a common issue with eBay servers?
