### ISSUE TITLE
DTS\eBaySDK\Trading\Types\MeasureType

### ISSUE THREAD

**Issue by achertovsky** [davidtsadler/ebay-sdk-php#39]
This class extended from `\DTS\eBaySDK\Types\DecimalType`, but `DecimalType` expects value as integer type
```
class DecimalType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = array(
        'value' => array(
            'type' => 'integer',
            'unbound' => false,
            'attribute' => false
        )
    );
```
How can i assign double data to MeasureType? For instance, i have package with dimensions
4,55x1,25x0,5 inches

p.s.

if just change there `integer` to `double` it will cause issue when call `DTS\eBaySDK\Trading\Services\TradingService::getOrders()`
Error is:
```
Invalid property type: DTS\eBaySDK\Trading\Types\MeasureType::value expected double, got integer in file /var/www/html/vendor/dts/ebay-sdk-php/src/DTS/eBaySDK/Types/BaseType.php on line 463
```

**Comment by davidtsadler** [comment]
As  a *temporary* fix I would recommend leaving `DecimalType` as an `integer` but switch off the SDK's type checking with `\DTS\eBaySDK\Sdk::$STRICT_PROPERTY_TYPES = false;` as [mentioned in the documentation](http://devbay.net/sdk/guides/guide/request-and-response-objects.html#property-types-are-enforced). This should allow you to set the dimensions using strings. E.g `width->value = '1.25'` or doubles E.g `width->value = 0.5`. This will hopefully work while I look into the issue.

**Comment by achertovsky** [comment]
@davidtsadler 
i'm afraid that i cant disable type checking, cause it may create a lot bugs for me. i will wait for solution.
thank you!

**Comment by davidtsadler** [comment]
It should now be possible to assign a double  to the MeasureType as the SDK now allows either an integer or double to be assigned as the value.

```php
$decimal = new  DTS\eBaySDK\Types\DecimalType();

// Assign integer values.
$decimal->value = 123;
$decimal->value = -123;

// Assign double values.
$decimal->value = 1.23;
$decimal->value = -1.23;
```

**Comment by achertovsky** [comment]
@davidtsadler 
Thank you, David!
I will contact you again if will find something weird.
