### ISSUE TITLE
eBay Security Update: Support for TLS 1.2 on API Endpoints 

### ISSUE THREAD

**Issue by bamburillo** [davidtsadler/ebay-sdk-php#43]
eBay is adding TLS1.2 support to API endpoints. See this [https://ebaydts.com/eBayKBDetails?KBid=5073](https://ebaydts.com/eBayKBDetails?KBid=5073)

This is not a bug, I did not check. But I would like to know - whether there is support TLS1.2 ?

**Comment by davidtsadler** [comment]
The SDK uses Guzzle 6 to handle the HTTP requests. I think, but not 100% sure, that as long as Guzzle and your system supports TLS1.2 there shouldn't be a problem. You can also provide your own HTTP handler if needed. http://devbay.net/sdk/guides/guide/configuration.html#httphandler
