### ISSUE TITLE
InternationalRateTable

### ISSUE THREAD

**Issue by Telrik** [davidtsadler/ebay-sdk-php#45]
Any example how to use InternationalRateTable ? did this sdk support it ?

**Comment by davidtsadler** [comment]
```php
$item->ShippingDetails = new \DTS\eBaySDK\Trading\Types\ShippingDetailsType();
$item->ShippingDetails->RateTableDetails = new \DTS\eBaySDK\Trading\Types\RateTableDetailsType();
$item->ShippingDetails->RateTableDetails->InternationalRateTable = '.....';
```

**Comment by davidtsadler** [comment]
Actually looking at the code the SDK should support the InternationalRateTable field but it currently missing from https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Trading/Types/RateTableDetailsType.php

I'll look into why.

**Comment by Telrik** [comment]
Thanks, also
![chrome_2016-09-22_23-03-09](https://cloud.githubusercontent.com/assets/141984/18753741/dc7860e6-8118-11e6-8524-dc63cac8be07.png)
the table itself don't have any name or id, so should i put 
$item->ShippingDetails->RateTableDetails->InternationalRateTable = 'true'; 
or '.....'; ?;)

**Comment by davidtsadler** [comment]
If you look at the documentation at http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/AddFixedPriceItem.html#Request.Item.ShippingDetails.RateTableDetails.InternationalRateTable, it appears that a seller can only specify one international rate table, so set it to Default.

```php
$item->ShippingDetails->RateTableDetails->InternationalRateTable = 'Default';
```

This may throw an exception as the InternationalRateTable may not exist in the SDK until I look into fixing the issue.

**Comment by Telrik** [comment]
Perfect, thanks a lot.
Will look for the fix. Before i want try to add InternationalRateTable into file manualy but it says DO NOT EDIT generated from wsdl so i add this issue first. thanks again.

**Comment by davidtsadler** [comment]
InternationalRateTable has been added in the 13.0.0 release.
