### ISSUE TITLE
\DTS\eBaySDK\Trading\Types\GetItemRequestType detailLevel doesn't exists

### ISSUE THREAD

**Issue by lupi85** [davidtsadler/ebay-sdk-php#46]
How can I retrieve the detail field?
The property detailLevel doesn't exists anymore. How can I do this?

Thanks and great job with the sdk!

**Comment by lupi85** [comment]
Sorr

**Comment by davidtsadler** [comment]
eBay's naming of fields is not consistent between services. In the Trading service fields start with a capital letter so you would use fields such as DetailLevel and Title. This is different to the Finding service where they start with a lowercase. E.g detaiLevel, title.

The is an issue with the API documentation not showing some fields, such as DetailLevel, that is been address in issue #42 .
