### ISSUE TITLE
cannot fetch ShipmentTrackingDetails

### ISSUE THREAD

**Issue by deepakgates** [davidtsadler/ebay-sdk-php#48]
When fetching orders or a single order, while other details are coming but ShipmentTrackingDetails is empty. I made sure the orders were shipped. Is there a way i can be sure if its because of the api or this library

Thanks

**Comment by davidtsadler** [comment]
You can use eBay's [API explorer](https://developer.ebay.com/my/api_test_tool) to test the API independently of the SDK.
