### ISSUE TITLE
BulkDataExchange - Header tag inserted after job type causing error

### ISSUE THREAD

**Issue by thomasnares** [davidtsadler/ebay-sdk-php#5]
When using BulkDataExchange (and maybe other calls), 
everything is fine using jobs types with first letter >H.

But when using EndFixedPriceItem for example, the generated XML is :

```
<BulkDataExchangeRequests xmlns="urn:ebay:apis:eBLBaseComponents">
	<EndFixedPriceItemRequest xmlns="urn:ebay:apis:eBLBaseComponents">
		<Version>871</Version>
		<ItemID>181741470745</ItemID>
	</EndFixedPriceItemRequest>
	<Header xmlns="urn:ebay:apis:eBLBaseComponents">
		<SiteID>71</SiteID>
		<Version>871</Version>
	</Header>
</BulkDataExchangeRequests>
```

The tags inside BulkDataExchangeRequests are sorted A-Z and this XML causes an error for eBay, , it needs Header first.

The error is : 

> Uploading end fixed price item requests...Done
> Request processing of end fixed price item...Done
> Error: There is failure during file upload and post-upload checking

I guess putting Header first in the method ($payload->toRequestXml()) would fix it.

When fixing via regex the generated xml, it works :+1: 
```
<BulkDataExchangeRequests xmlns="urn:ebay:apis:eBLBaseComponents">
	<Header xmlns="urn:ebay:apis:eBLBaseComponents">
		<SiteID>71</SiteID>
		<Version>871</Version>
	</Header>
       <EndFixedPriceItemRequest xmlns="urn:ebay:apis:eBLBaseComponents">
		<Version>871</Version>
		<ItemID>181741470745</ItemID>
	</EndFixedPriceItemRequest>
</BulkDataExchangeRequests>
```

**Comment by davidtsadler** [comment]
I've updated the SDK so that the properties are in the specified by the WSDL. This ensures that the header is before any of the other elements. Thank you for spotting this issue, much appreciated.

**Comment by affansaied** [comment]
Any one have experience with "ReviseInventoryStatusRequest" with BulkDataExchangeRequests?
have tried every thing with XML but same error "Error: There is failure during file upload and post-upload checking"

<BulkDataExchangeRequests xmlns="urn:ebay:apis:eBLBaseComponents">
    <Header xmlns="urn:ebay:apis:eBLBaseComponents">
        <SiteID>3</SiteID>
        <Version>961</Version>
    </Header>
       <ReviseInventoryStatusRequest xmlns="urn:ebay:apis:eBLBaseComponents">
        <InventoryStatus>
        <Version>961</Version>
        <ItemID>111941538820</ItemID>
      	<StartPrice>10.407</StartPrice>
    	</InventoryStatus>
    </ReviseInventoryStatusRequest>
</BulkDataExchangeRequests>

I am stuck in eBay API BulkInventoryUpload method for ReviseInventoryStatusRequest
tried creating XML as attached but after StartUploadJobResponse it always fail.
