### ISSUE TITLE
Interger overflow issue in SellerPaymentProfileType

### ISSUE THREAD

**Issue by gitmastro** [davidtsadler/ebay-sdk-php#50]
File: src/MerchantData/Types/SellerPaymentProfileType.php
When we have bigint value for payment profile ID  it does not works .. either we should type cast as string or long
```
 'PaymentProfileID' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'PaymentProfileID'
        ],
```

**Comment by davidtsadler** [comment]
Is your systrem 32Bit or 64Bit ?

**Comment by davidtsadler** [comment]
http://devbay.net/sdk/guides/getting-started/requirements.html#using-the-sdk-with-32-bit-systems

**Comment by gitmastro** [comment]
Thanks for prompt response ... you are right let me get back to you... my production is 64bit.. seems like bit is 32 bit
