### ISSUE TITLE
Completed but not paid

### ISSUE THREAD

**Issue by waza123x** [davidtsadler/ebay-sdk-php#52]
Hello I have a problem, need somehow to fix this.

I request ebay to give me all orders which are Completed & Paid.

I do this:

```
$request = new Types\GetMyeBaySellingRequestType();   
$args = array(
  "OrderStatus"   => "Completed",
  "SortingOrder"  => "Ascending",
  "CreateTimeFrom"   => new \DateTime(date("Y-m-d", time()-60*60*24*30*3)),
  "CreateTimeTo"   => new \DateTime(date("Y-m-d", time()+60*60*24)),
);

$getOrders = new Types\GetOrdersRequestType($args);
$getOrders->RequesterCredentials = new Types\CustomSecurityHeaderType();
$getOrders->RequesterCredentials->eBayAuthToken = $config['production']['authToken'];
$getOrders->IncludeFinalValueFee = true;
$getOrders->Pagination = new Types\PaginationType();
$getOrders->Pagination->EntriesPerPage = 9999999;
$getOrdersPageNum = 1;

$response = $service->getOrders($getOrders);
```

But today I got one order, which have a status checkout Completed, but not paid, it says the "buyer will contact you to pay with credit card."

But I already sent the item to him, but he still not paid me. So How can I tell ebay to list me orders which are 100% paid ?

thanks

**Comment by michabbb** [comment]
@waza123x as far as i know, you *cannot* ;) payment is something, you have to check in a 2nd instance. for example: an order may be "completed" but something is still pending with the paypal-payment. so to be 100% sure whats going on, you should use the paypal-api to get a clear info. if you don´t want to check something outside your response, you can check the [eBayPaymentStatus](http://developer.ebay.com/devzone/xml/docs/reference/ebay/extra/GtOrdrs.Rspns.OrdrArry.Ordr.ChcktStts.ByPymntStts.html).
