### ISSUE TITLE
Is it possible to get the ad fee for an order?

### ISSUE THREAD

**Issue by boosis** [davidtsadler/ebay-sdk-php#54]
Hi,

I was wondering if it's possible to get the ad fee eBay charges when an order is placed via promoted listing?

Thanks

**Comment by michabbb** [comment]
@boosis this question is not related to this framework. you should consult the [ebay docu](http://developer.ebay.com/devzone/xml/docs/reference/ebay/getorders.html) or ask the [forum](https://forums.developer.ebay.com/). just a hint: in case no place gives answeres: ebay offers [professional support](http://developer.ebay.com/signin?return_to=%2Fsupport%2Fdevelopersupport%2F).

**Comment by boosis** [comment]
Noted.
