### ISSUE TITLE
[support] curl options to guzzle

### ISSUE THREAD

**Issue by quazardous** [davidtsadler/ebay-sdk-php#58]
How can I passe curl options to guzzle ?

http://docs.guzzlephp.org/en/latest/faq.html?highlight=curlopt#how-can-i-add-custom-curl-options

```php
$service = new FindingService([
                'credentials' => [...],
                'globalId'    => ...,
                'curl' => [...],
            ]);
```

**Comment by davidtsadler** [comment]
There is currently no way to set the PHP cURL options but I can look at adding such a configuration option to the SDK. Depending on what options you are wanting to set, there may already be a corresponding configuration option. For example `CURLOPT_VERBOSE` is available through the [debug](http://devbay.net/sdk/guides/guide/configuration.html#http-options-debug) option.

**Comment by quazardous** [comment]
thx David !
I have asked the question in guzzle/guzzle/issues#1682

PS I'm a David too
