### ISSUE TITLE
[Old API] Add Product API

### ISSUE THREAD

**Issue by quazardous** [davidtsadler/ebay-sdk-php#59]
Hi,

is possible to add support for the Product API ?

http://developer.ebay.com/Devzone/product/CallRef/index.html

this API has the benefit to return ePID + ISBN + UPC + EAN the finding API does only return ePID

**Comment by davidtsadler** [comment]
I'm currently working on adding several of the new APIs that have been announced so can look at supporting the Product API as well. Aiming for a January release.

**Comment by quazardous** [comment]
@davidtsadler thx

**Comment by quazardous** [comment]
just an idea, but a little dev oriented doc (structure, command lines, etc) could give some pointers to others devs on how to fork and add features to your excellent SDK. I ve seen some generated files...

**Comment by davidtsadler** [comment]
I've been thinking about something along the same lines. It would be something to look at after I've supported the other APIs.

**Comment by quazardous** [comment]
good to know ! keep the good work

**Comment by quazardous** [comment]
thx
