### ISSUE TITLE
Get ProductListingDetails out of GetMyeBaySellingRequestType

### ISSUE THREAD

**Issue by aario** [davidtsadler/ebay-sdk-php#65]
Hi,
I send a GetMyeBaySellingRequest and in the Item I receive there is no ProductListingDetails. How can I get this Item?
I have searched several different combinations of keywords on google and read through several pages of search results and never found anyone talking about that. There should be some parameter/magic number that tells ebay to send more details or another request per each item to get them.
Please help. Thanks.

**Comment by davidtsadler** [comment]
If you look at the fields that is returned for [GetMyeBaySelling](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetMyeBaySelling.html#Output) you will see that ProductListingDetails is not available.

Sadly this information is not returned in many of the operations. A complete list of which calls return this field can be found in the [documentation](http://developer.ebay.com/devzone/xml/docs/Reference/eBay/fieldindex.html#ProductListingDetails)

You may have to make separate calls to [GetItem](http://developer.ebay.com/devzone/xml/docs/Reference/eBay/GetItem.html#Response.Item.ProductListingDetails) to get what you need.

**Comment by aario** [comment]
Thanks a lot for prompt response. And thanks for the useful code.
