### ISSUE TITLE
No quantity returned when calling GetSingleItem service

### ISSUE THREAD

**Issue by jasondalycan** [davidtsadler/ebay-sdk-php#66]
Hi,

When calling the GetSingleItem service there does not appear to be an Item->Quantity value returned (yet the eBay listing displays a quantity).  Is this element missing from the response object?

**Comment by michabbb** [comment]
looking into [GetSingleItemResponseType](https://github.com/davidtsadler/ebay-sdk-php/blob/9d490d7c0838eb0c3ccb9ac80e2645c05d7f9612/src/Shopping/Types/GetSingleItemResponseType.php) shows, that there is a item, that is related to [SimpleItemType](https://github.com/davidtsadler/ebay-sdk-php/blob/9d490d7c0838eb0c3ccb9ac80e2645c05d7f9612/src/Shopping/Types/SimpleItemType.php#L29) and it has "Quantity", i guess it's more a matter if "how you access" the item from the response object.

**Comment by davidtsadler** [comment]
As noted in the documentation for [GetSingleItem](http://developer.ebay.com/DevZone/shopping/docs/CallRef/GetSingleItem.html#BestPractices).

> GetSingleItem has been optimized for response size, speed and usability. So, it returns the most commonly used fields by default. Use the IncludeSelector field to get more data—but please note that getting more data can result in longer response times.

This means that some information is not returned unless you specify a value for `IncludeSelector` in the request. If you do not specify a value then only some fields are returned. A list of the fields and which value you need to specify can be found in the [documentation](http://developer.ebay.com/DevZone/shopping/docs/CallRef/GetSingleItem.html#IncludeSelector) 

If you use that table to lookup the field `Quantity` it states that it will not be returned unless `Details` is specified. E.g

```php
$request->IncludeSelector = 'Details';
```
