### ISSUE TITLE
All  profile id's are same and wrong in sandbox

### ISSUE THREAD

**Issue by webDevelopmentTechnologys** [davidtsadler/ebay-sdk-php#72]
While trying to get profile ids by using **getSellerProfiles** call, all profile ids returns same and wrong integer in sandbox environment. (Using SDK's **"ebay-sdk-example/business-policies-management/01-retrieve-all-policies.php"** file)

**Comment by davidtsadler** [comment]
Do you know if your system is using the 32Bit version of PHP? If so you may be encountering the issue mentioned in the guides http://devbay.net/sdk/guides/getting-started/requirements.html#using-the-sdk-with-32-bit-systems

**Comment by webDevelopmentTechnologys** [comment]
**My Server Software :**  Apache/2.4.23 (Win64) PHP/5.6.25 - Port defined for Apache: 80

**Comment by davidtsadler** [comment]
What value for each profile id is been returned?

**Comment by webDevelopmentTechnologys** [comment]
All profile ids are : **2147483647**

**Comment by webDevelopmentTechnologys** [comment]
Ok,  **2147483647** is my **PHP_INT_MAX.** . So, I am using 32-bit version.

**Comment by davidtsadler** [comment]
Sounds like it.
