### ISSUE TITLE
Fatal error while parsing orders in FullfilmentServer

### ISSUE THREAD

**Issue by ProFillMS** [davidtsadler/ebay-sdk-php#73]
Following code:
`$service = new Services\FulfillmentService(array(
	'credentials' => $credentials,
	'authorization' => $userToken
));

$request = new Types\GetOrdersRestRequest();
$request->limit = '1000';

$response = $service->getOrders($request);`
results in this error message:
`c:\xampp\php64\php -f updateEbayOrders.php
PHP Catchable fatal error:  Argument 1 passed to DTS\eBaySDK\Fulfillment\Types\OrderFulfillmentStatus::__construct() must be of the type array, string given, called in C:\Users\Besitzer\Documents\eclipse\cli-worker\Classes\DTS\eBaySDK\Types\BaseType.php on line 676 and defined in C:\Users\Besitzer\Documents\eclipse\cli-worker\Classes\DTS\eBaySDK\Fulfillment\Types\OrderFulfillmentStatus.php on line 27

Catchable fatal error: Argument 1 passed to DTS\eBaySDK\Fulfillment\Types\OrderFulfillmentStatus::__construct() must be of the type array, string given, called in C:\Users\Besitzer\Documents\eclipse\cli-worker\Classes\DTS\eBaySDK\Types\BaseType.php on line 676 and defined in C:\Users\Besitzer\Documents\eclipse\cli-worker\Classes\DTS\eBaySDK\Fulfillment\Types\OrderFulfillmentStatus.php on line 27`
There error is the same for both Windows runtimes I tried: PHP 7.0.6 x86 and PHP 5.6.30 x64.
When enabling the debug, the returning JSON looks perfectly normal. I only found 2 different kind of entries for OrderFulfillmentStatus:
`"orderFulfillmentStatus": "FULFILLED"
"orderFulfillmentStatus": "NOT_STARTED"`

I have downloaded the ZIP installation of the 8.0.0 release.

**Comment by davidtsadler** [comment]
Is possible for you to provide a copy of the JSON response so that I can look into this issue?

**Comment by ProFillMS** [comment]
I can't attach the file publicity, since it contains actual live data. Can I someone send that file/text privately?

**Comment by davidtsadler** [comment]
Understandable. It's OK I can re-create the issue without it. I think I've tracked down the cause to be this line https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Fulfillment/Types/Order.php#L85

As an ugly hack you may wish to change it to

```php
'type' => 'string'
```

**Comment by ProFillMS** [comment]
I think I understand what it's supposed to prevent, but just chaning the file doesn't prevent the error to be thrown. Do I need to run some script or prune some cache before the change takes effect?

**Comment by davidtsadler** [comment]
You're correct about changing https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Fulfillment/Types/FulfillmentStartInstruction.php#L41 as well so thanks for spotting that. I'll make sure it gets fixed along with the other fields.

Not sure at the moment about the refund error. Chances are one of the classes is missing the property from it's definition. The problem is that these classes are generated automatically from information provided by eBay. I'll need to check that information to see if it's correct. I have problems in the past when eBay's WSDLs was missing various fields.

**Comment by ProFillMS** [comment]
Is there any expectation of some soon testable code that can load the FullfillmentService API? I thought I could substitute the API using the SoldList from the TradingService, but it uses shortend (as in cut off by the ! sign) orderIds and calling it OrderLineItemID and it contains the lineItemId not all. Since I having some existing order tables from using Amazon API, I was counting on those fields as useable unique keys.

**Comment by davidtsadler** [comment]
I'm afraid that I don't have an ETA at the moment. I will try and look at this issue over the next few days. I've been busy in my free time so I haven't been able to devote as much time as I would have liked.

**Comment by ProFillMS** [comment]
Thanks for answering it. Knowing I have to find something myself is sufficient to know. At least I just stumbled over the getOrders() in der TradingService which does work adapting from the 11-get-my-ebay-selling.php example. It also uses the less troublesome authentification, since those oAuth tokens are seriously underperforming in useability, since it would be hard to daily generate a new one to begin with...

**Comment by davidtsadler** [comment]
There's a 9.0.0 release that hopefully fixes the issue with the [orderFulfillmentStatus](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Fulfillment/Types/Order.php#L85) and [fulfillmentInstructionsType](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Fulfillment/Types/FulfillmentStartInstruction.php#L41) properties. 

I'm still looking into why it thinks the refunds property doesn't exists. As far as I can tell from the [eBay documentation](https://developer.ebay.com/devzone/rest/api-ref/fulfillment/order__get.html#Response.orders.paymentSummary.refunds) there is only the one refunds property and the SDK [should already be handling it](https://github.com/davidtsadler/ebay-sdk-php/blob/master/src/Fulfillment/Types/PaymentSummary.php#L31).

**Comment by davidtsadler** [comment]
The 13.0.0 release now ignores any properties that the SDK is not aware of. This may resolve this issue.
