### ISSUE TITLE
User authorization

### ISSUE THREAD

**Issue by dennisdup** [davidtsadler/ebay-sdk-php#74]
Is it possible to authorize ebay user with this SDK, get access token and use it to get details of that user account ?

**Comment by davidtsadler** [comment]
It depends on which authorisation your project needs. If you want an Auth'n'auth token for use with the Trading service then this will be possible with the SDK. The API provides the two operations [GetSessionID](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetSessionID.html) and [FetchToken](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/FetchToken.html) which you can call with the SDK.

If you are looking to use an OAuth token for the new RESTful APIs you are going to have to go outside the SDK as it's currently not supported. There has been some discussion over at https://groups.google.com/d/msg/ebay-sdk-php/JUHcEtdD9gg/inND9c5MDQAJ which may be of use.

I'm looking at seeing if I can add something to the SDK that would make it easier to get the OAuth token but I don't have an ETA yet.

**Comment by dennisdup** [comment]
Alright, seems i have to do it then. Could you please then assist with this error i am having:
[error](http://stackoverflow.com/questions/42549023/using-ebay-oauth) .

**Comment by davidtsadler** [comment]
Sure :)

**Comment by davidtsadler** [comment]
I'm going to close this as I aim to address this issue in #75.

**Comment by ediceapi** [comment]
New OAUTH2 functions of this API are working. I am able to get an OAUTH Token and a Refres OAUTH User token using API. However, It is not clear to me how to use these for BULK Data exchange APIs - Or if it is even possible to use AUTH2 with Bulk Data Exchange API functions.

**Comment by michabbb** [comment]
@ediceapi read the docs debug the code, use the regular ebay forum.

https://developer.ebay.com/api-docs/static/oauth-trad-apis.html
