### ISSUE TITLE
InventoryService::updateOffer() always fails

### ISSUE THREAD

**Issue by chuhta** [davidtsadler/ebay-sdk-php#76]
The call to the InventoryService updateOffer() will always fail with a vague error message about "" (blank) being invalid.

This appears to be due to the InventoryService having a mixed up mapping between the resource (offer_Id) and the param (offerId) for this request type. The UpdateOfferRestRequest has the property as (offerId).

**Comment by davidtsadler** [comment]
Thanks for spotting the mixed up mapping. The [9.0.1](https://github.com/davidtsadler/ebay-sdk-php/releases/tag/9.0.1) release should have hopefully fixed this.
