### ISSUE TITLE
PHP Fatal error:  Call to a member function attachment() on null in BaseService.php on line 160

### ISSUE THREAD

**Issue by tajny** [davidtsadler/ebay-sdk-php#78]
For about 5 months i'm using ebay sdk , ocassionaly it gives me fatal error during  async request, is it possible to add throw declaration , eg. RuntimeException ? 

`if (is_null($response)) throw new RuntimeException....`

?

**Comment by davidtsadler** [comment]
I'll look into improving how the SDK handles null responses.

**Comment by agavss** [comment]
Recently i'm having a similar issue: `Fatal error: Call to a member function attachment() on a non-object in BaseService.php on line 160`
The sdk version i'm using is 7.0, doing an upgrade will solve this issue?
Thanks

**Comment by gaiterjones** [comment]
I am seeing this now too, am running v5, updating to 13 breaks my code at the moment - was this fixed?

**Comment by cgaugel** [comment]
Any news here?
