### ISSUE TITLE
Site Constants

### ISSUE THREAD

**Issue by kingsaj** [davidtsadler/ebay-sdk-php#79]
Hi,

First of all I want to say fantastic work, this library made my life so much easier.

My query was about the constants for siteId when setting up the TradingServices.

DTS\eBaySDK\Constants\SiteIds contains 'GB' for the United Kingdon

but when yo make a GetUserRequest to ebay its ruturns 'UK' as the site

Also according to the docs, it should be UK?
https://developer.ebay.com/devzone/xml/docs/reference/ebay/types/SiteCodeType.html

Thanks

**Comment by davidtsadler** [comment]
GetUserRequest does return UK but this value has nothing to do with the site id constant name.  The constants could have been called anything, E.g SITE_UK or UK_SITE. The constants are just a means to specificity a site or global id in your code.
