### ISSUE TITLE
Type check Enum types

### ISSUE THREAD

**Issue by dtjones** [davidtsadler/ebay-sdk-php#8]
If all Enum properties have the "propertytNameCodeType" class e.g.

    ItemType $BuyerProtection  maps to  BuyerProtectionCodeType 
   
then an alternative type checking method would allow for better distinction between an actual "string" type and an "string enum" type which would make it easier to check whether the provided value was valid. 
If all \DTS\eBaySDK\ {service} \Enums\{ .......CodeType} class Constants are ALL strings then the method is even tidier.

Heres the change

__ConfigurationResolver__

    /** @var array Map of type to function that confirms type. */
    private static $typeMap = [
         'enum' => 'is_string' 

__ItemType__ 

    * @property \DTS\eBaySDK\Trading\Enums\BuyerProtectionCodeType $BuyerProtection
    ....
    // From 
    'BuyerProtection' => array(
            'type' => 'string',
    // To 
    'BuyerProtection' => array(
            'type' => 'enum',

If the Constants type differs then a much uglier solution could be used 

    private static $typeMap = [
         'enum_string' => 'is_string',
         'enum_bool' => 'is_bool' 

     'BuyerProtection' => array(
            'type' => 'enum_string',

__WHY?__

I'm using if for form validation and automation. 

I've been using this snippet of code to get some details about different class properties. 

	$class_name = "\DTS\\eBaySDK\Trading\Types\\" . $type . "Type";

	$reflectionClass = new \ReflectionClass($class_name);

	$staticProperties = $reflectionClass->getStaticProperties();

	$properties = (isset($staticProperties['properties'][$class_name]) ? $staticProperties['properties'][$class_name] : $staticProperties['propertyTypes'];

    foreach($properties as $property){

        if($property['type'] == 'string'){
            $field['type'] = 'textbox';
            if(!empty($property]['unbound'])){
                // array allowed multiple fields
            } else {
                 // single field
            }
        }
        ....

    // but the change would allow for something like 

        if($property['type'] == 'enum'){

           $field['type'] = 'select';
            if(!empty($property]['unbound'])){
                // array allowed multiple fields e.g. (payment methods)
            } else {
                 // single field
            }

            $reflectionClass = new \ReflectionClass("\DTS\\eBaySDK\Trading\Enums\\" . $property[''elementName'] . "CodeType");
            $field['options'] = $reflectionClass->getConstants(); //key =>value pair
        }

         ...
        $fields [] = $field;
    }

It would allow you to grab the constants to use as the options of a select element dynamically and the checkType method could check that the $provided value is valid by checking against the classes constants.

Whatever the outcome of this, I really think there should be a way of finding out the actual class of a enum property.

**Comment by davidtsadler** [comment]
Firstly sorry for not addressing this issue sooner. At the present time this is a feature that I don't want to implement in the SDK as it's dependant upon a protected property that may be removed in future versions.
