### ISSUE TITLE
getProductDetails doesn't return productDetails array ?

### ISSUE THREAD

**Issue by zLegend-210** [davidtsadler/ebay-sdk-php#80]
First of all thank you for your massive work and improving this impressive package so keep the good work up :).

I'm trying to use getProductDetails request in order to use eBay catalog to prefill custom specifications and attributes, but the response only contains product array with identifier "ePID" without productDetails array which supposed to contain paired attribute name-value. Is there something like detailLevel should I provide or what else ?

Huge thanks in advance 

here is my code

$request = new Product\Types\GetProductDetailsRequest();
 $request->productDetailsRequest [] = new Product\Types\ProductDetailsRequestType();
 $request->productDetailsRequest->dataset = ['DisplayableProductDetails'];
 $request->productDetailsRequest[0]->productIdentifier = new Product\Types\ProductIdentifier();
 $request->productDetailsRequest[0]->productIdentifier->UPC = $upc;
        
$response = self::$service->getProductDetails($request);
       
 if (isset($response->errorMessage)) {
        foreach ($response->errorMessage->error as $error) {
            printf(
                    "%s: %s\n\n",
                    $error->severity=== Product\Enums\ErrorSeverity::C_ERROR ? 'Error' : 'Warning',
                    $error->message
                );
            }
        }
        if ($response->ack !== 'Failure') {
            return $response;
        }

**Comment by davidtsadler** [comment]
There's no equivalent to detailLevel as far as I know.  I don't know why eBay haven't returned any product details.  It could be that their catalogue is not complete and is missing information for some UPCs
