### ISSUE TITLE
Emergency! Buyer Email is empty in calls.

### ISSUE THREAD

**Issue by voskobovich** [davidtsadler/ebay-sdk-php#81]
Why the response did not contain BuyerEmail?
The official version of the SDK it worked.

Documentation: [click](http://developer.ebay.com/Devzone/xml/docs/Reference/ebay/GetSellingManagerSaleRecord.html#Response.SellingManagerSoldOrder.BuyerEmail)

Request Headers:

```text
https://api.ebay.com/ws/api.dll
X-EBAY-API-COMPATIBILITY-LEVEL: 993
X-EBAY-API-CALL-NAME: GetSellingManagerSaleRecord
X-EBAY-API-SITEID: 0
X-EBAY-API-APP-NAME: APP-NAME
X-EBAY-API-CERT-NAME: CERT-NAME
X-EBAY-API-DEV-NAME: DEV-NAME 
Content-Type: text/xml
Content-Length: 1202
```

Request Body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<GetSellingManagerSaleRecordRequest xmlns="urn:ebay:apis:eBLBaseComponents">
   <RequesterCredentials>
      <eBayAuthToken>EBAY-AUTH-TOKEN</eBayAuthToken>
   </RequesterCredentials>
   <OrderLineItemID>301925844209-1336125899020</OrderLineItemID>
</GetSellingManagerSaleRecordRequest>
```

Response Body:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<GetSellingManagerSaleRecordResponse xmlns="urn:ebay:apis:eBLBaseComponents">
   <Timestamp>2017-03-14T13:46:29.636Z</Timestamp>
   <Ack>Success</Ack>
   <Version>1003</Version>
   <Build>E1003_UNI_API5_18343062_R1</Build>
   <SellingManagerSoldOrder>
      <SellingManagerSoldTransaction>
         <TransactionID>133612534534899020</TransactionID>
         <ItemID>345345345</ItemID>
         <QuantitySold>1</QuantitySold>
         <ItemPrice currencyID="USD">63452.99</ItemPrice>
         <SubtotalAmount currencyID="USD">62.99</SubtotalAmount>
         <ItemTitle>Vulcan Diesel Performance - VpMax Big Line Dual Feed Kit</ItemTitle>
         <Shipment>
            <ShippingCarrierUsed>UPS</ShippingCarrierUsed>
            <ShipmentTrackingNumber>354345</ShipmentTrackingNumber>
            <DeliveryStatus>Delivered</DeliveryStatus>
         </Shipment>
         <OrderLineItemID>301925844209-1336125899020</OrderLineItemID>
      </SellingManagerSoldTransaction>
      <ShippingAddress>
         <Name>cedric dodson</Name>
         <Street1>444 richland rd</Street1>
         <CityName>yuba city</CityName>
         <StateOrProvince>CA</StateOrProvince>
         <Country>US</Country>
         <Phone>530-673-34489</Phone>
         <PostalCode>934591-5740</PostalCode>
         <Phone2 />
      </ShippingAddress>
      <ShippingDetails>
         <SalesTax />
         <ShippingServiceOptions>
            <ShippingService>UPSGround</ShippingService>
            <ShippingServiceCost currencyID="USD">0.0</ShippingServiceCost>
         </ShippingServiceOptions>
      </ShippingDetails>
      <TotalAmount currencyID="USD">345345.99</TotalAmount>
      <ActualShippingCost currencyID="USD">0.0</ActualShippingCost>
      <AdjustmentAmount currencyID="USD">0.0</AdjustmentAmount>
      <OrderStatus>
         <CheckoutStatus>CheckoutComplete</CheckoutStatus>
         <PayPalTransactionID>345345</PayPalTransactionID>
         <PaymentMethodUsed>PayPal</PaymentMethodUsed>
         <FeedbackSent>true</FeedbackSent>
         <PaymentHoldStatus>None</PaymentHoldStatus>
         <ShippedTime>2016-12-29T05:59:59.000Z</ShippedTime>
         <PaidTime>2016-12-25T18:43:23.000Z</PaidTime>
      </OrderStatus>
      <EmailsSent>3</EmailsSent>
      <BuyerID>345345</BuyerID>
      <SaleRecordID>34545</SaleRecordID>
      <CreationTime>2016-12-25T18:43:23.000Z</CreationTime>
   </SellingManagerSoldOrder>
</GetSellingManagerSaleRecordResponse>
```

**Comment by michabbb** [comment]
i remember a [thread](https://groups.google.com/d/msg/ebay-sdk-php/MESP_eDI27s/eLn87rwwDgAJ) in the groups, maybe that helps a bit....

**Comment by voskobovich** [comment]
@michabbb 

```php
$request->DetailLevel = ['ReturnAll'];
```
No, it didn't help.

**Comment by davidtsadler** [comment]
Can you replicate the issue outside of the SDK by using the API testing tool?

**Comment by voskobovich** [comment]
@davidtsadler 
I have not found how to do it. Can you provide a link?

**Comment by davidtsadler** [comment]
https://developer.ebay.com/my/api_test_tool?index=0&api=trading&call=GetSellingManagerSaleRecord&variation=xml

You will need to log into your eBay developer account to access their tool. Simple choose the trading service and the GetSellingManagerSaleRecord operation. You will need to copy and paste an auth token before making the request and enter your own XML.

**Comment by voskobovich** [comment]
@davidtsadler I tested using the eBay API Tool and it works.

**Comment by davidtsadler** [comment]
Are you using the same credentials in the SDK that you are using in the explorer?

**Comment by voskobovich** [comment]
Yes. AuthToken the same.

**Comment by michabbb** [comment]
@voskobovich you are only able to see such confidential data (email, phone) if your dev account is linked to the ebay account and if the data is not too old, and if thats a german ebay account, bad luck, ebay takes care of german law and even the ebay owner itself is not allow to see customer data via api, absolutly stupid !!

**Comment by voskobovich** [comment]
@michabbb We all worked on a basic ebay SDK. And we would like to get the same result using this SDK :)

**Comment by davidtsadler** [comment]
One thing I've noticed is that the API explorer is using 967 of the trading service. You could pass that into the SDK to see if it affects the result.

```php
$trading = new TradingService([
    'apiVersion' => '967'
]);
```

**Comment by davidtsadler** [comment]
Would be interested to know what API version the basic eBay SDK is also using.

**Comment by michabbb** [comment]
@voskobovich ebay is not interested in what you care or not, i just wanted to give you a hint that there are special circumstances that have nothing todo with technical issues, more than with law issues - i got this answer directly from the technical ebay support. i don´t know if other countries like germany have these stupid limitations, but whoever is reading this, should be aware of that.

**Comment by voskobovich** [comment]
I am using the latest SDK version 9.0.1 and version of the ebay API 993. 
Previously, we used the 825 version which is no longer supported. And there is the email of the buyer was present.

**Comment by davidtsadler** [comment]
@voskobovich voskobovich Can you try passing 967 via the SDK. Want to keep it the same as the explorer so that I can see if there is an issue with the SDK.

**Comment by davidtsadler** [comment]
@voskobovich You can also pass 993 into the explorer to see if the email is now longer returned.

**Comment by davidtsadler** [comment]
There is a deprecation notice for GetSellingManagerSaleRecord so I want to rule out a few things before I spend time changing any code.

> This call is subject to change without notice; the deprecation process is inapplicable to this call.

**Comment by voskobovich** [comment]
Email the buyer returns all versions of ebay API using the api explorer, but not returned via the SDK.
967, 983, 993 and more...
What evidence should I provide?

**Comment by davidtsadler** [comment]
Copy you provide a copy of the XML from the explorer? Want to make sure the SDK is not missing anything when it builds the request.

**Comment by davidtsadler** [comment]
I'm assuming that you can also get access to the XML generated by the SDK as you've copied it into the issue. It's a long shot but you could try coping that XML into the explorer to see if it works or not. I'm trying to see what is different between how the SDK is sending the request and the explorer.

If there is an issue with the SDK it could be any number of reasons.

- The SDK is generating the wrong XML.
- The SDK is generating the wrong HTTP headers. The explorer doesn't send the app, dev or cert ID as part of the request, but the SDK does!
- You are not populating the request correctly.
- Wrong credentials are been use.
- eBay are only returning the information if the explorer is been used. Highly unlikely as it seems the basic SDK works.

It's going to be difficult for me to give an answer at the moment as I don't have any orders on my sandbox eBay account. I would need some time to set things up before I can try and re-create the issue myself.

**Comment by voskobovich** [comment]
Tell the file and line of code where you take the raw response from eBay API?

**Comment by davidtsadler** [comment]
I take it the XML in this issue is not from the SDK then?

**Comment by voskobovich** [comment]
Request Headers:

```
https://api.ebay.com/ws/api.dll

X-EBAY-API-SITEID:0
X-EBAY-API-COMPATIBILITY-LEVEL:967
X-EBAY-API-CALL-NAME:GetSellingManagerSoldListings
```

Request Body:

```xml
<?xml version="1.0" encoding="utf-8"?>
<GetSellingManagerSoldListingsRequest xmlns="urn:ebay:apis:eBLBaseComponents">
  <!-- SellingManager API calls are only available for Selling Manager and Selling Manager Pro subscribers -->
  <RequesterCredentials>
    <eBayAuthToken>qwerty12345</eBayAuthToken>
  </RequesterCredentials>
	<ErrorLanguage>en_US</ErrorLanguage>
	<WarningLevel>High</WarningLevel>
</GetSellingManagerSoldListingsRequest>
```

Response Headers:

```txt
content-type:text/xml
guid:15acd410-0490-a624-d4a4-a6c4d610906a
server:Apache-Coyote/1.1
x-ebay-api-pool-name:___cDRidW90Zmlqbm1iZWhxYA==
x-ebay-api-server-name:___dWtgMWQ3MWYrNWE9ZCgyNSg2MzMoMDErNzQzPz43OzU=
x-ebay-esb-app-name:
x-ebay-esb-call-name:GetSellingManagerSoldListings
x-ebay-esb-guid:urn:uuid:a03f169b-9456-4aa1-9939-8aed92464292
x-ebay-esb-siteid:0
x-ebay-request-id:15acd410-0490-a624-d4a4-a6c4d610906a!ws.api.dll!10.98.77.74!esbtrading[
date:Tue, 14 Mar 2017 14:37:58 GMT
content-length:77428
connection:Keep-Alive
```

Response Body

```xml
<?xml version="1.0" encoding="UTF-8"?>
<GetSellingManagerSoldListingsResponse 
  xmlns="urn:ebay:apis:eBLBaseComponents">
  <Timestamp>2017-03-14T14:37:59.006Z</Timestamp>
  <Ack>Success</Ack>
  <Version>967</Version>
  <Build>E967_CORE_APISELLING_17965876_R1</Build>
  <SaleRecord>
    <SellingManagerSoldTransaction>
      <TransactionID>1363796164020</TransactionID>
      <SaleRecordID>535142</SaleRecordID>
      <ItemID>301957492129</ItemID>
      <QuantitySold>1</QuantitySold>
      <ItemTitle>Sherman 698-61L - Driver Side Trunk Filler Panel</ItemTitle>
      <ListingType>FixedPriceItem</ListingType>
      <Relisted>false</Relisted>
      <SecondChanceOfferSent>false</SecondChanceOfferSent>
      <CustomLabel>698-61L_1503_d1</CustomLabel>
      <SoldOn>eBay</SoldOn>
      <ListedOn>eBay</ListedOn>
      <CharityListing>false</CharityListing>
      <OrderLineItemID>301957492129-1363796164020</OrderLineItemID>
    </SellingManagerSoldTransaction>
    <ShippingAddress>
      <Name>asdfasdfasdf</Name>
      <PostalCode>44sdf0-4853</PostalCode>
    </ShippingAddress>
    <ShippingDetails>
      <ShippingType>Calculated</ShippingType>
    </ShippingDetails>
    <TotalAmount currencyID="USD">2123.42</TotalAmount>
    <TotalQuantity>1</TotalQuantity>
    <ActualShippingCost currencyID="USD">12313.33</ActualShippingCost>
    <OrderStatus>
      <CheckoutStatus>CheckoutComplete</CheckoutStatus>
      <PaidStatus>Paid</PaidStatus>
      <ShippedStatus>Unshipped</ShippedStatus>
      <PaymentMethodUsed>PayPal</PaymentMethodUsed>
      <FeedbackSent>false</FeedbackSent>
      <TotalEmailsSent>0</TotalEmailsSent>
      <PaidTime>2017-03-14T14:37:51.000Z</PaidTime>
    </OrderStatus>
    <SalePrice currencyID="USD">1234.09</SalePrice>
    <DaysSinceSale>0</DaysSinceSale>
    <BuyerID>1234123</BuyerID>
    <BuyerEmail>ewrqe@qwewerd.dk</BuyerEmail>
    <SaleRecordID>12341234</SaleRecordID>
    <CreationTime>2017-03-14T14:37:50.000Z</CreationTime>
  </SaleRecord>
  <PaginationResult>
    <TotalNumberOfPages>111</TotalNumberOfPages>
    <TotalNumberOfEntries>22222</TotalNumberOfEntries>
  </PaginationResult>
</GetSellingManagerSoldListingsResponse>
```

**Comment by voskobovich** [comment]
@davidtsadler Yes, I need the raw response from eBay.com.

**Comment by davidtsadler** [comment]
There is a [debug](http://devbay.net/sdk/guides/guide/configuration.html#debug) configuration option. `logfn` can be a function that saves the debug messages to a file. Note that you will want to append to the file as the function will be called multiple times.

I also need to check that you did pass a OrderLineItemID via the explorer. It's missing from the second xml example so I'm assuming that you have either removed it when copying the XML or that it wasn't used in the explorer.

**Comment by voskobovich** [comment]
I couldn't get Explorer to pass the search parameters. Therefore received all the entries and picked the first example.

**Comment by davidtsadler** [comment]
Can you try leaving out the OrderLineItemID  via the SDK? Want to try and get both systems working the same.

**Comment by davidtsadler** [comment]
> I couldn't get Explorer to pass the search parameters. 

You should be able to copy `<OrderLineItemID>301925844209-1336125899020</OrderLineItemID>` into the request body field of the tool.

> Therefore received all the entries and picked the first example.

Just want you to confirm that you have seen the explorer return the entry for  `301925844209-1336125899020`  (Vulcan Diesel Performance), and that the email was present.

The reason I ask is that the explorer has provided the email for a different entry, `301957492129-1363796164020` (Sherman 698-61L). Would interesting to see if the explorer is consistently returning the email for different records or if it's actually only returing them for some.

Also have you tried passing `301957492129-1363796164020` (a different sale record), via the API?

**Comment by alka-git** [comment]
Hi, for new orders is Buyer->Email not empty! After one-two days this will be set to empty! All orders from today have Buyer emails and orders from yesterday are empty for me.

**Comment by davidtsadler** [comment]
Looks like eBay does something to old orders. May be related to privacy settings in eBay or country laws. Not familiar with how the order side of the API works so can't say for definite.

**Comment by voskobovich** [comment]
@alka-git
