### ISSUE TITLE
ShoppingService const API_VERSION =983

### ISSUE THREAD

**Issue by moggiex** [davidtsadler/ebay-sdk-php#82]
Howdy David,

It appears that 983 is an invalid API version for the shopping API. 

Switched to 967 for GetSingleItem() calls on the shopping API and that's stopped returning these two messages as errors being returned:

- Warning: Version specified is above current version.
- Version specified is above current version.  Setting version to current release version.

Which is odd as on the top of their documentation here [http://developer.ebay.com/Devzone/Shopping/docs/CallRef/GetSingleItem.html](http://developer.ebay.com/Devzone/Shopping/docs/CallRef/GetSingleItem.html ) it says version 997 which is even higher, yet still returns the same two messages above.

Fantastic work by the way,

Matt

**Comment by davidtsadler** [comment]
The warning is one of those bizarre ones that eBay throws at you every now and then. It seems that the API is not in sync with the current documentation and specifying the correct value doesn't necessary mean that it will work. I found that looking at the ``Version`` field in the response normally tells you the highest version number that the API will support. Sadly even this value is not consistent. Depending on which operation you call a different version could be returned.  I've seen ``FindProducts`` return ``957`` and ``GetSingleItem`` return ``981``. I get the impression that it depends on which of their API servers your request hits as to whether the version you've specified will be accepted.
