### ISSUE TITLE
CredentialsProvider.php  typo

### ISSUE THREAD

**Issue by dtjones** [davidtsadler/ebay-sdk-php#9]
Beta branch. 
Use of undefined constant homePath - assumed 'homePath' in eBaySDK\Credentials\CredentialsProvider.php</b> on line <b>170</b>

    return ($homeDrive && homePath) ? $homeDrive . $homePath : null;

should be 

    return ($homeDrive && $homePath) ? $homeDrive . $homePath : null;

**Comment by dtjones** [comment]
also constants in Constants\SiteIds are all ints but the config expects a string.
`'siteId' => Constants\SiteIds::GB,` gives me this error 
Uncaught exception 'InvalidArgumentException' with message 'Invalid configuration value provided for "siteId". Expected string, but got <pre class='xdebug-var-dump' dir='ltr'><small>int</small> <font color='#4e9a06'>3</font> </pre> 

for now ive just casted the const to a string

`'siteId' => (string)Constants\SiteIds::GB,`

**Comment by davidtsadler** [comment]
Cheers for spotting these. I completely missed them. Will get them fixed in the next code push.

**Comment by dtjones** [comment]
Sorry didn't want to open another issue but
for the getcategoryfeatures, eBay recommend that you
 > Retrieve all available data at most once a day for each site that you work with, and store the data locally.

so ideally I would create a trading service then loop through all the siteids that i work with. Each time modifying `service->config[siteId]` before then make the getcategoryfeatures call. 
I might have missed something but it looks like you have to create a new service if you want to use a different siteid, am i correct or can config be modified?
 If not would it be possible to add come kind of setConfig($key, $val)  or setSiteId method added to  \DTS\eBaySDK\Services\BaseService ?

**Comment by dtjones** [comment]
possibly something like 

    private function setConfig($key, $val){

        $this->config[$key] = $val;
        //$resolver = new ConfigurationResolver(static::getConfigDefinitions());
        //$this->config = $resolver->resolve($this->config);
    }

    public function setSiteId($id)
    {
        $this->setConfig('siteId', $id);
        
    }
    public function setGlobalId($id)
    {
         $this->setConfig('globalId', $id);
    }

**Comment by davidtsadler** [comment]
As it stands at the moment you are correct in that you would have to create a new service with the required siteId during each iteration of the loop. Off the top of my head I can't think of any technical reason as to why the SDK can't let you modify configuration options after a service has been created. I'll look into it some more, just to double check, but I think that adding some sort of `setConfig` method may be the solution.

**Comment by davidtsadler** [comment]
I've added a `setConfig` to the beta branch so in future it will be possible to change the configuration of a service object during its lifetime.
