### ISSUE TITLE
sdk don't support additems 

### ISSUE THREAD

**Issue by moxgeek** [davidtsadler/ebay-sdk-php#91]
Hello, seriously I like your sdk and it's helpful, and it's so easy to use it
but i have some questions
first : why don't use add items instead of add item ?
In the eBay documentation
“ AddItems
Use this call to define one to five items and list them on the specified eBay site.”
that will be good.
And how to add item with non-specifing category or just let “ SugesstedCategorie “ try to catch it,.
In my project, I used to create a page when I select mufti items without categories.And add them to ebay..

Thanks :)

**Comment by davidtsadler** [comment]
The SDK does support the AddItems operation. I've added an [example](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/23-add-items.php) of how to do this.

I've recently added a [forum](https://forum.devbay.net/c/php-sdk) where I will do my best to answer questions regarding the usage of the SDK.
