### ISSUE TITLE
Get Item rank for pricing strategies ?

### ISSUE THREAD

**Issue by zLegend-210** [davidtsadler/ebay-sdk-php#94]
I'm trying to build a pricing strategy app where a seller can compare his products to other merchants products. Is there a way to return an item rank like at Amazon API it returns the item's rank with a list of competitors prices ?, I've tried to use FindItemsByProduct call but it returns only products with same specefics based on "UPC and  ePID" without any filtering or even prices decendingly ? 
Thanks and keep up your great work :)

**Comment by davidtsadler** [comment]
I'm afraid I have no idea.

I've provided a forum at https://forum.devbay.net/ and https://groups.google.com/forum/#!forum/ebay-sdk-php where questions regarding the usage of the API may have a better chance of been answered.

Sorry that wasn't much help with answering this question.
