### ISSUE TITLE
does it compatible with ebay motors?

### ISSUE THREAD

**Issue by maxkopych** [davidtsadler/ebay-sdk-php#96]
if yes any insturction or examples for it?
Thanks!

**Comment by sudiptpa** [comment]
May be look at - https://github.com/davidtsadler/ebay-sdk-examples/blob/master/trading/07-add-an-item-with-parts-compatibility.php

You will get few ideas.

**Comment by maxkopych** [comment]
Thanks! I saw this example. But I'm wondering if I can publish(or manage) vehicles on ebay motors with this SDK? I think ebay motors has little different API from regular ebay system. if I'm not mistaken.

**Comment by davidtsadler** [comment]
You can use the SDK to list products on the Motors site. Just make sure that you use the correct site ID. For motors it will be 100. 

Don't know if cars are listed any differently to products. I'm not aware of any API specifically for cars, but maybe there is one?  It could be that you have to specify the relevant vehicle information in your AddFixedPriceItem calls. 

One thing I would try is to list a car on the sandbox site and then pull it back via GetItem. If the information comes back correctly then it would indicate that you could use AddItem or AddFixedPriceItem to list it.
